# database
USER = 'user'
USER_ID = 'user_id'
ROLE_ID = 'role_id'
NAME = 'name'
# user credentials
USERNAME = 'username'
PASSWORD = 'password'
# roles
ROLE = 'role'
ROLES = 'roles'
ADMIN_ROLE = 'admin_role'
ASSISTANT_ROLE = 'assistant_role'
PATIENT_ROLE = 'patient_role'
# patterns
USERNAME_PATTERN = 'username_pattern'
PASSWORD_PATTERN = 'password_pattern'
# messages
MSG_ACCESS_DENIED = 'msg_access_denied'
MSG_INVALID_REQUEST = 'msg_invalid_request'
MSG_ALL_DONE = 'msg_all_done'
MSG_INVALID_USERNAME = 'msg_invalid_username'
MSG_INVALID_PASSWORD = 'msg_invalid_password'
MSG_INVALID_ROLE = 'msg_invalid_role'
MSG_USER_NOT_FOUND = 'msg_user_not_found'
MSG_USER_IS_IN_BASE = 'msg_user_is_in_base'
MSG_USER_DELETED = 'msg_user_deleted'
MSG_USER_UPDATED = 'msg_user_updated'
MSG_CODE = 'msg_code'
MSG_CODES = 'msg_codes'
# token properties and keys
ISS = 'iss'
EXP = 'exp'
EXPIRES_IN = 'expires_in'
TOKEN_TYPE = 'token_type'
JWT = 'JWT'
TOKEN = 'token'
ACCESS_TOKEN = 'access_token'
ACCESS_TOKEN_LIFE_SPAN = 'access_token_life_span'
REFRESH_TOKEN = 'refresh_token'
REFRESH_TOKEN_LIFE_SPAN = 'refresh_token_life_span'
ISSUER = 'issuer'
# paths
SQLITE_DB_PATH = 'sqlite_db_path'
PRIVATE_KEY_PATH = 'private_key'
PUBLIC_KEY_PATH = 'public_key'
