# database and common
USER = 'user'
USERS = 'users'
ID = 'id'
NAME = 'name'
PASSWORD = 'password'
# messages
MSG_ACCESS_DENIED = 'msg_access_denied'
MSG_INVALID_REQUEST = 'msg_invalid_request'
MSG_ALL_DONE = 'msg_all_done'
MSG_INVALID_USERNAME = 'msg_invalid_username'
MSG_INVALID_PASSWORD = 'msg_invalid_password'
MSG_USER_NOT_FOUND = 'msg_user_not_found'
MSG_USER_IS_IN_BASE = 'msg_user_is_in_base'
MSG_CODE = 'msg_code'
MSG_CODES = 'msg_codes'
MSG_TEXT = 'msg_text'
# token properties and keys
ISS = 'iss'
EXP = 'exp'
TOKEN_TYPE = 'token_type'
JWT = 'JWT'
TOKEN = 'token'
ACCESS_TOKEN = 'access_token'
REFRESH_TOKEN = 'refresh_token'
ISSUER = 'issuer'
USERNAME = 'username'
# paths
PUBLIC_KEY_PATH = 'public_key'
AUTH_FLAG = 'auth_flag'
