# database and common
USER = 'user'
USERS = 'users'
ID = 'id'
NAME = 'name'
PASSWORD = 'password'
# patterns
USERNAME_PATTERN = 'username_pattern'
PASSWORD_PATTERN = 'password_pattern'
# messages
MSG_ACCESS_DENIED = 'msg_access_denied'
MSG_INVALID_REQUEST = 'msg_invalid_request'
MSG_ALL_DONE = 'msg_all_done'
MSG_INVALID_USERNAME = 'msg_invalid_username'
MSG_INVALID_PASSWORD = 'msg_invalid_password'
MSG_USER_NOT_FOUND = 'msg_user_not_found'
MSG_USER_IS_IN_BASE = 'msg_user_is_in_base'
MSG_CODE = 'msg_code'
MSG_CODES = 'msg_codes'
MSG_TEXT = 'msg_text'
# token properties and keys
ISS = 'iss'
EXP = 'exp'
EXPIRES_IN = 'expires_in'
TOKEN_TYPE = 'token_type'
JWT = 'JWT'
TOKEN = 'token'
ACCESS_TOKEN = 'access_token'
ACCESS_TOKEN_LIFE_SPAN = 'access_token_life_span'
REFRESH_TOKEN = 'refresh_token'
REFRESH_TOKEN_LIFE_SPAN = 'refresh_token_life_span'
ISSUER = 'issuer'
# paths
SQLITE_DB_PATH = 'sqlite_db_path'
PRIVATE_KEY_PATH = 'private_key'
PUBLIC_KEY_PATH = 'public_key'
