macro(compiler _COMPILER _COVERAGE _SANITIZER _AUTO_TEST)
	if(${_COMPILER} MATCHES "Clang")
		set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -fcolor-diagnostics -std=c++14")
		if (${_SANITIZER} STREQUAL "none" AND NOT ${_COVERAGE})
			set(CMAKE_CXX_FLAGS_RELEASE "${CMAKE_CXX_FLAGS_RELEASE} -O3")
		endif()
		if(${_AUTO_TEST})
			set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -Wdeprecated-declarations")
		endif()
	elseif(${_COMPILER} MATCHES "GNU")
		set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -std=c++14 -Wall")
		if (${_SANITIZER} STREQUAL "none" AND NOT ${_COVERAGE})
			set(CMAKE_CXX_FLAGS_RELEASE "${CMAKE_CXX_FLAGS_RELEASE} -O3")        ## Optimize
		endif()
		set(CMAKE_EXE_LINKER_FLAGS_RELEASE "${CMAKE_EXE_LINKER_FLAGS_RELEASE} -s")  ## Strip binary
	elseif (NOT ${_COMPILER} MATCHES "MSVC")
		set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -std=c++14")
	endif ()
endmacro()
