macro(sanitizer _NAME _INFO _MODE)
    set(${_NAME} ${_MODE} CACHE STRING ${_INFO})
    set_property(CACHE ${_NAME} PROPERTY STRINGS none address memory)

    if(NOT ${_NAME} STREQUAL "none")
         if(NOT CMAKE_CXX_COMPILER_ID MATCHES ".*Clang" OR NOT CMAKE_C_COMPILER_ID MATCHES ".*Clang")
              message("Sanitizers are supported only by Clang")
         elseif(${_MODE} STREQUAL "memory")
              set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -fsanitize=memory -fPIE -pie -fno-omit-frame-pointer")
              set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -fsanitize=memory -fPIE -pie -fno-omit-frame-pointer")
         elseif(${_MODE} STREQUAL "address")
              set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -fsanitize=address -O1 -fno-omit-frame-pointer")
              set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -fsanitize=address -O1 -fno-omit-frame-pointer")
         endif()
    endif()
endmacro()
