/** \file
 *  This C source file was generated by $ANTLR version !Unknown version!
 *
 *     -  From the grammar source file : grammar/scs.g
 *     -                            On : 2013-11-19 02:41:41
 *     -                for the parser : scsParserParser *
 * Editing it, at least manually, is not wise. 
 *
 * C language generator and runtime by Jim Idle, jimi|hereisanat|idle|dotgoeshere|ws.
 *
 *
*/
// [The "BSD licence"]
// Copyright (c) 2005-2009 Jim Idle, Temporal Wave LLC
// http://www.temporal-wave.com
// http://www.linkedin.com/in/jimidle
//
// All rights reserved.
//
// Redistribution and use in source and binary forms, with or without
// modification, are permitted provided that the following conditions
// are met:
// 1. Redistributions of source code must retain the above copyright
//    notice, this list of conditions and the following disclaimer.
// 2. Redistributions in binary form must reproduce the above copyright
//    notice, this list of conditions and the following disclaimer in the
//    documentation and/or other materials provided with the distribution.
// 3. The name of the author may not be used to endorse or promote products
//    derived from this software without specific prior written permission.
//
// THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS OR
// IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
// OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
// IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT,
// INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
// NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
// DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
// THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
// (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF
// THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

/* -----------------------------------------
 * Include the ANTLR3 generated header file.
 */
#include    "scsParser.h"



/* ----------------------------------------- */





/* MACROS that hide the C interface implementations from the
 * generated code, which makes it a little more understandable to the human eye.
 * I am very much against using C pre-processor macros for function calls and bits
 * of code as you cannot see what is happening when single stepping in debuggers
 * and so on. The exception (in my book at least) is for generated code, where you are
 * not maintaining it, but may wish to read and understand it. If you single step it, you know that input()
 * hides some indirect calls, but is always referring to the input stream. This is
 * probably more readable than ctx->input->istream->input(snarfle0->blarg) and allows me to rejig
 * the runtime interfaces without changing the generated code too often, without
 * confusing the reader of the generated output, who may not wish to know the gory
 * details of the interface inheritance.
 */
 
#define		CTX	ctx

/* Aids in accessing scopes for grammar programmers
 */
#undef	SCOPE_TYPE
#undef	SCOPE_STACK
#undef	SCOPE_TOP
#define	SCOPE_TYPE(scope)   pscsParser_##scope##_SCOPE
#define SCOPE_STACK(scope)  pscsParser_##scope##Stack
#define	SCOPE_TOP(scope)    ctx->pscsParser_##scope##Top
#define	SCOPE_SIZE(scope)		ctx->pscsParser_##scope##Stack_limit
#define SCOPE_INSTANCE(scope, i)	(ctx->SCOPE_STACK(scope)->get(ctx->SCOPE_STACK(scope),i))

/* Macros for accessing things in the parser
 */
 
#undef	    PARSER		    
#undef	    RECOGNIZER		    
#undef	    HAVEPARSEDRULE
#undef		MEMOIZE
#undef	    INPUT
#undef	    STRSTREAM
#undef	    HASEXCEPTION
#undef	    EXCEPTION
#undef	    MATCHT
#undef	    MATCHANYT
#undef	    FOLLOWSTACK
#undef	    FOLLOWPUSH
#undef	    FOLLOWPOP
#undef	    PRECOVER
#undef	    PREPORTERROR
#undef	    LA
#undef	    LT
#undef	    CONSTRUCTEX
#undef	    CONSUME
#undef	    MARK
#undef	    REWIND
#undef	    REWINDLAST
#undef	    PERRORRECOVERY
#undef	    HASFAILED
#undef	    FAILEDFLAG
#undef	    RECOVERFROMMISMATCHEDSET
#undef	    RECOVERFROMMISMATCHEDELEMENT
#undef		INDEX
#undef      ADAPTOR
#undef		SEEK
#undef	    RULEMEMO		    
#undef		DBG

#define	    PARSER							ctx->pParser  
#define	    RECOGNIZER						PARSER->rec
#define		PSRSTATE						RECOGNIZER->state
#define	    HAVEPARSEDRULE(r)				RECOGNIZER->alreadyParsedRule(RECOGNIZER, r)
#define		MEMOIZE(ri,si)					RECOGNIZER->memoize(RECOGNIZER, ri, si)
#define	    INPUT							PARSER->tstream
#define	    STRSTREAM						INPUT
#define		ISTREAM							INPUT->istream
#define		INDEX()							ISTREAM->index(INPUT->istream)
#define	    HASEXCEPTION()					(PSRSTATE->error == ANTLR3_TRUE)
#define	    EXCEPTION						PSRSTATE->exception
#define	    MATCHT(t, fs)					RECOGNIZER->match(RECOGNIZER, t, fs)
#define	    MATCHANYT()						RECOGNIZER->matchAny(RECOGNIZER)
#define	    FOLLOWSTACK					    PSRSTATE->following
#define	    FOLLOWPUSH(x)					FOLLOWSTACK->push(FOLLOWSTACK, ((void *)(&(x))), NULL)
#define	    FOLLOWPOP()						FOLLOWSTACK->pop(FOLLOWSTACK)
#define	    PRECOVER()						RECOGNIZER->recover(RECOGNIZER)
#define	    PREPORTERROR()					RECOGNIZER->reportError(RECOGNIZER)
#define	    LA(n)							INPUT->istream->_LA(ISTREAM, n)
#define	    LT(n)							INPUT->_LT(INPUT, n)
#define	    CONSTRUCTEX()					RECOGNIZER->exConstruct(RECOGNIZER)
#define	    CONSUME()						ISTREAM->consume(ISTREAM)
#define	    MARK()							ISTREAM->mark(ISTREAM)
#define	    REWIND(m)						ISTREAM->rewind(ISTREAM, m)
#define	    REWINDLAST()					ISTREAM->rewindLast(ISTREAM)
#define		SEEK(n)							ISTREAM->seek(ISTREAM, n)
#define	    PERRORRECOVERY					PSRSTATE->errorRecovery
#define	    FAILEDFLAG						PSRSTATE->failed
#define	    HASFAILED()						(FAILEDFLAG == ANTLR3_TRUE)
#define	    BACKTRACKING					PSRSTATE->backtracking
#define	    RECOVERFROMMISMATCHEDSET(s)		RECOGNIZER->recoverFromMismatchedSet(RECOGNIZER, s)
#define	    RECOVERFROMMISMATCHEDELEMENT(e)	RECOGNIZER->recoverFromMismatchedElement(RECOGNIZER, s)
#define     ADAPTOR                         ctx->adaptor
#define		RULEMEMO						PSRSTATE->ruleMemo
#define		DBG								RECOGNIZER->debugger

#define		TOKTEXT(tok, txt)				tok, (pANTLR3_UINT8)txt

/* The 4 tokens defined below may well clash with your own #defines or token types. If so
 * then for the present you must use different names for your defines as these are hard coded
 * in the code generator. It would be better not to use such names internally, and maybe
 * we can change this in a forthcoming release. I deliberately do not #undef these
 * here as this will at least give you a redefined error somewhere if they clash.
 */
#define	    UP	    ANTLR3_TOKEN_UP
#define	    DOWN    ANTLR3_TOKEN_DOWN
#define	    EOR	    ANTLR3_TOKEN_EOR
#define	    INVALID ANTLR3_TOKEN_INVALID


/* =============================================================================
 * Functions to create and destroy scopes. First come the rule scopes, followed
 * by the global declared scopes.
 */



/* ============================================================================= */

/* =============================================================================
 * Start of recognizer
 */



/** \brief Table of all token names in symbolic order, mainly used for
 *         error reporting.
 */
pANTLR3_UINT8   scsParserTokenNames[25+4]
     = {
        (pANTLR3_UINT8) "<invalid>",       /* String to print to indicate an invalid token */
        (pANTLR3_UINT8) "<EOR>",
        (pANTLR3_UINT8) "<DOWN>", 
        (pANTLR3_UINT8) "<UP>", 
        (pANTLR3_UINT8) "SEP_SENTENCE",
        (pANTLR3_UINT8) "SEP_SIMPLE",
        (pANTLR3_UINT8) "SEP_LPAR",
        (pANTLR3_UINT8) "SEP_RPAR",
        (pANTLR3_UINT8) "SEP_ATTR_CONST",
        (pANTLR3_UINT8) "SEP_ATTR_VAR",
        (pANTLR3_UINT8) "SEP_IDTF",
        (pANTLR3_UINT8) "SEP_LINT",
        (pANTLR3_UINT8) "SEP_RINT",
        (pANTLR3_UINT8) "SEP_LTUPLE",
        (pANTLR3_UINT8) "SEP_RTUPLE",
        (pANTLR3_UINT8) "SEP_LSET",
        (pANTLR3_UINT8) "SEP_RSET",
        (pANTLR3_UINT8) "SEP_LCONTENT",
        (pANTLR3_UINT8) "SEP_RCONTENT",
        (pANTLR3_UINT8) "SEP_ASSIGN",
        (pANTLR3_UINT8) "CONNECTORS",
        (pANTLR3_UINT8) "CONTENT",
        (pANTLR3_UINT8) "ID_SYSTEM",
        (pANTLR3_UINT8) "LINK",
        (pANTLR3_UINT8) "COMMENT",
        (pANTLR3_UINT8) "HEX_DIGIT",
        (pANTLR3_UINT8) "WS",
        (pANTLR3_UINT8) "OCTAL_ESC",
        (pANTLR3_UINT8) "UNICODE_ESC"
       };

        

// Forward declare the locally static matching functions we have generated.
//
static scsParser_syntax_return	syntax    (pscsParser ctx);
static scsParser_sentence_return	sentence    (pscsParser ctx);
static scsParser_sentence_level2_6_return	sentence_level2_6    (pscsParser ctx);
static scsParser_sentence_level1_return	sentence_level1    (pscsParser ctx);
static scsParser_sentence_internal_list_return	sentence_internal_list    (pscsParser ctx);
static scsParser_sentence_assignment_return	sentence_assignment    (pscsParser ctx);
static scsParser_sentence_internal_return	sentence_internal    (pscsParser ctx);
static scsParser_attrs_idtf_list_return	attrs_idtf_list    (pscsParser ctx);
static scsParser_idtf_attrs_return	idtf_attrs    (pscsParser ctx);
static scsParser_attrs_list_return	attrs_list    (pscsParser ctx);
static scsParser_idtf_internal_return	idtf_internal    (pscsParser ctx);
static scsParser_idtf_tuple_return	idtf_tuple    (pscsParser ctx);
static scsParser_idtf_set_return	idtf_set    (pscsParser ctx);
static scsParser_idtf_return	idtf    (pscsParser ctx);
static scsParser_idtf_level1_return	idtf_level1    (pscsParser ctx);
static scsParser_idtf_edge_return	idtf_edge    (pscsParser ctx);
static void	scsParserFree(pscsParser ctx);
/* For use in tree output where we are accumulating rule labels via label += ruleRef
 * we need a function that knows how to free a return scope when the list is destroyed. 
 * We cannot just use ANTLR3_FREE because in debug tracking mode, this is a macro.
 */
static	void ANTLR3_CDECL freeScope(void * scope)
{
    ANTLR3_FREE(scope);
}

/** \brief Name of the grammar file that generated this code
 */
static const char fileName[] = "grammar/scs.g";

/** \brief Return the name of the grammar file that generated this code.
 */
static const char * getGrammarFileName()
{
	return fileName;
}
/** \brief Create a new scsParser parser and return a context for it.
 *
 * \param[in] instream Pointer to an input stream interface.
 *
 * \return Pointer to new parser context upon success.
 */
ANTLR3_API pscsParser
scsParserNew   (pANTLR3_COMMON_TOKEN_STREAM instream)
{
	// See if we can create a new parser with the standard constructor
	//
	return scsParserNewSSD(instream, NULL);
}

/** \brief Create a new scsParser parser and return a context for it.
 *
 * \param[in] instream Pointer to an input stream interface.
 *
 * \return Pointer to new parser context upon success.
 */
ANTLR3_API pscsParser
scsParserNewSSD   (pANTLR3_COMMON_TOKEN_STREAM instream, pANTLR3_RECOGNIZER_SHARED_STATE state)
{
    pscsParser ctx;	    /* Context structure we will build and return   */
    
    ctx	= (pscsParser) ANTLR3_CALLOC(1, sizeof(scsParser));
    
    if	(ctx == NULL)
    {
		// Failed to allocate memory for parser context
		//
        return  NULL;
    }
    
    /* -------------------------------------------------------------------
     * Memory for basic structure is allocated, now to fill in
     * the base ANTLR3 structures. We initialize the function pointers
     * for the standard ANTLR3 parser function set, but upon return
     * from here, the programmer may set the pointers to provide custom
     * implementations of each function. 
     *
     * We don't use the macros defined in scsParser.h here, in order that you can get a sense
     * of what goes where.
     */

    /* Create a base parser/recognizer, using the supplied token stream
     */
    ctx->pParser	    = antlr3ParserNewStream(ANTLR3_SIZE_HINT, instream->tstream, state);
    /* Install the implementation of our scsParser interface
     */
    ctx->syntax	= syntax;
    ctx->sentence	= sentence;
    ctx->sentence_level2_6	= sentence_level2_6;
    ctx->sentence_level1	= sentence_level1;
    ctx->sentence_internal_list	= sentence_internal_list;
    ctx->sentence_assignment	= sentence_assignment;
    ctx->sentence_internal	= sentence_internal;
    ctx->attrs_idtf_list	= attrs_idtf_list;
    ctx->idtf_attrs	= idtf_attrs;
    ctx->attrs_list	= attrs_list;
    ctx->idtf_internal	= idtf_internal;
    ctx->idtf_tuple	= idtf_tuple;
    ctx->idtf_set	= idtf_set;
    ctx->idtf	= idtf;
    ctx->idtf_level1	= idtf_level1;
    ctx->idtf_edge	= idtf_edge;
    ctx->free			= scsParserFree;
    ctx->getGrammarFileName	= getGrammarFileName;
    
    /* Install the scope pushing methods.
     */
    ADAPTOR	= ANTLR3_TREE_ADAPTORNew(instream->tstream->tokenSource->strFactory);
    ctx->vectors	= antlr3VectorFactoryNew(0);
    

	
    /* Install the token table
     */
    PSRSTATE->tokenNames   = scsParserTokenNames;
    
    
    /* Return the newly built parser to the caller
     */
    return  ctx;
}

/** Free the parser resources
 */
 static void
 scsParserFree(pscsParser ctx)
 {
    /* Free any scope memory
     */
    
    ctx->vectors->close(ctx->vectors);
    /* We created the adaptor so we must free it
     */
    ADAPTOR->free(ADAPTOR);
	// Free this parser
	//
    ctx->pParser->free(ctx->pParser);
    ANTLR3_FREE(ctx);

    /* Everything is released, so we can return
     */
    return;
 }
 
/** Return token names used by this parser
 *
 * The returned pointer is used as an index into the token names table (using the token 
 * number as the index).
 * 
 * \return Pointer to first char * in the table.
 */
static pANTLR3_UINT8    *getTokenNames() 
{
        return scsParserTokenNames; 
}

    
/* Declare the bitsets
 */

/** Bitset defining follow set for error recovery in rule state: FOLLOW_sentence_in_syntax249  */
static	ANTLR3_BITWORD FOLLOW_sentence_in_syntax249_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000010) };
static  ANTLR3_BITSET_LIST FOLLOW_sentence_in_syntax249	= { FOLLOW_sentence_in_syntax249_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_SEP_SENTENCE_in_syntax251  */
static	ANTLR3_BITWORD FOLLOW_SEP_SENTENCE_in_syntax251_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000E8A040) };
static  ANTLR3_BITSET_LIST FOLLOW_SEP_SENTENCE_in_syntax251	= { FOLLOW_SEP_SENTENCE_in_syntax251_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_EOF_in_syntax256  */
static	ANTLR3_BITWORD FOLLOW_EOF_in_syntax256_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_EOF_in_syntax256	= { FOLLOW_EOF_in_syntax256_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_sentence_level1_in_sentence268  */
static	ANTLR3_BITWORD FOLLOW_sentence_level1_in_sentence268_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_sentence_level1_in_sentence268	= { FOLLOW_sentence_level1_in_sentence268_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_sentence_level2_6_in_sentence273  */
static	ANTLR3_BITWORD FOLLOW_sentence_level2_6_in_sentence273_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_sentence_level2_6_in_sentence273	= { FOLLOW_sentence_level2_6_in_sentence273_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_sentence_assignment_in_sentence278  */
static	ANTLR3_BITWORD FOLLOW_sentence_assignment_in_sentence278_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_sentence_assignment_in_sentence278	= { FOLLOW_sentence_assignment_in_sentence278_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_idtf_in_sentence_level2_6294  */
static	ANTLR3_BITWORD FOLLOW_idtf_in_sentence_level2_6294_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000100000) };
static  ANTLR3_BITSET_LIST FOLLOW_idtf_in_sentence_level2_6294	= { FOLLOW_idtf_in_sentence_level2_6294_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_CONNECTORS_in_sentence_level2_6296  */
static	ANTLR3_BITWORD FOLLOW_CONNECTORS_in_sentence_level2_6296_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000E0A840) };
static  ANTLR3_BITSET_LIST FOLLOW_CONNECTORS_in_sentence_level2_6296	= { FOLLOW_CONNECTORS_in_sentence_level2_6296_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_attrs_idtf_list_in_sentence_level2_6298  */
static	ANTLR3_BITWORD FOLLOW_attrs_idtf_list_in_sentence_level2_6298_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_attrs_idtf_list_in_sentence_level2_6298	= { FOLLOW_attrs_idtf_list_in_sentence_level2_6298_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_idtf_level1_in_sentence_level1318  */
static	ANTLR3_BITWORD FOLLOW_idtf_level1_in_sentence_level1318_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000020) };
static  ANTLR3_BITSET_LIST FOLLOW_idtf_level1_in_sentence_level1318	= { FOLLOW_idtf_level1_in_sentence_level1318_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_SEP_SIMPLE_in_sentence_level1320  */
static	ANTLR3_BITWORD FOLLOW_SEP_SIMPLE_in_sentence_level1320_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000C00000) };
static  ANTLR3_BITSET_LIST FOLLOW_SEP_SIMPLE_in_sentence_level1320	= { FOLLOW_SEP_SIMPLE_in_sentence_level1320_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_idtf_level1_in_sentence_level1322  */
static	ANTLR3_BITWORD FOLLOW_idtf_level1_in_sentence_level1322_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000020) };
static  ANTLR3_BITSET_LIST FOLLOW_idtf_level1_in_sentence_level1322	= { FOLLOW_idtf_level1_in_sentence_level1322_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_SEP_SIMPLE_in_sentence_level1324  */
static	ANTLR3_BITWORD FOLLOW_SEP_SIMPLE_in_sentence_level1324_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000C00000) };
static  ANTLR3_BITSET_LIST FOLLOW_SEP_SIMPLE_in_sentence_level1324	= { FOLLOW_SEP_SIMPLE_in_sentence_level1324_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_idtf_level1_in_sentence_level1326  */
static	ANTLR3_BITWORD FOLLOW_idtf_level1_in_sentence_level1326_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_idtf_level1_in_sentence_level1326	= { FOLLOW_idtf_level1_in_sentence_level1326_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_SEP_LINT_in_sentence_internal_list349  */
static	ANTLR3_BITWORD FOLLOW_SEP_LINT_in_sentence_internal_list349_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000101000) };
static  ANTLR3_BITSET_LIST FOLLOW_SEP_LINT_in_sentence_internal_list349	= { FOLLOW_SEP_LINT_in_sentence_internal_list349_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_sentence_internal_in_sentence_internal_list353  */
static	ANTLR3_BITWORD FOLLOW_sentence_internal_in_sentence_internal_list353_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000010) };
static  ANTLR3_BITSET_LIST FOLLOW_sentence_internal_in_sentence_internal_list353	= { FOLLOW_sentence_internal_in_sentence_internal_list353_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_SEP_SENTENCE_in_sentence_internal_list355  */
static	ANTLR3_BITWORD FOLLOW_SEP_SENTENCE_in_sentence_internal_list355_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000101000) };
static  ANTLR3_BITSET_LIST FOLLOW_SEP_SENTENCE_in_sentence_internal_list355	= { FOLLOW_SEP_SENTENCE_in_sentence_internal_list355_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_SEP_RINT_in_sentence_internal_list359  */
static	ANTLR3_BITWORD FOLLOW_SEP_RINT_in_sentence_internal_list359_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_SEP_RINT_in_sentence_internal_list359	= { FOLLOW_SEP_RINT_in_sentence_internal_list359_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_idtf_in_sentence_assignment372  */
static	ANTLR3_BITWORD FOLLOW_idtf_in_sentence_assignment372_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000080000) };
static  ANTLR3_BITSET_LIST FOLLOW_idtf_in_sentence_assignment372	= { FOLLOW_idtf_in_sentence_assignment372_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_SEP_ASSIGN_in_sentence_assignment374  */
static	ANTLR3_BITWORD FOLLOW_SEP_ASSIGN_in_sentence_assignment374_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000E0A040) };
static  ANTLR3_BITSET_LIST FOLLOW_SEP_ASSIGN_in_sentence_assignment374	= { FOLLOW_SEP_ASSIGN_in_sentence_assignment374_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_idtf_in_sentence_assignment376  */
static	ANTLR3_BITWORD FOLLOW_idtf_in_sentence_assignment376_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_idtf_in_sentence_assignment376	= { FOLLOW_idtf_in_sentence_assignment376_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_CONNECTORS_in_sentence_internal397  */
static	ANTLR3_BITWORD FOLLOW_CONNECTORS_in_sentence_internal397_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000E0A840) };
static  ANTLR3_BITSET_LIST FOLLOW_CONNECTORS_in_sentence_internal397	= { FOLLOW_CONNECTORS_in_sentence_internal397_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_attrs_idtf_list_in_sentence_internal399  */
static	ANTLR3_BITWORD FOLLOW_attrs_idtf_list_in_sentence_internal399_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_attrs_idtf_list_in_sentence_internal399	= { FOLLOW_attrs_idtf_list_in_sentence_internal399_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_idtf_attrs_in_attrs_idtf_list411  */
static	ANTLR3_BITWORD FOLLOW_idtf_attrs_in_attrs_idtf_list411_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000402) };
static  ANTLR3_BITSET_LIST FOLLOW_idtf_attrs_in_attrs_idtf_list411	= { FOLLOW_idtf_attrs_in_attrs_idtf_list411_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_SEP_IDTF_in_attrs_idtf_list415  */
static	ANTLR3_BITWORD FOLLOW_SEP_IDTF_in_attrs_idtf_list415_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000E0A840) };
static  ANTLR3_BITSET_LIST FOLLOW_SEP_IDTF_in_attrs_idtf_list415	= { FOLLOW_SEP_IDTF_in_attrs_idtf_list415_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_idtf_attrs_in_attrs_idtf_list417  */
static	ANTLR3_BITWORD FOLLOW_idtf_attrs_in_attrs_idtf_list417_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000402) };
static  ANTLR3_BITSET_LIST FOLLOW_idtf_attrs_in_attrs_idtf_list417	= { FOLLOW_idtf_attrs_in_attrs_idtf_list417_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_attrs_list_in_idtf_attrs431  */
static	ANTLR3_BITWORD FOLLOW_attrs_list_in_idtf_attrs431_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000E0A840) };
static  ANTLR3_BITSET_LIST FOLLOW_attrs_list_in_idtf_attrs431	= { FOLLOW_attrs_list_in_idtf_attrs431_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_idtf_internal_in_idtf_attrs433  */
static	ANTLR3_BITWORD FOLLOW_idtf_internal_in_idtf_attrs433_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_idtf_internal_in_idtf_attrs433	= { FOLLOW_idtf_internal_in_idtf_attrs433_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_idtf_level1_in_attrs_list446  */
static	ANTLR3_BITWORD FOLLOW_idtf_level1_in_attrs_list446_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000300) };
static  ANTLR3_BITSET_LIST FOLLOW_idtf_level1_in_attrs_list446	= { FOLLOW_idtf_level1_in_attrs_list446_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_set_in_attrs_list448  */
static	ANTLR3_BITWORD FOLLOW_set_in_attrs_list448_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000C00002) };
static  ANTLR3_BITSET_LIST FOLLOW_set_in_attrs_list448	= { FOLLOW_set_in_attrs_list448_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_idtf_in_idtf_internal468  */
static	ANTLR3_BITWORD FOLLOW_idtf_in_idtf_internal468_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000802) };
static  ANTLR3_BITSET_LIST FOLLOW_idtf_in_idtf_internal468	= { FOLLOW_idtf_in_idtf_internal468_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_sentence_internal_list_in_idtf_internal470  */
static	ANTLR3_BITWORD FOLLOW_sentence_internal_list_in_idtf_internal470_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_sentence_internal_list_in_idtf_internal470	= { FOLLOW_sentence_internal_list_in_idtf_internal470_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_SEP_LTUPLE_in_idtf_tuple482  */
static	ANTLR3_BITWORD FOLLOW_SEP_LTUPLE_in_idtf_tuple482_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000E0A840) };
static  ANTLR3_BITSET_LIST FOLLOW_SEP_LTUPLE_in_idtf_tuple482	= { FOLLOW_SEP_LTUPLE_in_idtf_tuple482_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_attrs_idtf_list_in_idtf_tuple484  */
static	ANTLR3_BITWORD FOLLOW_attrs_idtf_list_in_idtf_tuple484_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000004000) };
static  ANTLR3_BITSET_LIST FOLLOW_attrs_idtf_list_in_idtf_tuple484	= { FOLLOW_attrs_idtf_list_in_idtf_tuple484_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_SEP_RTUPLE_in_idtf_tuple487  */
static	ANTLR3_BITWORD FOLLOW_SEP_RTUPLE_in_idtf_tuple487_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_SEP_RTUPLE_in_idtf_tuple487	= { FOLLOW_SEP_RTUPLE_in_idtf_tuple487_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_SEP_LSET_in_idtf_set500  */
static	ANTLR3_BITWORD FOLLOW_SEP_LSET_in_idtf_set500_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000E0A840) };
static  ANTLR3_BITSET_LIST FOLLOW_SEP_LSET_in_idtf_set500	= { FOLLOW_SEP_LSET_in_idtf_set500_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_attrs_idtf_list_in_idtf_set502  */
static	ANTLR3_BITWORD FOLLOW_attrs_idtf_list_in_idtf_set502_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000010000) };
static  ANTLR3_BITSET_LIST FOLLOW_attrs_idtf_list_in_idtf_set502	= { FOLLOW_attrs_idtf_list_in_idtf_set502_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_SEP_RSET_in_idtf_set504  */
static	ANTLR3_BITWORD FOLLOW_SEP_RSET_in_idtf_set504_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_SEP_RSET_in_idtf_set504	= { FOLLOW_SEP_RSET_in_idtf_set504_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_idtf_level1_in_idtf516  */
static	ANTLR3_BITWORD FOLLOW_idtf_level1_in_idtf516_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_idtf_level1_in_idtf516	= { FOLLOW_idtf_level1_in_idtf516_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_idtf_edge_in_idtf521  */
static	ANTLR3_BITWORD FOLLOW_idtf_edge_in_idtf521_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_idtf_edge_in_idtf521	= { FOLLOW_idtf_edge_in_idtf521_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_idtf_tuple_in_idtf526  */
static	ANTLR3_BITWORD FOLLOW_idtf_tuple_in_idtf526_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_idtf_tuple_in_idtf526	= { FOLLOW_idtf_tuple_in_idtf526_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_idtf_set_in_idtf531  */
static	ANTLR3_BITWORD FOLLOW_idtf_set_in_idtf531_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_idtf_set_in_idtf531	= { FOLLOW_idtf_set_in_idtf531_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_CONTENT_in_idtf536  */
static	ANTLR3_BITWORD FOLLOW_CONTENT_in_idtf536_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_CONTENT_in_idtf536	= { FOLLOW_CONTENT_in_idtf536_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_set_in_idtf_level10  */
static	ANTLR3_BITWORD FOLLOW_set_in_idtf_level10_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_set_in_idtf_level10	= { FOLLOW_set_in_idtf_level10_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_SEP_LPAR_in_idtf_edge565  */
static	ANTLR3_BITWORD FOLLOW_SEP_LPAR_in_idtf_edge565_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000F0A040) };
static  ANTLR3_BITSET_LIST FOLLOW_SEP_LPAR_in_idtf_edge565	= { FOLLOW_SEP_LPAR_in_idtf_edge565_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_idtf_in_idtf_edge567  */
static	ANTLR3_BITWORD FOLLOW_idtf_in_idtf_edge567_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000100000) };
static  ANTLR3_BITSET_LIST FOLLOW_idtf_in_idtf_edge567	= { FOLLOW_idtf_in_idtf_edge567_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_CONNECTORS_in_idtf_edge569  */
static	ANTLR3_BITWORD FOLLOW_CONNECTORS_in_idtf_edge569_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000E0A0C0) };
static  ANTLR3_BITSET_LIST FOLLOW_CONNECTORS_in_idtf_edge569	= { FOLLOW_CONNECTORS_in_idtf_edge569_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_idtf_in_idtf_edge571  */
static	ANTLR3_BITWORD FOLLOW_idtf_in_idtf_edge571_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000080) };
static  ANTLR3_BITSET_LIST FOLLOW_idtf_in_idtf_edge571	= { FOLLOW_idtf_in_idtf_edge571_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_SEP_RPAR_in_idtf_edge573  */
static	ANTLR3_BITWORD FOLLOW_SEP_RPAR_in_idtf_edge573_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_SEP_RPAR_in_idtf_edge573	= { FOLLOW_SEP_RPAR_in_idtf_edge573_bits, 1	};
     

 
 
/* ==============================================
 * Parsing rules
 */
/** 
 * $ANTLR start syntax
 * grammar/scs.g:52:1: syntax : ( sentence SEP_SENTENCE )* EOF ;
 */
static scsParser_syntax_return
syntax(pscsParser ctx)
{   
    scsParser_syntax_return retval;

    pANTLR3_BASE_TREE root_0;

    pANTLR3_COMMON_TOKEN    SEP_SENTENCE2;
    pANTLR3_COMMON_TOKEN    EOF3;
    scsParser_sentence_return sentence1;
    #undef	RETURN_TYPE_sentence1
    #define	RETURN_TYPE_sentence1 scsParser_sentence_return

    pANTLR3_BASE_TREE SEP_SENTENCE2_tree;
    pANTLR3_BASE_TREE EOF3_tree;

    /* Initialize rule variables
     */


    root_0 = NULL;

    SEP_SENTENCE2       = NULL;
    EOF3       = NULL;
    sentence1.tree = NULL;

    retval.start = LT(1); retval.stop = retval.start;

    SEP_SENTENCE2_tree   = NULL;
    EOF3_tree   = NULL;


    retval.tree  = NULL;
    {
        // grammar/scs.g:53:2: ( ( sentence SEP_SENTENCE )* EOF )
        // grammar/scs.g:53:4: ( sentence SEP_SENTENCE )* EOF
        {
            root_0 = (pANTLR3_BASE_TREE)(ADAPTOR->nilNode(ADAPTOR));


            // grammar/scs.g:53:4: ( sentence SEP_SENTENCE )*

            for (;;)
            {
                int alt1=2;
                switch ( LA(1) ) 
                {
                case SEP_SENTENCE:
                case SEP_LPAR:
                case SEP_LTUPLE:
                case SEP_LSET:
                case CONTENT:
                case ID_SYSTEM:
                case LINK:
                	{
                		alt1=1;
                	}
                    break;

                }

                switch (alt1) 
                {
            	case 1:
            	    // grammar/scs.g:53:5: sentence SEP_SENTENCE
            	    {
            	        FOLLOWPUSH(FOLLOW_sentence_in_syntax249);
            	        sentence1=sentence(ctx);

            	        FOLLOWPOP();
            	        if  (HASEXCEPTION())
            	        {
            	            goto rulesyntaxEx;
            	        }

            	        ADAPTOR->addChild(ADAPTOR, root_0, sentence1.tree);
            	        SEP_SENTENCE2 = (pANTLR3_COMMON_TOKEN) MATCHT(SEP_SENTENCE, &FOLLOW_SEP_SENTENCE_in_syntax251); 
            	        if  (HASEXCEPTION())
            	        {
            	            goto rulesyntaxEx;
            	        }


            	    }
            	    break;

            	default:
            	    goto loop1;	/* break out of the loop */
            	    break;
                }
            }
            loop1: ; /* Jump out to here if this rule does not match */

            EOF3 = (pANTLR3_COMMON_TOKEN) MATCHT(EOF, &FOLLOW_EOF_in_syntax256); 
            if  (HASEXCEPTION())
            {
                goto rulesyntaxEx;
            }

            EOF3_tree = (pANTLR3_BASE_TREE)(ADAPTOR->create(ADAPTOR, EOF3));
            ADAPTOR->addChild(ADAPTOR, root_0, EOF3_tree);


        }

    }
    

    // This is where rules clean up and exit
    //
    goto rulesyntaxEx; /* Prevent compiler warnings */
    rulesyntaxEx: ;
    retval.stop = LT(-1);

    	retval.stop = LT(-1);
    	retval.tree = (pANTLR3_BASE_TREE)(ADAPTOR->rulePostProcessing(ADAPTOR, root_0));
    	ADAPTOR->setTokenBoundaries(ADAPTOR, retval.tree, retval.start, retval.stop);





    return retval;
}
/* $ANTLR end syntax */

/** 
 * $ANTLR start sentence
 * grammar/scs.g:56:1: sentence : ( sentence_level1 | sentence_level2_6 | sentence_assignment );
 */
static scsParser_sentence_return
sentence(pscsParser ctx)
{   
    scsParser_sentence_return retval;

    pANTLR3_BASE_TREE root_0;

    scsParser_sentence_level1_return sentence_level14;
    #undef	RETURN_TYPE_sentence_level14
    #define	RETURN_TYPE_sentence_level14 scsParser_sentence_level1_return

    scsParser_sentence_level2_6_return sentence_level2_65;
    #undef	RETURN_TYPE_sentence_level2_65
    #define	RETURN_TYPE_sentence_level2_65 scsParser_sentence_level2_6_return

    scsParser_sentence_assignment_return sentence_assignment6;
    #undef	RETURN_TYPE_sentence_assignment6
    #define	RETURN_TYPE_sentence_assignment6 scsParser_sentence_assignment_return


    /* Initialize rule variables
     */


    root_0 = NULL;

    sentence_level14.tree = NULL;

    sentence_level2_65.tree = NULL;

    sentence_assignment6.tree = NULL;

    retval.start = LT(1); retval.stop = retval.start;



    retval.tree  = NULL;
    {
        {
            //  grammar/scs.g:57:2: ( sentence_level1 | sentence_level2_6 | sentence_assignment )
            
            ANTLR3_UINT32 alt2;

            alt2=3;

            switch ( LA(1) ) 
            {
            case ID_SYSTEM:
            case LINK:
            	{
            		switch ( LA(2) ) 
            		{
            		case SEP_ASSIGN:
            			{
            				alt2=3;
            			}
            		    break;
            		case SEP_SIMPLE:
            			{
            				alt2=1;
            			}
            		    break;
            		case CONNECTORS:
            			{
            				alt2=2;
            			}
            		    break;

            		default:
            		    CONSTRUCTEX();
            		    EXCEPTION->type         = ANTLR3_NO_VIABLE_ALT_EXCEPTION;
            		    EXCEPTION->message      = (void *)"";
            		    EXCEPTION->decisionNum  = 2;
            		    EXCEPTION->state        = 1;


            		    goto rulesentenceEx;
            		}

            	}
                break;
            case SEP_SENTENCE:
            	{
            		alt2=2;
            	}
                break;
            case SEP_LPAR:
            	{
            		switch ( LA(2) ) 
            		{
            		case ID_SYSTEM:
            		case LINK:
            			{
            				alt2=2;
            			}
            		    break;
            		case SEP_LPAR:
            			{
            				alt2=2;
            			}
            		    break;
            		case SEP_LTUPLE:
            			{
            				alt2=2;
            			}
            		    break;
            		case SEP_LSET:
            			{
            				alt2=2;
            			}
            		    break;
            		case CONTENT:
            			{
            				alt2=2;
            			}
            		    break;

            		default:
            		    CONSTRUCTEX();
            		    EXCEPTION->type         = ANTLR3_NO_VIABLE_ALT_EXCEPTION;
            		    EXCEPTION->message      = (void *)"";
            		    EXCEPTION->decisionNum  = 2;
            		    EXCEPTION->state        = 3;


            		    goto rulesentenceEx;
            		}

            	}
                break;
            case SEP_LTUPLE:
            	{
            		switch ( LA(2) ) 
            		{
            		case ID_SYSTEM:
            		case LINK:
            			{
            				alt2=2;
            			}
            		    break;
            		case SEP_LPAR:
            			{
            				alt2=2;
            			}
            		    break;
            		case SEP_LTUPLE:
            			{
            				alt2=2;
            			}
            		    break;
            		case SEP_LSET:
            			{
            				alt2=2;
            			}
            		    break;
            		case CONTENT:
            			{
            				alt2=2;
            			}
            		    break;

            		default:
            		    CONSTRUCTEX();
            		    EXCEPTION->type         = ANTLR3_NO_VIABLE_ALT_EXCEPTION;
            		    EXCEPTION->message      = (void *)"";
            		    EXCEPTION->decisionNum  = 2;
            		    EXCEPTION->state        = 4;


            		    goto rulesentenceEx;
            		}

            	}
                break;
            case SEP_LSET:
            	{
            		switch ( LA(2) ) 
            		{
            		case ID_SYSTEM:
            		case LINK:
            			{
            				alt2=2;
            			}
            		    break;
            		case SEP_LPAR:
            			{
            				alt2=2;
            			}
            		    break;
            		case SEP_LTUPLE:
            			{
            				alt2=2;
            			}
            		    break;
            		case SEP_LSET:
            			{
            				alt2=2;
            			}
            		    break;
            		case CONTENT:
            			{
            				alt2=2;
            			}
            		    break;

            		default:
            		    CONSTRUCTEX();
            		    EXCEPTION->type         = ANTLR3_NO_VIABLE_ALT_EXCEPTION;
            		    EXCEPTION->message      = (void *)"";
            		    EXCEPTION->decisionNum  = 2;
            		    EXCEPTION->state        = 5;


            		    goto rulesentenceEx;
            		}

            	}
                break;
            case CONTENT:
            	{
            		switch ( LA(2) ) 
            		{
            		case SEP_ASSIGN:
            			{
            				alt2=3;
            			}
            		    break;
            		case CONNECTORS:
            			{
            				alt2=2;
            			}
            		    break;

            		default:
            		    CONSTRUCTEX();
            		    EXCEPTION->type         = ANTLR3_NO_VIABLE_ALT_EXCEPTION;
            		    EXCEPTION->message      = (void *)"";
            		    EXCEPTION->decisionNum  = 2;
            		    EXCEPTION->state        = 6;


            		    goto rulesentenceEx;
            		}

            	}
                break;

            default:
                CONSTRUCTEX();
                EXCEPTION->type         = ANTLR3_NO_VIABLE_ALT_EXCEPTION;
                EXCEPTION->message      = (void *)"";
                EXCEPTION->decisionNum  = 2;
                EXCEPTION->state        = 0;


                goto rulesentenceEx;
            }

            switch (alt2) 
            {
        	case 1:
        	    // grammar/scs.g:57:4: sentence_level1
        	    {
        	        root_0 = (pANTLR3_BASE_TREE)(ADAPTOR->nilNode(ADAPTOR));

        	        FOLLOWPUSH(FOLLOW_sentence_level1_in_sentence268);
        	        sentence_level14=sentence_level1(ctx);

        	        FOLLOWPOP();
        	        if  (HASEXCEPTION())
        	        {
        	            goto rulesentenceEx;
        	        }

        	        ADAPTOR->addChild(ADAPTOR, root_0, sentence_level14.tree);

        	    }
        	    break;
        	case 2:
        	    // grammar/scs.g:58:4: sentence_level2_6
        	    {
        	        root_0 = (pANTLR3_BASE_TREE)(ADAPTOR->nilNode(ADAPTOR));

        	        FOLLOWPUSH(FOLLOW_sentence_level2_6_in_sentence273);
        	        sentence_level2_65=sentence_level2_6(ctx);

        	        FOLLOWPOP();
        	        if  (HASEXCEPTION())
        	        {
        	            goto rulesentenceEx;
        	        }

        	        ADAPTOR->addChild(ADAPTOR, root_0, sentence_level2_65.tree);

        	    }
        	    break;
        	case 3:
        	    // grammar/scs.g:59:4: sentence_assignment
        	    {
        	        root_0 = (pANTLR3_BASE_TREE)(ADAPTOR->nilNode(ADAPTOR));

        	        FOLLOWPUSH(FOLLOW_sentence_assignment_in_sentence278);
        	        sentence_assignment6=sentence_assignment(ctx);

        	        FOLLOWPOP();
        	        if  (HASEXCEPTION())
        	        {
        	            goto rulesentenceEx;
        	        }

        	        ADAPTOR->addChild(ADAPTOR, root_0, sentence_assignment6.tree);

        	    }
        	    break;

            }
        }
    }
    

    // This is where rules clean up and exit
    //
    goto rulesentenceEx; /* Prevent compiler warnings */
    rulesentenceEx: ;
    retval.stop = LT(-1);

    	retval.stop = LT(-1);
    	retval.tree = (pANTLR3_BASE_TREE)(ADAPTOR->rulePostProcessing(ADAPTOR, root_0));
    	ADAPTOR->setTokenBoundaries(ADAPTOR, retval.tree, retval.start, retval.stop);





    return retval;
}
/* $ANTLR end sentence */

/** 
 * $ANTLR start sentence_level2_6
 * grammar/scs.g:63:1: sentence_level2_6 : ( | idtf CONNECTORS attrs_idtf_list -> ^( CONNECTORS idtf attrs_idtf_list ) );
 */
static scsParser_sentence_level2_6_return
sentence_level2_6(pscsParser ctx)
{   
    scsParser_sentence_level2_6_return retval;

    pANTLR3_BASE_TREE root_0;

    pANTLR3_COMMON_TOKEN    CONNECTORS8;
    scsParser_idtf_return idtf7;
    #undef	RETURN_TYPE_idtf7
    #define	RETURN_TYPE_idtf7 scsParser_idtf_return

    scsParser_attrs_idtf_list_return attrs_idtf_list9;
    #undef	RETURN_TYPE_attrs_idtf_list9
    #define	RETURN_TYPE_attrs_idtf_list9 scsParser_attrs_idtf_list_return

    pANTLR3_BASE_TREE CONNECTORS8_tree;
    pANTLR3_REWRITE_RULE_TOKEN_STREAM stream_CONNECTORS;
    pANTLR3_REWRITE_RULE_SUBTREE_STREAM stream_idtf;
    pANTLR3_REWRITE_RULE_SUBTREE_STREAM stream_attrs_idtf_list;
    /* Initialize rule variables
     */


    root_0 = NULL;

    CONNECTORS8       = NULL;
    idtf7.tree = NULL;

    attrs_idtf_list9.tree = NULL;

    retval.start = LT(1); retval.stop = retval.start;

    CONNECTORS8_tree   = NULL;

    stream_CONNECTORS   = NULL;
    #define CREATE_stream_CONNECTORS  if (stream_CONNECTORS == NULL) {stream_CONNECTORS = antlr3RewriteRuleTOKENStreamNewAE(ADAPTOR, RECOGNIZER, (pANTLR3_UINT8)"token CONNECTORS"); } 
    stream_idtf   = NULL;
    #define CREATE_stream_idtf  if (stream_idtf == NULL) {stream_idtf = antlr3RewriteRuleSubtreeStreamNewAE(ADAPTOR, RECOGNIZER, (pANTLR3_UINT8)"rule idtf"); }
    stream_attrs_idtf_list   = NULL;
    #define CREATE_stream_attrs_idtf_list  if (stream_attrs_idtf_list == NULL) {stream_attrs_idtf_list = antlr3RewriteRuleSubtreeStreamNewAE(ADAPTOR, RECOGNIZER, (pANTLR3_UINT8)"rule attrs_idtf_list"); }

    retval.tree  = NULL;
    {
        {
            //  grammar/scs.g:64:2: ( | idtf CONNECTORS attrs_idtf_list -> ^( CONNECTORS idtf attrs_idtf_list ) )
            
            ANTLR3_UINT32 alt3;

            alt3=2;

            switch ( LA(1) ) 
            {
            case SEP_SENTENCE:
            	{
            		alt3=1;
            	}
                break;
            case SEP_LPAR:
            case SEP_LTUPLE:
            case SEP_LSET:
            case CONTENT:
            case ID_SYSTEM:
            case LINK:
            	{
            		alt3=2;
            	}
                break;

            default:
                CONSTRUCTEX();
                EXCEPTION->type         = ANTLR3_NO_VIABLE_ALT_EXCEPTION;
                EXCEPTION->message      = (void *)"";
                EXCEPTION->decisionNum  = 3;
                EXCEPTION->state        = 0;


                goto rulesentence_level2_6Ex;
            }

            switch (alt3) 
            {
        	case 1:
        	    // grammar/scs.g:65:2: 
        	    {
        	        root_0 = (pANTLR3_BASE_TREE)(ADAPTOR->nilNode(ADAPTOR));

        	    }
        	    break;
        	case 2:
        	    // grammar/scs.g:65:4: idtf CONNECTORS attrs_idtf_list
        	    {
        	        FOLLOWPUSH(FOLLOW_idtf_in_sentence_level2_6294);
        	        idtf7=idtf(ctx);

        	        FOLLOWPOP();
        	        if  (HASEXCEPTION())
        	        {
        	            goto rulesentence_level2_6Ex;
        	        }

        	        CREATE_stream_idtf; stream_idtf->add(stream_idtf, idtf7.tree, NULL);
        	        CONNECTORS8 = (pANTLR3_COMMON_TOKEN) MATCHT(CONNECTORS, &FOLLOW_CONNECTORS_in_sentence_level2_6296); 
        	        if  (HASEXCEPTION())
        	        {
        	            goto rulesentence_level2_6Ex;
        	        }
        	         
        	        CREATE_stream_CONNECTORS; stream_CONNECTORS->add(stream_CONNECTORS, CONNECTORS8, NULL);

        	        FOLLOWPUSH(FOLLOW_attrs_idtf_list_in_sentence_level2_6298);
        	        attrs_idtf_list9=attrs_idtf_list(ctx);

        	        FOLLOWPOP();
        	        if  (HASEXCEPTION())
        	        {
        	            goto rulesentence_level2_6Ex;
        	        }

        	        CREATE_stream_attrs_idtf_list; stream_attrs_idtf_list->add(stream_attrs_idtf_list, attrs_idtf_list9.tree, NULL);

        	         
        	        /* AST REWRITE
        	         * elements          : CONNECTORS, idtf, attrs_idtf_list
        	         * token labels      : 
        	         * rule labels       : retval
        	         * token list labels : 
        	         * rule list labels  : 
        	         */
        	        {
        	        	pANTLR3_REWRITE_RULE_SUBTREE_STREAM stream_retval;

        	        	stream_retval=antlr3RewriteRuleSubtreeStreamNewAEE(ADAPTOR,  RECOGNIZER, (pANTLR3_UINT8)"token retval", retval.tree != NULL ? retval.tree : NULL);

        	        	root_0			    = (pANTLR3_BASE_TREE)(ADAPTOR->nilNode(ADAPTOR));
        	        	retval.tree    = root_0;
        	        	// 65:36: -> ^( CONNECTORS idtf attrs_idtf_list )
        	        	{
        	        	    // grammar/scs.g:65:39: ^( CONNECTORS idtf attrs_idtf_list )
        	        	    {
        	        	        pANTLR3_BASE_TREE root_1 = (pANTLR3_BASE_TREE)(ADAPTOR->nilNode(ADAPTOR));
        	        	        root_1 = (pANTLR3_BASE_TREE)(ADAPTOR->becomeRoot(ADAPTOR, stream_CONNECTORS == NULL ? NULL : stream_CONNECTORS->nextNode(stream_CONNECTORS), root_1));

        	        	        ADAPTOR->addChild(ADAPTOR, root_1, stream_idtf == NULL ? NULL : stream_idtf->nextTree(stream_idtf));
        	        	        ADAPTOR->addChild(ADAPTOR, root_1, stream_attrs_idtf_list == NULL ? NULL : stream_attrs_idtf_list->nextTree(stream_attrs_idtf_list));

        	        	        ADAPTOR->addChild(ADAPTOR, root_0, root_1);
        	        	    }

        	        	}

        	        	retval.tree = root_0; // set result root
        	        	if (stream_retval != NULL) stream_retval->free(stream_retval);


        	        }
        	    }
        	    break;

            }
        }
    }
    

    // This is where rules clean up and exit
    //
    goto rulesentence_level2_6Ex; /* Prevent compiler warnings */
    rulesentence_level2_6Ex: ;
    retval.stop = LT(-1);

    	retval.stop = LT(-1);
    	retval.tree = (pANTLR3_BASE_TREE)(ADAPTOR->rulePostProcessing(ADAPTOR, root_0));
    	ADAPTOR->setTokenBoundaries(ADAPTOR, retval.tree, retval.start, retval.stop);
        if (stream_CONNECTORS != NULL) stream_CONNECTORS->free(stream_CONNECTORS);
        if (stream_idtf != NULL) stream_idtf->free(stream_idtf);
        if (stream_attrs_idtf_list != NULL) stream_attrs_idtf_list->free(stream_attrs_idtf_list);





    return retval;
}
/* $ANTLR end sentence_level2_6 */

/** 
 * $ANTLR start sentence_level1
 * grammar/scs.g:67:1: sentence_level1 : idtf_level1 SEP_SIMPLE idtf_level1 SEP_SIMPLE idtf_level1 -> ^( SEP_SIMPLE ( idtf_level1 )+ ) ;
 */
static scsParser_sentence_level1_return
sentence_level1(pscsParser ctx)
{   
    scsParser_sentence_level1_return retval;

    pANTLR3_BASE_TREE root_0;

    pANTLR3_COMMON_TOKEN    SEP_SIMPLE11;
    pANTLR3_COMMON_TOKEN    SEP_SIMPLE13;
    scsParser_idtf_level1_return idtf_level110;
    #undef	RETURN_TYPE_idtf_level110
    #define	RETURN_TYPE_idtf_level110 scsParser_idtf_level1_return

    scsParser_idtf_level1_return idtf_level112;
    #undef	RETURN_TYPE_idtf_level112
    #define	RETURN_TYPE_idtf_level112 scsParser_idtf_level1_return

    scsParser_idtf_level1_return idtf_level114;
    #undef	RETURN_TYPE_idtf_level114
    #define	RETURN_TYPE_idtf_level114 scsParser_idtf_level1_return

    pANTLR3_BASE_TREE SEP_SIMPLE11_tree;
    pANTLR3_BASE_TREE SEP_SIMPLE13_tree;
    pANTLR3_REWRITE_RULE_TOKEN_STREAM stream_SEP_SIMPLE;
    pANTLR3_REWRITE_RULE_SUBTREE_STREAM stream_idtf_level1;
    /* Initialize rule variables
     */


    root_0 = NULL;

    SEP_SIMPLE11       = NULL;
    SEP_SIMPLE13       = NULL;
    idtf_level110.tree = NULL;

    idtf_level112.tree = NULL;

    idtf_level114.tree = NULL;

    retval.start = LT(1); retval.stop = retval.start;

    SEP_SIMPLE11_tree   = NULL;
    SEP_SIMPLE13_tree   = NULL;

    stream_SEP_SIMPLE   = NULL;
    #define CREATE_stream_SEP_SIMPLE  if (stream_SEP_SIMPLE == NULL) {stream_SEP_SIMPLE = antlr3RewriteRuleTOKENStreamNewAE(ADAPTOR, RECOGNIZER, (pANTLR3_UINT8)"token SEP_SIMPLE"); } 
    stream_idtf_level1   = NULL;
    #define CREATE_stream_idtf_level1  if (stream_idtf_level1 == NULL) {stream_idtf_level1 = antlr3RewriteRuleSubtreeStreamNewAE(ADAPTOR, RECOGNIZER, (pANTLR3_UINT8)"rule idtf_level1"); }

    retval.tree  = NULL;
    {
        // grammar/scs.g:68:2: ( idtf_level1 SEP_SIMPLE idtf_level1 SEP_SIMPLE idtf_level1 -> ^( SEP_SIMPLE ( idtf_level1 )+ ) )
        // grammar/scs.g:68:4: idtf_level1 SEP_SIMPLE idtf_level1 SEP_SIMPLE idtf_level1
        {
            FOLLOWPUSH(FOLLOW_idtf_level1_in_sentence_level1318);
            idtf_level110=idtf_level1(ctx);

            FOLLOWPOP();
            if  (HASEXCEPTION())
            {
                goto rulesentence_level1Ex;
            }

            CREATE_stream_idtf_level1; stream_idtf_level1->add(stream_idtf_level1, idtf_level110.tree, NULL);
            SEP_SIMPLE11 = (pANTLR3_COMMON_TOKEN) MATCHT(SEP_SIMPLE, &FOLLOW_SEP_SIMPLE_in_sentence_level1320); 
            if  (HASEXCEPTION())
            {
                goto rulesentence_level1Ex;
            }
             
            CREATE_stream_SEP_SIMPLE; stream_SEP_SIMPLE->add(stream_SEP_SIMPLE, SEP_SIMPLE11, NULL);

            FOLLOWPUSH(FOLLOW_idtf_level1_in_sentence_level1322);
            idtf_level112=idtf_level1(ctx);

            FOLLOWPOP();
            if  (HASEXCEPTION())
            {
                goto rulesentence_level1Ex;
            }

            CREATE_stream_idtf_level1; stream_idtf_level1->add(stream_idtf_level1, idtf_level112.tree, NULL);
            SEP_SIMPLE13 = (pANTLR3_COMMON_TOKEN) MATCHT(SEP_SIMPLE, &FOLLOW_SEP_SIMPLE_in_sentence_level1324); 
            if  (HASEXCEPTION())
            {
                goto rulesentence_level1Ex;
            }
             
            CREATE_stream_SEP_SIMPLE; stream_SEP_SIMPLE->add(stream_SEP_SIMPLE, SEP_SIMPLE13, NULL);

            FOLLOWPUSH(FOLLOW_idtf_level1_in_sentence_level1326);
            idtf_level114=idtf_level1(ctx);

            FOLLOWPOP();
            if  (HASEXCEPTION())
            {
                goto rulesentence_level1Ex;
            }

            CREATE_stream_idtf_level1; stream_idtf_level1->add(stream_idtf_level1, idtf_level114.tree, NULL);

             
            /* AST REWRITE
             * elements          : idtf_level1, SEP_SIMPLE
             * token labels      : 
             * rule labels       : retval
             * token list labels : 
             * rule list labels  : 
             */
            {
            	pANTLR3_REWRITE_RULE_SUBTREE_STREAM stream_retval;

            	stream_retval=antlr3RewriteRuleSubtreeStreamNewAEE(ADAPTOR,  RECOGNIZER, (pANTLR3_UINT8)"token retval", retval.tree != NULL ? retval.tree : NULL);

            	root_0			    = (pANTLR3_BASE_TREE)(ADAPTOR->nilNode(ADAPTOR));
            	retval.tree    = root_0;
            	// 68:62: -> ^( SEP_SIMPLE ( idtf_level1 )+ )
            	{
            	    // grammar/scs.g:68:65: ^( SEP_SIMPLE ( idtf_level1 )+ )
            	    {
            	        pANTLR3_BASE_TREE root_1 = (pANTLR3_BASE_TREE)(ADAPTOR->nilNode(ADAPTOR));
            	        root_1 = (pANTLR3_BASE_TREE)(ADAPTOR->becomeRoot(ADAPTOR, stream_SEP_SIMPLE == NULL ? NULL : stream_SEP_SIMPLE->nextNode(stream_SEP_SIMPLE), root_1));

            	        if ((stream_idtf_level1 == NULL || !stream_idtf_level1->hasNext(stream_idtf_level1))  )
            	        {
            	            CONSTRUCTEX();
            	            EXCEPTION->type         = ANTLR3_REWRITE_EARLY_EXCEPTION;
            	            EXCEPTION->name         = (void *)ANTLR3_REWRITE_EARLY_EXCEPTION_NAME;
            	        }
            	        else
            	        {
            	        	while ( (stream_idtf_level1->hasNext(stream_idtf_level1))  ) {
            	        		ADAPTOR->addChild(ADAPTOR, root_1, stream_idtf_level1 == NULL ? NULL : stream_idtf_level1->nextTree(stream_idtf_level1));

            	        	}
            	        	stream_idtf_level1->reset(stream_idtf_level1);

            	        }
            	        ADAPTOR->addChild(ADAPTOR, root_0, root_1);
            	    }

            	}

            	retval.tree = root_0; // set result root
            	if (stream_retval != NULL) stream_retval->free(stream_retval);


            }
        }

    }
    

    // This is where rules clean up and exit
    //
    goto rulesentence_level1Ex; /* Prevent compiler warnings */
    rulesentence_level1Ex: ;
    retval.stop = LT(-1);

    	retval.stop = LT(-1);
    	retval.tree = (pANTLR3_BASE_TREE)(ADAPTOR->rulePostProcessing(ADAPTOR, root_0));
    	ADAPTOR->setTokenBoundaries(ADAPTOR, retval.tree, retval.start, retval.stop);
        if (stream_SEP_SIMPLE != NULL) stream_SEP_SIMPLE->free(stream_SEP_SIMPLE);
        if (stream_idtf_level1 != NULL) stream_idtf_level1->free(stream_idtf_level1);





    return retval;
}
/* $ANTLR end sentence_level1 */

/** 
 * $ANTLR start sentence_internal_list
 * grammar/scs.g:72:1: sentence_internal_list : SEP_LINT ( sentence_internal SEP_SENTENCE )* SEP_RINT ;
 */
static scsParser_sentence_internal_list_return
sentence_internal_list(pscsParser ctx)
{   
    scsParser_sentence_internal_list_return retval;

    pANTLR3_BASE_TREE root_0;

    pANTLR3_COMMON_TOKEN    SEP_LINT15;
    pANTLR3_COMMON_TOKEN    SEP_SENTENCE17;
    pANTLR3_COMMON_TOKEN    SEP_RINT18;
    scsParser_sentence_internal_return sentence_internal16;
    #undef	RETURN_TYPE_sentence_internal16
    #define	RETURN_TYPE_sentence_internal16 scsParser_sentence_internal_return

    pANTLR3_BASE_TREE SEP_LINT15_tree;
    pANTLR3_BASE_TREE SEP_SENTENCE17_tree;
    pANTLR3_BASE_TREE SEP_RINT18_tree;

    /* Initialize rule variables
     */


    root_0 = NULL;

    SEP_LINT15       = NULL;
    SEP_SENTENCE17       = NULL;
    SEP_RINT18       = NULL;
    sentence_internal16.tree = NULL;

    retval.start = LT(1); retval.stop = retval.start;

    SEP_LINT15_tree   = NULL;
    SEP_SENTENCE17_tree   = NULL;
    SEP_RINT18_tree   = NULL;


    retval.tree  = NULL;
    {
        // grammar/scs.g:73:2: ( SEP_LINT ( sentence_internal SEP_SENTENCE )* SEP_RINT )
        // grammar/scs.g:73:4: SEP_LINT ( sentence_internal SEP_SENTENCE )* SEP_RINT
        {
            root_0 = (pANTLR3_BASE_TREE)(ADAPTOR->nilNode(ADAPTOR));

            SEP_LINT15 = (pANTLR3_COMMON_TOKEN) MATCHT(SEP_LINT, &FOLLOW_SEP_LINT_in_sentence_internal_list349); 
            if  (HASEXCEPTION())
            {
                goto rulesentence_internal_listEx;
            }

            SEP_LINT15_tree = (pANTLR3_BASE_TREE)(ADAPTOR->create(ADAPTOR, SEP_LINT15));
            ADAPTOR->addChild(ADAPTOR, root_0, SEP_LINT15_tree);


            // grammar/scs.g:73:14: ( sentence_internal SEP_SENTENCE )*

            for (;;)
            {
                int alt4=2;
                switch ( LA(1) ) 
                {
                case CONNECTORS:
                	{
                		alt4=1;
                	}
                    break;

                }

                switch (alt4) 
                {
            	case 1:
            	    // grammar/scs.g:73:15: sentence_internal SEP_SENTENCE
            	    {
            	        FOLLOWPUSH(FOLLOW_sentence_internal_in_sentence_internal_list353);
            	        sentence_internal16=sentence_internal(ctx);

            	        FOLLOWPOP();
            	        if  (HASEXCEPTION())
            	        {
            	            goto rulesentence_internal_listEx;
            	        }

            	        ADAPTOR->addChild(ADAPTOR, root_0, sentence_internal16.tree);
            	        SEP_SENTENCE17 = (pANTLR3_COMMON_TOKEN) MATCHT(SEP_SENTENCE, &FOLLOW_SEP_SENTENCE_in_sentence_internal_list355); 
            	        if  (HASEXCEPTION())
            	        {
            	            goto rulesentence_internal_listEx;
            	        }

            	        SEP_SENTENCE17_tree = (pANTLR3_BASE_TREE)(ADAPTOR->create(ADAPTOR, SEP_SENTENCE17));
            	        ADAPTOR->addChild(ADAPTOR, root_0, SEP_SENTENCE17_tree);


            	    }
            	    break;

            	default:
            	    goto loop4;	/* break out of the loop */
            	    break;
                }
            }
            loop4: ; /* Jump out to here if this rule does not match */

            SEP_RINT18 = (pANTLR3_COMMON_TOKEN) MATCHT(SEP_RINT, &FOLLOW_SEP_RINT_in_sentence_internal_list359); 
            if  (HASEXCEPTION())
            {
                goto rulesentence_internal_listEx;
            }


        }

    }
    

    // This is where rules clean up and exit
    //
    goto rulesentence_internal_listEx; /* Prevent compiler warnings */
    rulesentence_internal_listEx: ;
    retval.stop = LT(-1);

    	retval.stop = LT(-1);
    	retval.tree = (pANTLR3_BASE_TREE)(ADAPTOR->rulePostProcessing(ADAPTOR, root_0));
    	ADAPTOR->setTokenBoundaries(ADAPTOR, retval.tree, retval.start, retval.stop);





    return retval;
}
/* $ANTLR end sentence_internal_list */

/** 
 * $ANTLR start sentence_assignment
 * grammar/scs.g:76:1: sentence_assignment : idtf SEP_ASSIGN idtf -> ^( SEP_ASSIGN ( idtf )+ ) ;
 */
static scsParser_sentence_assignment_return
sentence_assignment(pscsParser ctx)
{   
    scsParser_sentence_assignment_return retval;

    pANTLR3_BASE_TREE root_0;

    pANTLR3_COMMON_TOKEN    SEP_ASSIGN20;
    scsParser_idtf_return idtf19;
    #undef	RETURN_TYPE_idtf19
    #define	RETURN_TYPE_idtf19 scsParser_idtf_return

    scsParser_idtf_return idtf21;
    #undef	RETURN_TYPE_idtf21
    #define	RETURN_TYPE_idtf21 scsParser_idtf_return

    pANTLR3_BASE_TREE SEP_ASSIGN20_tree;
    pANTLR3_REWRITE_RULE_TOKEN_STREAM stream_SEP_ASSIGN;
    pANTLR3_REWRITE_RULE_SUBTREE_STREAM stream_idtf;
    /* Initialize rule variables
     */


    root_0 = NULL;

    SEP_ASSIGN20       = NULL;
    idtf19.tree = NULL;

    idtf21.tree = NULL;

    retval.start = LT(1); retval.stop = retval.start;

    SEP_ASSIGN20_tree   = NULL;

    stream_SEP_ASSIGN   = NULL;
    #define CREATE_stream_SEP_ASSIGN  if (stream_SEP_ASSIGN == NULL) {stream_SEP_ASSIGN = antlr3RewriteRuleTOKENStreamNewAE(ADAPTOR, RECOGNIZER, (pANTLR3_UINT8)"token SEP_ASSIGN"); } 
    stream_idtf   = NULL;
    #define CREATE_stream_idtf  if (stream_idtf == NULL) {stream_idtf = antlr3RewriteRuleSubtreeStreamNewAE(ADAPTOR, RECOGNIZER, (pANTLR3_UINT8)"rule idtf"); }

    retval.tree  = NULL;
    {
        // grammar/scs.g:77:2: ( idtf SEP_ASSIGN idtf -> ^( SEP_ASSIGN ( idtf )+ ) )
        // grammar/scs.g:77:4: idtf SEP_ASSIGN idtf
        {
            FOLLOWPUSH(FOLLOW_idtf_in_sentence_assignment372);
            idtf19=idtf(ctx);

            FOLLOWPOP();
            if  (HASEXCEPTION())
            {
                goto rulesentence_assignmentEx;
            }

            CREATE_stream_idtf; stream_idtf->add(stream_idtf, idtf19.tree, NULL);
            SEP_ASSIGN20 = (pANTLR3_COMMON_TOKEN) MATCHT(SEP_ASSIGN, &FOLLOW_SEP_ASSIGN_in_sentence_assignment374); 
            if  (HASEXCEPTION())
            {
                goto rulesentence_assignmentEx;
            }
             
            CREATE_stream_SEP_ASSIGN; stream_SEP_ASSIGN->add(stream_SEP_ASSIGN, SEP_ASSIGN20, NULL);

            FOLLOWPUSH(FOLLOW_idtf_in_sentence_assignment376);
            idtf21=idtf(ctx);

            FOLLOWPOP();
            if  (HASEXCEPTION())
            {
                goto rulesentence_assignmentEx;
            }

            CREATE_stream_idtf; stream_idtf->add(stream_idtf, idtf21.tree, NULL);

             
            /* AST REWRITE
             * elements          : idtf, SEP_ASSIGN
             * token labels      : 
             * rule labels       : retval
             * token list labels : 
             * rule list labels  : 
             */
            {
            	pANTLR3_REWRITE_RULE_SUBTREE_STREAM stream_retval;

            	stream_retval=antlr3RewriteRuleSubtreeStreamNewAEE(ADAPTOR,  RECOGNIZER, (pANTLR3_UINT8)"token retval", retval.tree != NULL ? retval.tree : NULL);

            	root_0			    = (pANTLR3_BASE_TREE)(ADAPTOR->nilNode(ADAPTOR));
            	retval.tree    = root_0;
            	// 77:25: -> ^( SEP_ASSIGN ( idtf )+ )
            	{
            	    // grammar/scs.g:77:28: ^( SEP_ASSIGN ( idtf )+ )
            	    {
            	        pANTLR3_BASE_TREE root_1 = (pANTLR3_BASE_TREE)(ADAPTOR->nilNode(ADAPTOR));
            	        root_1 = (pANTLR3_BASE_TREE)(ADAPTOR->becomeRoot(ADAPTOR, stream_SEP_ASSIGN == NULL ? NULL : stream_SEP_ASSIGN->nextNode(stream_SEP_ASSIGN), root_1));

            	        if ((stream_idtf == NULL || !stream_idtf->hasNext(stream_idtf))  )
            	        {
            	            CONSTRUCTEX();
            	            EXCEPTION->type         = ANTLR3_REWRITE_EARLY_EXCEPTION;
            	            EXCEPTION->name         = (void *)ANTLR3_REWRITE_EARLY_EXCEPTION_NAME;
            	        }
            	        else
            	        {
            	        	while ( (stream_idtf->hasNext(stream_idtf))  ) {
            	        		ADAPTOR->addChild(ADAPTOR, root_1, stream_idtf == NULL ? NULL : stream_idtf->nextTree(stream_idtf));

            	        	}
            	        	stream_idtf->reset(stream_idtf);

            	        }
            	        ADAPTOR->addChild(ADAPTOR, root_0, root_1);
            	    }

            	}

            	retval.tree = root_0; // set result root
            	if (stream_retval != NULL) stream_retval->free(stream_retval);


            }
        }

    }
    

    // This is where rules clean up and exit
    //
    goto rulesentence_assignmentEx; /* Prevent compiler warnings */
    rulesentence_assignmentEx: ;
    retval.stop = LT(-1);

    	retval.stop = LT(-1);
    	retval.tree = (pANTLR3_BASE_TREE)(ADAPTOR->rulePostProcessing(ADAPTOR, root_0));
    	ADAPTOR->setTokenBoundaries(ADAPTOR, retval.tree, retval.start, retval.stop);
        if (stream_SEP_ASSIGN != NULL) stream_SEP_ASSIGN->free(stream_SEP_ASSIGN);
        if (stream_idtf != NULL) stream_idtf->free(stream_idtf);





    return retval;
}
/* $ANTLR end sentence_assignment */

/** 
 * $ANTLR start sentence_internal
 * grammar/scs.g:80:1: sentence_internal : CONNECTORS attrs_idtf_list ;
 */
static scsParser_sentence_internal_return
sentence_internal(pscsParser ctx)
{   
    scsParser_sentence_internal_return retval;

    pANTLR3_BASE_TREE root_0;

    pANTLR3_COMMON_TOKEN    CONNECTORS22;
    scsParser_attrs_idtf_list_return attrs_idtf_list23;
    #undef	RETURN_TYPE_attrs_idtf_list23
    #define	RETURN_TYPE_attrs_idtf_list23 scsParser_attrs_idtf_list_return

    pANTLR3_BASE_TREE CONNECTORS22_tree;

    /* Initialize rule variables
     */


    root_0 = NULL;

    CONNECTORS22       = NULL;
    attrs_idtf_list23.tree = NULL;

    retval.start = LT(1); retval.stop = retval.start;

    CONNECTORS22_tree   = NULL;


    retval.tree  = NULL;
    {
        // grammar/scs.g:81:2: ( CONNECTORS attrs_idtf_list )
        // grammar/scs.g:81:4: CONNECTORS attrs_idtf_list
        {
            root_0 = (pANTLR3_BASE_TREE)(ADAPTOR->nilNode(ADAPTOR));

            CONNECTORS22 = (pANTLR3_COMMON_TOKEN) MATCHT(CONNECTORS, &FOLLOW_CONNECTORS_in_sentence_internal397); 
            if  (HASEXCEPTION())
            {
                goto rulesentence_internalEx;
            }

            CONNECTORS22_tree = (pANTLR3_BASE_TREE)(ADAPTOR->create(ADAPTOR, CONNECTORS22));
            ADAPTOR->addChild(ADAPTOR, root_0, CONNECTORS22_tree);

            FOLLOWPUSH(FOLLOW_attrs_idtf_list_in_sentence_internal399);
            attrs_idtf_list23=attrs_idtf_list(ctx);

            FOLLOWPOP();
            if  (HASEXCEPTION())
            {
                goto rulesentence_internalEx;
            }

            ADAPTOR->addChild(ADAPTOR, root_0, attrs_idtf_list23.tree);

        }

    }
    

    // This is where rules clean up and exit
    //
    goto rulesentence_internalEx; /* Prevent compiler warnings */
    rulesentence_internalEx: ;
    retval.stop = LT(-1);

    	retval.stop = LT(-1);
    	retval.tree = (pANTLR3_BASE_TREE)(ADAPTOR->rulePostProcessing(ADAPTOR, root_0));
    	ADAPTOR->setTokenBoundaries(ADAPTOR, retval.tree, retval.start, retval.stop);





    return retval;
}
/* $ANTLR end sentence_internal */

/** 
 * $ANTLR start attrs_idtf_list
 * grammar/scs.g:84:1: attrs_idtf_list : idtf_attrs ( SEP_IDTF idtf_attrs )* ;
 */
static scsParser_attrs_idtf_list_return
attrs_idtf_list(pscsParser ctx)
{   
    scsParser_attrs_idtf_list_return retval;

    pANTLR3_BASE_TREE root_0;

    pANTLR3_COMMON_TOKEN    SEP_IDTF25;
    scsParser_idtf_attrs_return idtf_attrs24;
    #undef	RETURN_TYPE_idtf_attrs24
    #define	RETURN_TYPE_idtf_attrs24 scsParser_idtf_attrs_return

    scsParser_idtf_attrs_return idtf_attrs26;
    #undef	RETURN_TYPE_idtf_attrs26
    #define	RETURN_TYPE_idtf_attrs26 scsParser_idtf_attrs_return

    pANTLR3_BASE_TREE SEP_IDTF25_tree;

    /* Initialize rule variables
     */


    root_0 = NULL;

    SEP_IDTF25       = NULL;
    idtf_attrs24.tree = NULL;

    idtf_attrs26.tree = NULL;

    retval.start = LT(1); retval.stop = retval.start;

    SEP_IDTF25_tree   = NULL;


    retval.tree  = NULL;
    {
        // grammar/scs.g:85:2: ( idtf_attrs ( SEP_IDTF idtf_attrs )* )
        // grammar/scs.g:85:4: idtf_attrs ( SEP_IDTF idtf_attrs )*
        {
            root_0 = (pANTLR3_BASE_TREE)(ADAPTOR->nilNode(ADAPTOR));

            FOLLOWPUSH(FOLLOW_idtf_attrs_in_attrs_idtf_list411);
            idtf_attrs24=idtf_attrs(ctx);

            FOLLOWPOP();
            if  (HASEXCEPTION())
            {
                goto ruleattrs_idtf_listEx;
            }

            ADAPTOR->addChild(ADAPTOR, root_0, idtf_attrs24.tree);

            // grammar/scs.g:85:16: ( SEP_IDTF idtf_attrs )*

            for (;;)
            {
                int alt5=2;
                switch ( LA(1) ) 
                {
                case SEP_IDTF:
                	{
                		alt5=1;
                	}
                    break;

                }

                switch (alt5) 
                {
            	case 1:
            	    // grammar/scs.g:85:17: SEP_IDTF idtf_attrs
            	    {
            	        SEP_IDTF25 = (pANTLR3_COMMON_TOKEN) MATCHT(SEP_IDTF, &FOLLOW_SEP_IDTF_in_attrs_idtf_list415); 
            	        if  (HASEXCEPTION())
            	        {
            	            goto ruleattrs_idtf_listEx;
            	        }

            	        SEP_IDTF25_tree = (pANTLR3_BASE_TREE)(ADAPTOR->create(ADAPTOR, SEP_IDTF25));
            	        ADAPTOR->addChild(ADAPTOR, root_0, SEP_IDTF25_tree);

            	        FOLLOWPUSH(FOLLOW_idtf_attrs_in_attrs_idtf_list417);
            	        idtf_attrs26=idtf_attrs(ctx);

            	        FOLLOWPOP();
            	        if  (HASEXCEPTION())
            	        {
            	            goto ruleattrs_idtf_listEx;
            	        }

            	        ADAPTOR->addChild(ADAPTOR, root_0, idtf_attrs26.tree);

            	    }
            	    break;

            	default:
            	    goto loop5;	/* break out of the loop */
            	    break;
                }
            }
            loop5: ; /* Jump out to here if this rule does not match */


        }

    }
    

    // This is where rules clean up and exit
    //
    goto ruleattrs_idtf_listEx; /* Prevent compiler warnings */
    ruleattrs_idtf_listEx: ;
    retval.stop = LT(-1);

    	retval.stop = LT(-1);
    	retval.tree = (pANTLR3_BASE_TREE)(ADAPTOR->rulePostProcessing(ADAPTOR, root_0));
    	ADAPTOR->setTokenBoundaries(ADAPTOR, retval.tree, retval.start, retval.stop);





    return retval;
}
/* $ANTLR end attrs_idtf_list */

/** 
 * $ANTLR start idtf_attrs
 * grammar/scs.g:88:1: idtf_attrs : attrs_list idtf_internal ;
 */
static scsParser_idtf_attrs_return
idtf_attrs(pscsParser ctx)
{   
    scsParser_idtf_attrs_return retval;

    pANTLR3_BASE_TREE root_0;

    scsParser_attrs_list_return attrs_list27;
    #undef	RETURN_TYPE_attrs_list27
    #define	RETURN_TYPE_attrs_list27 scsParser_attrs_list_return

    scsParser_idtf_internal_return idtf_internal28;
    #undef	RETURN_TYPE_idtf_internal28
    #define	RETURN_TYPE_idtf_internal28 scsParser_idtf_internal_return


    /* Initialize rule variables
     */


    root_0 = NULL;

    attrs_list27.tree = NULL;

    idtf_internal28.tree = NULL;

    retval.start = LT(1); retval.stop = retval.start;



    retval.tree  = NULL;
    {
        // grammar/scs.g:89:2: ( attrs_list idtf_internal )
        // grammar/scs.g:89:4: attrs_list idtf_internal
        {
            root_0 = (pANTLR3_BASE_TREE)(ADAPTOR->nilNode(ADAPTOR));

            FOLLOWPUSH(FOLLOW_attrs_list_in_idtf_attrs431);
            attrs_list27=attrs_list(ctx);

            FOLLOWPOP();
            if  (HASEXCEPTION())
            {
                goto ruleidtf_attrsEx;
            }

            ADAPTOR->addChild(ADAPTOR, root_0, attrs_list27.tree);
            FOLLOWPUSH(FOLLOW_idtf_internal_in_idtf_attrs433);
            idtf_internal28=idtf_internal(ctx);

            FOLLOWPOP();
            if  (HASEXCEPTION())
            {
                goto ruleidtf_attrsEx;
            }

            ADAPTOR->addChild(ADAPTOR, root_0, idtf_internal28.tree);

        }

    }
    

    // This is where rules clean up and exit
    //
    goto ruleidtf_attrsEx; /* Prevent compiler warnings */
    ruleidtf_attrsEx: ;
    retval.stop = LT(-1);

    	retval.stop = LT(-1);
    	retval.tree = (pANTLR3_BASE_TREE)(ADAPTOR->rulePostProcessing(ADAPTOR, root_0));
    	ADAPTOR->setTokenBoundaries(ADAPTOR, retval.tree, retval.start, retval.stop);





    return retval;
}
/* $ANTLR end idtf_attrs */

/** 
 * $ANTLR start attrs_list
 * grammar/scs.g:92:1: attrs_list : ( idtf_level1 ( SEP_ATTR_VAR | SEP_ATTR_CONST ) )* ;
 */
static scsParser_attrs_list_return
attrs_list(pscsParser ctx)
{   
    scsParser_attrs_list_return retval;

    pANTLR3_BASE_TREE root_0;

    pANTLR3_COMMON_TOKEN    set30;
    scsParser_idtf_level1_return idtf_level129;
    #undef	RETURN_TYPE_idtf_level129
    #define	RETURN_TYPE_idtf_level129 scsParser_idtf_level1_return

    pANTLR3_BASE_TREE set30_tree;

    /* Initialize rule variables
     */


    root_0 = NULL;

    set30       = NULL;
    idtf_level129.tree = NULL;

    retval.start = LT(1); retval.stop = retval.start;

    set30_tree   = NULL;


    retval.tree  = NULL;
    {
        // grammar/scs.g:93:2: ( ( idtf_level1 ( SEP_ATTR_VAR | SEP_ATTR_CONST ) )* )
        // grammar/scs.g:93:4: ( idtf_level1 ( SEP_ATTR_VAR | SEP_ATTR_CONST ) )*
        {
            root_0 = (pANTLR3_BASE_TREE)(ADAPTOR->nilNode(ADAPTOR));


            // grammar/scs.g:93:4: ( idtf_level1 ( SEP_ATTR_VAR | SEP_ATTR_CONST ) )*

            for (;;)
            {
                int alt6=2;
                switch ( LA(1) ) 
                {
                case ID_SYSTEM:
                case LINK:
                	{
                		switch ( LA(2) ) 
                		{
                		case SEP_ATTR_CONST:
                		case SEP_ATTR_VAR:
                			{
                				alt6=1;
                			}
                		    break;

                		}

                	}
                    break;

                }

                switch (alt6) 
                {
            	case 1:
            	    // grammar/scs.g:93:5: idtf_level1 ( SEP_ATTR_VAR | SEP_ATTR_CONST )
            	    {
            	        FOLLOWPUSH(FOLLOW_idtf_level1_in_attrs_list446);
            	        idtf_level129=idtf_level1(ctx);

            	        FOLLOWPOP();
            	        if  (HASEXCEPTION())
            	        {
            	            goto ruleattrs_listEx;
            	        }

            	        ADAPTOR->addChild(ADAPTOR, root_0, idtf_level129.tree);
            	        set30=(pANTLR3_COMMON_TOKEN)LT(1);
            	        if ( ((LA(1) >= SEP_ATTR_CONST) && (LA(1) <= SEP_ATTR_VAR)) )
            	        {
            	            CONSUME();
            	            ADAPTOR->addChild(ADAPTOR, root_0, (pANTLR3_BASE_TREE)(ADAPTOR->create(ADAPTOR, set30)));
            	            PERRORRECOVERY=ANTLR3_FALSE;
            	        }
            	        else 
            	        {
            	            CONSTRUCTEX();
            	            EXCEPTION->type         = ANTLR3_MISMATCHED_SET_EXCEPTION;
            	            EXCEPTION->name         = (void *)ANTLR3_MISMATCHED_SET_NAME;
            	            EXCEPTION->expectingSet = &FOLLOW_set_in_attrs_list448;
            	            RECOVERFROMMISMATCHEDSET(&FOLLOW_set_in_attrs_list448);    goto ruleattrs_listEx;
            	        }


            	    }
            	    break;

            	default:
            	    goto loop6;	/* break out of the loop */
            	    break;
                }
            }
            loop6: ; /* Jump out to here if this rule does not match */


        }

    }
    

    // This is where rules clean up and exit
    //
    goto ruleattrs_listEx; /* Prevent compiler warnings */
    ruleattrs_listEx: ;
    retval.stop = LT(-1);

    	retval.stop = LT(-1);
    	retval.tree = (pANTLR3_BASE_TREE)(ADAPTOR->rulePostProcessing(ADAPTOR, root_0));
    	ADAPTOR->setTokenBoundaries(ADAPTOR, retval.tree, retval.start, retval.stop);





    return retval;
}
/* $ANTLR end attrs_list */

/** 
 * $ANTLR start idtf_internal
 * grammar/scs.g:96:1: idtf_internal : idtf ( sentence_internal_list )? ;
 */
static scsParser_idtf_internal_return
idtf_internal(pscsParser ctx)
{   
    scsParser_idtf_internal_return retval;

    pANTLR3_BASE_TREE root_0;

    scsParser_idtf_return idtf31;
    #undef	RETURN_TYPE_idtf31
    #define	RETURN_TYPE_idtf31 scsParser_idtf_return

    scsParser_sentence_internal_list_return sentence_internal_list32;
    #undef	RETURN_TYPE_sentence_internal_list32
    #define	RETURN_TYPE_sentence_internal_list32 scsParser_sentence_internal_list_return


    /* Initialize rule variables
     */


    root_0 = NULL;

    idtf31.tree = NULL;

    sentence_internal_list32.tree = NULL;

    retval.start = LT(1); retval.stop = retval.start;



    retval.tree  = NULL;
    {
        // grammar/scs.g:97:3: ( idtf ( sentence_internal_list )? )
        // grammar/scs.g:97:4: idtf ( sentence_internal_list )?
        {
            root_0 = (pANTLR3_BASE_TREE)(ADAPTOR->nilNode(ADAPTOR));

            FOLLOWPUSH(FOLLOW_idtf_in_idtf_internal468);
            idtf31=idtf(ctx);

            FOLLOWPOP();
            if  (HASEXCEPTION())
            {
                goto ruleidtf_internalEx;
            }

            ADAPTOR->addChild(ADAPTOR, root_0, idtf31.tree);

            // grammar/scs.g:97:9: ( sentence_internal_list )?
            {
                int alt7=2;
                switch ( LA(1) ) 
                {
                    case SEP_LINT:
                    	{
                    		alt7=1;
                    	}
                        break;
                }

                switch (alt7) 
                {
            	case 1:
            	    // grammar/scs.g:97:9: sentence_internal_list
            	    {
            	        FOLLOWPUSH(FOLLOW_sentence_internal_list_in_idtf_internal470);
            	        sentence_internal_list32=sentence_internal_list(ctx);

            	        FOLLOWPOP();
            	        if  (HASEXCEPTION())
            	        {
            	            goto ruleidtf_internalEx;
            	        }

            	        ADAPTOR->addChild(ADAPTOR, root_0, sentence_internal_list32.tree);

            	    }
            	    break;

                }
            }

        }

    }
    

    // This is where rules clean up and exit
    //
    goto ruleidtf_internalEx; /* Prevent compiler warnings */
    ruleidtf_internalEx: ;
    retval.stop = LT(-1);

    	retval.stop = LT(-1);
    	retval.tree = (pANTLR3_BASE_TREE)(ADAPTOR->rulePostProcessing(ADAPTOR, root_0));
    	ADAPTOR->setTokenBoundaries(ADAPTOR, retval.tree, retval.start, retval.stop);





    return retval;
}
/* $ANTLR end idtf_internal */

/** 
 * $ANTLR start idtf_tuple
 * grammar/scs.g:100:1: idtf_tuple : SEP_LTUPLE attrs_idtf_list SEP_RTUPLE ;
 */
static scsParser_idtf_tuple_return
idtf_tuple(pscsParser ctx)
{   
    scsParser_idtf_tuple_return retval;

    pANTLR3_BASE_TREE root_0;

    pANTLR3_COMMON_TOKEN    SEP_LTUPLE33;
    pANTLR3_COMMON_TOKEN    SEP_RTUPLE35;
    scsParser_attrs_idtf_list_return attrs_idtf_list34;
    #undef	RETURN_TYPE_attrs_idtf_list34
    #define	RETURN_TYPE_attrs_idtf_list34 scsParser_attrs_idtf_list_return

    pANTLR3_BASE_TREE SEP_LTUPLE33_tree;
    pANTLR3_BASE_TREE SEP_RTUPLE35_tree;

    /* Initialize rule variables
     */


    root_0 = NULL;

    SEP_LTUPLE33       = NULL;
    SEP_RTUPLE35       = NULL;
    attrs_idtf_list34.tree = NULL;

    retval.start = LT(1); retval.stop = retval.start;

    SEP_LTUPLE33_tree   = NULL;
    SEP_RTUPLE35_tree   = NULL;


    retval.tree  = NULL;
    {
        // grammar/scs.g:101:2: ( SEP_LTUPLE attrs_idtf_list SEP_RTUPLE )
        // grammar/scs.g:101:4: SEP_LTUPLE attrs_idtf_list SEP_RTUPLE
        {
            root_0 = (pANTLR3_BASE_TREE)(ADAPTOR->nilNode(ADAPTOR));

            SEP_LTUPLE33 = (pANTLR3_COMMON_TOKEN) MATCHT(SEP_LTUPLE, &FOLLOW_SEP_LTUPLE_in_idtf_tuple482); 
            if  (HASEXCEPTION())
            {
                goto ruleidtf_tupleEx;
            }

            SEP_LTUPLE33_tree = (pANTLR3_BASE_TREE)(ADAPTOR->create(ADAPTOR, SEP_LTUPLE33));
            ADAPTOR->addChild(ADAPTOR, root_0, SEP_LTUPLE33_tree);

            FOLLOWPUSH(FOLLOW_attrs_idtf_list_in_idtf_tuple484);
            attrs_idtf_list34=attrs_idtf_list(ctx);

            FOLLOWPOP();
            if  (HASEXCEPTION())
            {
                goto ruleidtf_tupleEx;
            }

            ADAPTOR->addChild(ADAPTOR, root_0, attrs_idtf_list34.tree);
            SEP_RTUPLE35 = (pANTLR3_COMMON_TOKEN) MATCHT(SEP_RTUPLE, &FOLLOW_SEP_RTUPLE_in_idtf_tuple487); 
            if  (HASEXCEPTION())
            {
                goto ruleidtf_tupleEx;
            }


        }

    }
    

    // This is where rules clean up and exit
    //
    goto ruleidtf_tupleEx; /* Prevent compiler warnings */
    ruleidtf_tupleEx: ;
    retval.stop = LT(-1);

    	retval.stop = LT(-1);
    	retval.tree = (pANTLR3_BASE_TREE)(ADAPTOR->rulePostProcessing(ADAPTOR, root_0));
    	ADAPTOR->setTokenBoundaries(ADAPTOR, retval.tree, retval.start, retval.stop);





    return retval;
}
/* $ANTLR end idtf_tuple */

/** 
 * $ANTLR start idtf_set
 * grammar/scs.g:104:1: idtf_set : SEP_LSET attrs_idtf_list SEP_RSET ;
 */
static scsParser_idtf_set_return
idtf_set(pscsParser ctx)
{   
    scsParser_idtf_set_return retval;

    pANTLR3_BASE_TREE root_0;

    pANTLR3_COMMON_TOKEN    SEP_LSET36;
    pANTLR3_COMMON_TOKEN    SEP_RSET38;
    scsParser_attrs_idtf_list_return attrs_idtf_list37;
    #undef	RETURN_TYPE_attrs_idtf_list37
    #define	RETURN_TYPE_attrs_idtf_list37 scsParser_attrs_idtf_list_return

    pANTLR3_BASE_TREE SEP_LSET36_tree;
    pANTLR3_BASE_TREE SEP_RSET38_tree;

    /* Initialize rule variables
     */


    root_0 = NULL;

    SEP_LSET36       = NULL;
    SEP_RSET38       = NULL;
    attrs_idtf_list37.tree = NULL;

    retval.start = LT(1); retval.stop = retval.start;

    SEP_LSET36_tree   = NULL;
    SEP_RSET38_tree   = NULL;


    retval.tree  = NULL;
    {
        // grammar/scs.g:105:2: ( SEP_LSET attrs_idtf_list SEP_RSET )
        // grammar/scs.g:105:4: SEP_LSET attrs_idtf_list SEP_RSET
        {
            root_0 = (pANTLR3_BASE_TREE)(ADAPTOR->nilNode(ADAPTOR));

            SEP_LSET36 = (pANTLR3_COMMON_TOKEN) MATCHT(SEP_LSET, &FOLLOW_SEP_LSET_in_idtf_set500); 
            if  (HASEXCEPTION())
            {
                goto ruleidtf_setEx;
            }

            SEP_LSET36_tree = (pANTLR3_BASE_TREE)(ADAPTOR->create(ADAPTOR, SEP_LSET36));
            ADAPTOR->addChild(ADAPTOR, root_0, SEP_LSET36_tree);

            FOLLOWPUSH(FOLLOW_attrs_idtf_list_in_idtf_set502);
            attrs_idtf_list37=attrs_idtf_list(ctx);

            FOLLOWPOP();
            if  (HASEXCEPTION())
            {
                goto ruleidtf_setEx;
            }

            ADAPTOR->addChild(ADAPTOR, root_0, attrs_idtf_list37.tree);
            SEP_RSET38 = (pANTLR3_COMMON_TOKEN) MATCHT(SEP_RSET, &FOLLOW_SEP_RSET_in_idtf_set504); 
            if  (HASEXCEPTION())
            {
                goto ruleidtf_setEx;
            }


        }

    }
    

    // This is where rules clean up and exit
    //
    goto ruleidtf_setEx; /* Prevent compiler warnings */
    ruleidtf_setEx: ;
    retval.stop = LT(-1);

    	retval.stop = LT(-1);
    	retval.tree = (pANTLR3_BASE_TREE)(ADAPTOR->rulePostProcessing(ADAPTOR, root_0));
    	ADAPTOR->setTokenBoundaries(ADAPTOR, retval.tree, retval.start, retval.stop);





    return retval;
}
/* $ANTLR end idtf_set */

/** 
 * $ANTLR start idtf
 * grammar/scs.g:108:1: idtf : ( idtf_level1 | idtf_edge | idtf_tuple | idtf_set | CONTENT );
 */
static scsParser_idtf_return
idtf(pscsParser ctx)
{   
    scsParser_idtf_return retval;

    pANTLR3_BASE_TREE root_0;

    pANTLR3_COMMON_TOKEN    CONTENT43;
    scsParser_idtf_level1_return idtf_level139;
    #undef	RETURN_TYPE_idtf_level139
    #define	RETURN_TYPE_idtf_level139 scsParser_idtf_level1_return

    scsParser_idtf_edge_return idtf_edge40;
    #undef	RETURN_TYPE_idtf_edge40
    #define	RETURN_TYPE_idtf_edge40 scsParser_idtf_edge_return

    scsParser_idtf_tuple_return idtf_tuple41;
    #undef	RETURN_TYPE_idtf_tuple41
    #define	RETURN_TYPE_idtf_tuple41 scsParser_idtf_tuple_return

    scsParser_idtf_set_return idtf_set42;
    #undef	RETURN_TYPE_idtf_set42
    #define	RETURN_TYPE_idtf_set42 scsParser_idtf_set_return

    pANTLR3_BASE_TREE CONTENT43_tree;

    /* Initialize rule variables
     */


    root_0 = NULL;

    CONTENT43       = NULL;
    idtf_level139.tree = NULL;

    idtf_edge40.tree = NULL;

    idtf_tuple41.tree = NULL;

    idtf_set42.tree = NULL;

    retval.start = LT(1); retval.stop = retval.start;

    CONTENT43_tree   = NULL;


    retval.tree  = NULL;
    {
        {
            //  grammar/scs.g:109:2: ( idtf_level1 | idtf_edge | idtf_tuple | idtf_set | CONTENT )
            
            ANTLR3_UINT32 alt8;

            alt8=5;

            switch ( LA(1) ) 
            {
            case ID_SYSTEM:
            case LINK:
            	{
            		alt8=1;
            	}
                break;
            case SEP_LPAR:
            	{
            		alt8=2;
            	}
                break;
            case SEP_LTUPLE:
            	{
            		alt8=3;
            	}
                break;
            case SEP_LSET:
            	{
            		alt8=4;
            	}
                break;
            case CONTENT:
            	{
            		alt8=5;
            	}
                break;

            default:
                CONSTRUCTEX();
                EXCEPTION->type         = ANTLR3_NO_VIABLE_ALT_EXCEPTION;
                EXCEPTION->message      = (void *)"";
                EXCEPTION->decisionNum  = 8;
                EXCEPTION->state        = 0;


                goto ruleidtfEx;
            }

            switch (alt8) 
            {
        	case 1:
        	    // grammar/scs.g:109:4: idtf_level1
        	    {
        	        root_0 = (pANTLR3_BASE_TREE)(ADAPTOR->nilNode(ADAPTOR));

        	        FOLLOWPUSH(FOLLOW_idtf_level1_in_idtf516);
        	        idtf_level139=idtf_level1(ctx);

        	        FOLLOWPOP();
        	        if  (HASEXCEPTION())
        	        {
        	            goto ruleidtfEx;
        	        }

        	        ADAPTOR->addChild(ADAPTOR, root_0, idtf_level139.tree);

        	    }
        	    break;
        	case 2:
        	    // grammar/scs.g:110:4: idtf_edge
        	    {
        	        root_0 = (pANTLR3_BASE_TREE)(ADAPTOR->nilNode(ADAPTOR));

        	        FOLLOWPUSH(FOLLOW_idtf_edge_in_idtf521);
        	        idtf_edge40=idtf_edge(ctx);

        	        FOLLOWPOP();
        	        if  (HASEXCEPTION())
        	        {
        	            goto ruleidtfEx;
        	        }

        	        ADAPTOR->addChild(ADAPTOR, root_0, idtf_edge40.tree);

        	    }
        	    break;
        	case 3:
        	    // grammar/scs.g:111:4: idtf_tuple
        	    {
        	        root_0 = (pANTLR3_BASE_TREE)(ADAPTOR->nilNode(ADAPTOR));

        	        FOLLOWPUSH(FOLLOW_idtf_tuple_in_idtf526);
        	        idtf_tuple41=idtf_tuple(ctx);

        	        FOLLOWPOP();
        	        if  (HASEXCEPTION())
        	        {
        	            goto ruleidtfEx;
        	        }

        	        ADAPTOR->addChild(ADAPTOR, root_0, idtf_tuple41.tree);

        	    }
        	    break;
        	case 4:
        	    // grammar/scs.g:112:4: idtf_set
        	    {
        	        root_0 = (pANTLR3_BASE_TREE)(ADAPTOR->nilNode(ADAPTOR));

        	        FOLLOWPUSH(FOLLOW_idtf_set_in_idtf531);
        	        idtf_set42=idtf_set(ctx);

        	        FOLLOWPOP();
        	        if  (HASEXCEPTION())
        	        {
        	            goto ruleidtfEx;
        	        }

        	        ADAPTOR->addChild(ADAPTOR, root_0, idtf_set42.tree);

        	    }
        	    break;
        	case 5:
        	    // grammar/scs.g:113:4: CONTENT
        	    {
        	        root_0 = (pANTLR3_BASE_TREE)(ADAPTOR->nilNode(ADAPTOR));

        	        CONTENT43 = (pANTLR3_COMMON_TOKEN) MATCHT(CONTENT, &FOLLOW_CONTENT_in_idtf536); 
        	        if  (HASEXCEPTION())
        	        {
        	            goto ruleidtfEx;
        	        }

        	        CONTENT43_tree = (pANTLR3_BASE_TREE)(ADAPTOR->create(ADAPTOR, CONTENT43));
        	        ADAPTOR->addChild(ADAPTOR, root_0, CONTENT43_tree);


        	    }
        	    break;

            }
        }
    }
    

    // This is where rules clean up and exit
    //
    goto ruleidtfEx; /* Prevent compiler warnings */
    ruleidtfEx: ;
    retval.stop = LT(-1);

    	retval.stop = LT(-1);
    	retval.tree = (pANTLR3_BASE_TREE)(ADAPTOR->rulePostProcessing(ADAPTOR, root_0));
    	ADAPTOR->setTokenBoundaries(ADAPTOR, retval.tree, retval.start, retval.stop);





    return retval;
}
/* $ANTLR end idtf */

/** 
 * $ANTLR start idtf_level1
 * grammar/scs.g:116:1: idtf_level1 : ( ID_SYSTEM | LINK );
 */
static scsParser_idtf_level1_return
idtf_level1(pscsParser ctx)
{   
    scsParser_idtf_level1_return retval;

    pANTLR3_BASE_TREE root_0;

    pANTLR3_COMMON_TOKEN    set44;

    pANTLR3_BASE_TREE set44_tree;

    /* Initialize rule variables
     */


    root_0 = NULL;

    set44       = NULL;
    retval.start = LT(1); retval.stop = retval.start;

    set44_tree   = NULL;


    retval.tree  = NULL;
    {
        // grammar/scs.g:117:2: ( ID_SYSTEM | LINK )
        // grammar/scs.g:
        {
            root_0 = (pANTLR3_BASE_TREE)(ADAPTOR->nilNode(ADAPTOR));

            set44=(pANTLR3_COMMON_TOKEN)LT(1);
            if ( ((LA(1) >= ID_SYSTEM) && (LA(1) <= LINK)) )
            {
                CONSUME();
                ADAPTOR->addChild(ADAPTOR, root_0, (pANTLR3_BASE_TREE)(ADAPTOR->create(ADAPTOR, set44)));
                PERRORRECOVERY=ANTLR3_FALSE;
            }
            else 
            {
                CONSTRUCTEX();
                EXCEPTION->type         = ANTLR3_MISMATCHED_SET_EXCEPTION;
                EXCEPTION->name         = (void *)ANTLR3_MISMATCHED_SET_NAME;
                EXCEPTION->expectingSet = &FOLLOW_set_in_idtf_level10;
                RECOVERFROMMISMATCHEDSET(&FOLLOW_set_in_idtf_level10);    goto ruleidtf_level1Ex;
            }


        }

    }
    

    // This is where rules clean up and exit
    //
    goto ruleidtf_level1Ex; /* Prevent compiler warnings */
    ruleidtf_level1Ex: ;
    retval.stop = LT(-1);

    	retval.stop = LT(-1);
    	retval.tree = (pANTLR3_BASE_TREE)(ADAPTOR->rulePostProcessing(ADAPTOR, root_0));
    	ADAPTOR->setTokenBoundaries(ADAPTOR, retval.tree, retval.start, retval.stop);





    return retval;
}
/* $ANTLR end idtf_level1 */

/** 
 * $ANTLR start idtf_edge
 * grammar/scs.g:123:1: idtf_edge : SEP_LPAR idtf CONNECTORS idtf SEP_RPAR ;
 */
static scsParser_idtf_edge_return
idtf_edge(pscsParser ctx)
{   
    scsParser_idtf_edge_return retval;

    pANTLR3_BASE_TREE root_0;

    pANTLR3_COMMON_TOKEN    SEP_LPAR45;
    pANTLR3_COMMON_TOKEN    CONNECTORS47;
    pANTLR3_COMMON_TOKEN    SEP_RPAR49;
    scsParser_idtf_return idtf46;
    #undef	RETURN_TYPE_idtf46
    #define	RETURN_TYPE_idtf46 scsParser_idtf_return

    scsParser_idtf_return idtf48;
    #undef	RETURN_TYPE_idtf48
    #define	RETURN_TYPE_idtf48 scsParser_idtf_return

    pANTLR3_BASE_TREE SEP_LPAR45_tree;
    pANTLR3_BASE_TREE CONNECTORS47_tree;
    pANTLR3_BASE_TREE SEP_RPAR49_tree;

    /* Initialize rule variables
     */


    root_0 = NULL;

    SEP_LPAR45       = NULL;
    CONNECTORS47       = NULL;
    SEP_RPAR49       = NULL;
    idtf46.tree = NULL;

    idtf48.tree = NULL;

    retval.start = LT(1); retval.stop = retval.start;

    SEP_LPAR45_tree   = NULL;
    CONNECTORS47_tree   = NULL;
    SEP_RPAR49_tree   = NULL;


    retval.tree  = NULL;
    {
        // grammar/scs.g:124:2: ( SEP_LPAR idtf CONNECTORS idtf SEP_RPAR )
        // grammar/scs.g:124:4: SEP_LPAR idtf CONNECTORS idtf SEP_RPAR
        {
            root_0 = (pANTLR3_BASE_TREE)(ADAPTOR->nilNode(ADAPTOR));

            SEP_LPAR45 = (pANTLR3_COMMON_TOKEN) MATCHT(SEP_LPAR, &FOLLOW_SEP_LPAR_in_idtf_edge565); 
            if  (HASEXCEPTION())
            {
                goto ruleidtf_edgeEx;
            }

            SEP_LPAR45_tree = (pANTLR3_BASE_TREE)(ADAPTOR->create(ADAPTOR, SEP_LPAR45));
            ADAPTOR->addChild(ADAPTOR, root_0, SEP_LPAR45_tree);

            FOLLOWPUSH(FOLLOW_idtf_in_idtf_edge567);
            idtf46=idtf(ctx);

            FOLLOWPOP();
            if  (HASEXCEPTION())
            {
                goto ruleidtf_edgeEx;
            }

            ADAPTOR->addChild(ADAPTOR, root_0, idtf46.tree);
            CONNECTORS47 = (pANTLR3_COMMON_TOKEN) MATCHT(CONNECTORS, &FOLLOW_CONNECTORS_in_idtf_edge569); 
            if  (HASEXCEPTION())
            {
                goto ruleidtf_edgeEx;
            }

            CONNECTORS47_tree = (pANTLR3_BASE_TREE)(ADAPTOR->create(ADAPTOR, CONNECTORS47));
            ADAPTOR->addChild(ADAPTOR, root_0, CONNECTORS47_tree);

            FOLLOWPUSH(FOLLOW_idtf_in_idtf_edge571);
            idtf48=idtf(ctx);

            FOLLOWPOP();
            if  (HASEXCEPTION())
            {
                goto ruleidtf_edgeEx;
            }

            ADAPTOR->addChild(ADAPTOR, root_0, idtf48.tree);
            SEP_RPAR49 = (pANTLR3_COMMON_TOKEN) MATCHT(SEP_RPAR, &FOLLOW_SEP_RPAR_in_idtf_edge573); 
            if  (HASEXCEPTION())
            {
                goto ruleidtf_edgeEx;
            }


        }

    }
    

    // This is where rules clean up and exit
    //
    goto ruleidtf_edgeEx; /* Prevent compiler warnings */
    ruleidtf_edgeEx: ;
    retval.stop = LT(-1);

    	retval.stop = LT(-1);
    	retval.tree = (pANTLR3_BASE_TREE)(ADAPTOR->rulePostProcessing(ADAPTOR, root_0));
    	ADAPTOR->setTokenBoundaries(ADAPTOR, retval.tree, retval.start, retval.stop);





    return retval;
}
/* $ANTLR end idtf_edge */
/* End of parsing rules
 * ==============================================
 */

/* ==============================================
 * Syntactic predicates
 */
/* End of syntactic predicates
 * ==============================================
 */

 
 



/* End of code
 * =============================================================================
 */
