/** \file
 *  This C source file was generated by $ANTLR version !Unknown version!
 *
 *     -  From the grammar source file : grammar/scs.g
 *     -                            On : 2013-11-09 00:22:36
 *     -                for the parser : scsParserParser *
 * Editing it, at least manually, is not wise. 
 *
 * C language generator and runtime by Jim Idle, jimi|hereisanat|idle|dotgoeshere|ws.
 *
 *
*/
// [The "BSD licence"]
// Copyright (c) 2005-2009 Jim Idle, Temporal Wave LLC
// http://www.temporal-wave.com
// http://www.linkedin.com/in/jimidle
//
// All rights reserved.
//
// Redistribution and use in source and binary forms, with or without
// modification, are permitted provided that the following conditions
// are met:
// 1. Redistributions of source code must retain the above copyright
//    notice, this list of conditions and the following disclaimer.
// 2. Redistributions in binary form must reproduce the above copyright
//    notice, this list of conditions and the following disclaimer in the
//    documentation and/or other materials provided with the distribution.
// 3. The name of the author may not be used to endorse or promote products
//    derived from this software without specific prior written permission.
//
// THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS OR
// IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
// OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
// IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT,
// INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
// NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
// DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
// THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
// (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF
// THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

/* -----------------------------------------
 * Include the ANTLR3 generated header file.
 */
#include    "scsParser.h"



/* ----------------------------------------- */





/* MACROS that hide the C interface implementations from the
 * generated code, which makes it a little more understandable to the human eye.
 * I am very much against using C pre-processor macros for function calls and bits
 * of code as you cannot see what is happening when single stepping in debuggers
 * and so on. The exception (in my book at least) is for generated code, where you are
 * not maintaining it, but may wish to read and understand it. If you single step it, you know that input()
 * hides some indirect calls, but is always referring to the input stream. This is
 * probably more readable than ctx->input->istream->input(snarfle0->blarg) and allows me to rejig
 * the runtime interfaces without changing the generated code too often, without
 * confusing the reader of the generated output, who may not wish to know the gory
 * details of the interface inheritance.
 */
 
#define		CTX	ctx

/* Aids in accessing scopes for grammar programmers
 */
#undef	SCOPE_TYPE
#undef	SCOPE_STACK
#undef	SCOPE_TOP
#define	SCOPE_TYPE(scope)   pscsParser_##scope##_SCOPE
#define SCOPE_STACK(scope)  pscsParser_##scope##Stack
#define	SCOPE_TOP(scope)    ctx->pscsParser_##scope##Top
#define	SCOPE_SIZE(scope)		ctx->pscsParser_##scope##Stack_limit
#define SCOPE_INSTANCE(scope, i)	(ctx->SCOPE_STACK(scope)->get(ctx->SCOPE_STACK(scope),i))

/* Macros for accessing things in the parser
 */
 
#undef	    PARSER		    
#undef	    RECOGNIZER		    
#undef	    HAVEPARSEDRULE
#undef		MEMOIZE
#undef	    INPUT
#undef	    STRSTREAM
#undef	    HASEXCEPTION
#undef	    EXCEPTION
#undef	    MATCHT
#undef	    MATCHANYT
#undef	    FOLLOWSTACK
#undef	    FOLLOWPUSH
#undef	    FOLLOWPOP
#undef	    PRECOVER
#undef	    PREPORTERROR
#undef	    LA
#undef	    LT
#undef	    CONSTRUCTEX
#undef	    CONSUME
#undef	    MARK
#undef	    REWIND
#undef	    REWINDLAST
#undef	    PERRORRECOVERY
#undef	    HASFAILED
#undef	    FAILEDFLAG
#undef	    RECOVERFROMMISMATCHEDSET
#undef	    RECOVERFROMMISMATCHEDELEMENT
#undef		INDEX
#undef      ADAPTOR
#undef		SEEK
#undef	    RULEMEMO		    
#undef		DBG

#define	    PARSER							ctx->pParser  
#define	    RECOGNIZER						PARSER->rec
#define		PSRSTATE						RECOGNIZER->state
#define	    HAVEPARSEDRULE(r)				RECOGNIZER->alreadyParsedRule(RECOGNIZER, r)
#define		MEMOIZE(ri,si)					RECOGNIZER->memoize(RECOGNIZER, ri, si)
#define	    INPUT							PARSER->tstream
#define	    STRSTREAM						INPUT
#define		ISTREAM							INPUT->istream
#define		INDEX()							ISTREAM->index(INPUT->istream)
#define	    HASEXCEPTION()					(PSRSTATE->error == ANTLR3_TRUE)
#define	    EXCEPTION						PSRSTATE->exception
#define	    MATCHT(t, fs)					RECOGNIZER->match(RECOGNIZER, t, fs)
#define	    MATCHANYT()						RECOGNIZER->matchAny(RECOGNIZER)
#define	    FOLLOWSTACK					    PSRSTATE->following
#define	    FOLLOWPUSH(x)					FOLLOWSTACK->push(FOLLOWSTACK, ((void *)(&(x))), NULL)
#define	    FOLLOWPOP()						FOLLOWSTACK->pop(FOLLOWSTACK)
#define	    PRECOVER()						RECOGNIZER->recover(RECOGNIZER)
#define	    PREPORTERROR()					RECOGNIZER->reportError(RECOGNIZER)
#define	    LA(n)							INPUT->istream->_LA(ISTREAM, n)
#define	    LT(n)							INPUT->_LT(INPUT, n)
#define	    CONSTRUCTEX()					RECOGNIZER->exConstruct(RECOGNIZER)
#define	    CONSUME()						ISTREAM->consume(ISTREAM)
#define	    MARK()							ISTREAM->mark(ISTREAM)
#define	    REWIND(m)						ISTREAM->rewind(ISTREAM, m)
#define	    REWINDLAST()					ISTREAM->rewindLast(ISTREAM)
#define		SEEK(n)							ISTREAM->seek(ISTREAM, n)
#define	    PERRORRECOVERY					PSRSTATE->errorRecovery
#define	    FAILEDFLAG						PSRSTATE->failed
#define	    HASFAILED()						(FAILEDFLAG == ANTLR3_TRUE)
#define	    BACKTRACKING					PSRSTATE->backtracking
#define	    RECOVERFROMMISMATCHEDSET(s)		RECOGNIZER->recoverFromMismatchedSet(RECOGNIZER, s)
#define	    RECOVERFROMMISMATCHEDELEMENT(e)	RECOGNIZER->recoverFromMismatchedElement(RECOGNIZER, s)
#define     ADAPTOR                         ctx->adaptor
#define		RULEMEMO						PSRSTATE->ruleMemo
#define		DBG								RECOGNIZER->debugger

#define		TOKTEXT(tok, txt)				tok, (pANTLR3_UINT8)txt

/* The 4 tokens defined below may well clash with your own #defines or token types. If so
 * then for the present you must use different names for your defines as these are hard coded
 * in the code generator. It would be better not to use such names internally, and maybe
 * we can change this in a forthcoming release. I deliberately do not #undef these
 * here as this will at least give you a redefined error somewhere if they clash.
 */
#define	    UP	    ANTLR3_TOKEN_UP
#define	    DOWN    ANTLR3_TOKEN_DOWN
#define	    EOR	    ANTLR3_TOKEN_EOR
#define	    INVALID ANTLR3_TOKEN_INVALID


/* =============================================================================
 * Functions to create and destroy scopes. First come the rule scopes, followed
 * by the global declared scopes.
 */



/* ============================================================================= */

/* =============================================================================
 * Start of recognizer
 */



/** \brief Table of all token names in symbolic order, mainly used for
 *         error reporting.
 */
pANTLR3_UINT8   scsParserTokenNames[25+4]
     = {
        (pANTLR3_UINT8) "<invalid>",       /* String to print to indicate an invalid token */
        (pANTLR3_UINT8) "<EOR>",
        (pANTLR3_UINT8) "<DOWN>", 
        (pANTLR3_UINT8) "<UP>", 
        (pANTLR3_UINT8) "SEP_SENTENCE",
        (pANTLR3_UINT8) "SEP_SIMPLE",
        (pANTLR3_UINT8) "SEP_LPAR",
        (pANTLR3_UINT8) "SEP_RPAR",
        (pANTLR3_UINT8) "SEP_ATTR_CONST",
        (pANTLR3_UINT8) "SEP_ATTR_VAR",
        (pANTLR3_UINT8) "SEP_IDTF",
        (pANTLR3_UINT8) "SEP_LINT",
        (pANTLR3_UINT8) "SEP_RINT",
        (pANTLR3_UINT8) "SEP_LTUPLE",
        (pANTLR3_UINT8) "SEP_RTUPLE",
        (pANTLR3_UINT8) "SEP_LSET",
        (pANTLR3_UINT8) "SEP_RSET",
        (pANTLR3_UINT8) "SEP_LCONTENT",
        (pANTLR3_UINT8) "SEP_RCONTENT",
        (pANTLR3_UINT8) "SEP_ASSIGN",
        (pANTLR3_UINT8) "CONNECTORS",
        (pANTLR3_UINT8) "CONTENT",
        (pANTLR3_UINT8) "ID_SYSTEM",
        (pANTLR3_UINT8) "LINK",
        (pANTLR3_UINT8) "COMMENT",
        (pANTLR3_UINT8) "HEX_DIGIT",
        (pANTLR3_UINT8) "WS",
        (pANTLR3_UINT8) "OCTAL_ESC",
        (pANTLR3_UINT8) "UNICODE_ESC"
       };

        

// Forward declare the locally static matching functions we have generated.
//
static scsParser_syntax_return	syntax    (pscsParser ctx);
static scsParser_sentence_return	sentence    (pscsParser ctx);
static scsParser_sentence_level1_return	sentence_level1    (pscsParser ctx);
static scsParser_sentence_level2_6_return	sentence_level2_6    (pscsParser ctx);
static scsParser_sentence_internal_list_return	sentence_internal_list    (pscsParser ctx);
static scsParser_sentence_assignment_return	sentence_assignment    (pscsParser ctx);
static scsParser_sentence_internal_return	sentence_internal    (pscsParser ctx);
static scsParser_attrs_idtf_list_return	attrs_idtf_list    (pscsParser ctx);
static scsParser_idtf_attrs_return	idtf_attrs    (pscsParser ctx);
static scsParser_attrs_list_return	attrs_list    (pscsParser ctx);
static scsParser_idtf_internal_return	idtf_internal    (pscsParser ctx);
static scsParser_idtf_tuple_return	idtf_tuple    (pscsParser ctx);
static scsParser_idtf_set_return	idtf_set    (pscsParser ctx);
static scsParser_idtf_return	idtf    (pscsParser ctx);
static scsParser_idtf_level1_return	idtf_level1    (pscsParser ctx);
static scsParser_idtf_edge_return	idtf_edge    (pscsParser ctx);
static void	scsParserFree(pscsParser ctx);
/* For use in tree output where we are accumulating rule labels via label += ruleRef
 * we need a function that knows how to free a return scope when the list is destroyed. 
 * We cannot just use ANTLR3_FREE because in debug tracking mode, this is a macro.
 */
static	void ANTLR3_CDECL freeScope(void * scope)
{
    ANTLR3_FREE(scope);
}

/** \brief Name of the grammar file that generated this code
 */
static const char fileName[] = "grammar/scs.g";

/** \brief Return the name of the grammar file that generated this code.
 */
static const char * getGrammarFileName()
{
	return fileName;
}
/** \brief Create a new scsParser parser and return a context for it.
 *
 * \param[in] instream Pointer to an input stream interface.
 *
 * \return Pointer to new parser context upon success.
 */
ANTLR3_API pscsParser
scsParserNew   (pANTLR3_COMMON_TOKEN_STREAM instream)
{
	// See if we can create a new parser with the standard constructor
	//
	return scsParserNewSSD(instream, NULL);
}

/** \brief Create a new scsParser parser and return a context for it.
 *
 * \param[in] instream Pointer to an input stream interface.
 *
 * \return Pointer to new parser context upon success.
 */
ANTLR3_API pscsParser
scsParserNewSSD   (pANTLR3_COMMON_TOKEN_STREAM instream, pANTLR3_RECOGNIZER_SHARED_STATE state)
{
    pscsParser ctx;	    /* Context structure we will build and return   */
    
    ctx	= (pscsParser) ANTLR3_CALLOC(1, sizeof(scsParser));
    
    if	(ctx == NULL)
    {
		// Failed to allocate memory for parser context
		//
        return  NULL;
    }
    
    /* -------------------------------------------------------------------
     * Memory for basic structure is allocated, now to fill in
     * the base ANTLR3 structures. We initialize the function pointers
     * for the standard ANTLR3 parser function set, but upon return
     * from here, the programmer may set the pointers to provide custom
     * implementations of each function. 
     *
     * We don't use the macros defined in scsParser.h here, in order that you can get a sense
     * of what goes where.
     */

    /* Create a base parser/recognizer, using the supplied token stream
     */
    ctx->pParser	    = antlr3ParserNewStream(ANTLR3_SIZE_HINT, instream->tstream, state);
    /* Install the implementation of our scsParser interface
     */
    ctx->syntax	= syntax;
    ctx->sentence	= sentence;
    ctx->sentence_level1	= sentence_level1;
    ctx->sentence_level2_6	= sentence_level2_6;
    ctx->sentence_internal_list	= sentence_internal_list;
    ctx->sentence_assignment	= sentence_assignment;
    ctx->sentence_internal	= sentence_internal;
    ctx->attrs_idtf_list	= attrs_idtf_list;
    ctx->idtf_attrs	= idtf_attrs;
    ctx->attrs_list	= attrs_list;
    ctx->idtf_internal	= idtf_internal;
    ctx->idtf_tuple	= idtf_tuple;
    ctx->idtf_set	= idtf_set;
    ctx->idtf	= idtf;
    ctx->idtf_level1	= idtf_level1;
    ctx->idtf_edge	= idtf_edge;
    ctx->free			= scsParserFree;
    ctx->getGrammarFileName	= getGrammarFileName;
    
    /* Install the scope pushing methods.
     */
    ADAPTOR	= ANTLR3_TREE_ADAPTORNew(instream->tstream->tokenSource->strFactory);
    ctx->vectors	= antlr3VectorFactoryNew(0);
    

	
    /* Install the token table
     */
    PSRSTATE->tokenNames   = scsParserTokenNames;
    
    
    /* Return the newly built parser to the caller
     */
    return  ctx;
}

/** Free the parser resources
 */
 static void
 scsParserFree(pscsParser ctx)
 {
    /* Free any scope memory
     */
    
    ctx->vectors->close(ctx->vectors);
    /* We created the adaptor so we must free it
     */
    ADAPTOR->free(ADAPTOR);
	// Free this parser
	//
    ctx->pParser->free(ctx->pParser);
    ANTLR3_FREE(ctx);

    /* Everything is released, so we can return
     */
    return;
 }
 
/** Return token names used by this parser
 *
 * The returned pointer is used as an index into the token names table (using the token 
 * number as the index).
 * 
 * \return Pointer to first char * in the table.
 */
static pANTLR3_UINT8    *getTokenNames() 
{
        return scsParserTokenNames; 
}

    
/* Declare the bitsets
 */

/** Bitset defining follow set for error recovery in rule state: FOLLOW_sentence_in_syntax254  */
static	ANTLR3_BITWORD FOLLOW_sentence_in_syntax254_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000010) };
static  ANTLR3_BITSET_LIST FOLLOW_sentence_in_syntax254	= { FOLLOW_sentence_in_syntax254_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_SEP_SENTENCE_in_syntax256  */
static	ANTLR3_BITWORD FOLLOW_SEP_SENTENCE_in_syntax256_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000E8A040) };
static  ANTLR3_BITSET_LIST FOLLOW_SEP_SENTENCE_in_syntax256	= { FOLLOW_SEP_SENTENCE_in_syntax256_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_EOF_in_syntax260  */
static	ANTLR3_BITWORD FOLLOW_EOF_in_syntax260_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_EOF_in_syntax260	= { FOLLOW_EOF_in_syntax260_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_sentence_level1_in_sentence272  */
static	ANTLR3_BITWORD FOLLOW_sentence_level1_in_sentence272_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_sentence_level1_in_sentence272	= { FOLLOW_sentence_level1_in_sentence272_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_sentence_level2_6_in_sentence277  */
static	ANTLR3_BITWORD FOLLOW_sentence_level2_6_in_sentence277_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_sentence_level2_6_in_sentence277	= { FOLLOW_sentence_level2_6_in_sentence277_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_sentence_assignment_in_sentence282  */
static	ANTLR3_BITWORD FOLLOW_sentence_assignment_in_sentence282_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_sentence_assignment_in_sentence282	= { FOLLOW_sentence_assignment_in_sentence282_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_idtf_level1_in_sentence_level1294  */
static	ANTLR3_BITWORD FOLLOW_idtf_level1_in_sentence_level1294_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000020) };
static  ANTLR3_BITSET_LIST FOLLOW_idtf_level1_in_sentence_level1294	= { FOLLOW_idtf_level1_in_sentence_level1294_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_SEP_SIMPLE_in_sentence_level1296  */
static	ANTLR3_BITWORD FOLLOW_SEP_SIMPLE_in_sentence_level1296_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000C00000) };
static  ANTLR3_BITSET_LIST FOLLOW_SEP_SIMPLE_in_sentence_level1296	= { FOLLOW_SEP_SIMPLE_in_sentence_level1296_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_idtf_level1_in_sentence_level1298  */
static	ANTLR3_BITWORD FOLLOW_idtf_level1_in_sentence_level1298_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000020) };
static  ANTLR3_BITSET_LIST FOLLOW_idtf_level1_in_sentence_level1298	= { FOLLOW_idtf_level1_in_sentence_level1298_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_SEP_SIMPLE_in_sentence_level1300  */
static	ANTLR3_BITWORD FOLLOW_SEP_SIMPLE_in_sentence_level1300_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000C00000) };
static  ANTLR3_BITSET_LIST FOLLOW_SEP_SIMPLE_in_sentence_level1300	= { FOLLOW_SEP_SIMPLE_in_sentence_level1300_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_idtf_level1_in_sentence_level1302  */
static	ANTLR3_BITWORD FOLLOW_idtf_level1_in_sentence_level1302_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_idtf_level1_in_sentence_level1302	= { FOLLOW_idtf_level1_in_sentence_level1302_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_idtf_in_sentence_level2_6317  */
static	ANTLR3_BITWORD FOLLOW_idtf_in_sentence_level2_6317_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000100000) };
static  ANTLR3_BITSET_LIST FOLLOW_idtf_in_sentence_level2_6317	= { FOLLOW_idtf_in_sentence_level2_6317_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_CONNECTORS_in_sentence_level2_6319  */
static	ANTLR3_BITWORD FOLLOW_CONNECTORS_in_sentence_level2_6319_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000E0A840) };
static  ANTLR3_BITSET_LIST FOLLOW_CONNECTORS_in_sentence_level2_6319	= { FOLLOW_CONNECTORS_in_sentence_level2_6319_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_attrs_idtf_list_in_sentence_level2_6321  */
static	ANTLR3_BITWORD FOLLOW_attrs_idtf_list_in_sentence_level2_6321_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_attrs_idtf_list_in_sentence_level2_6321	= { FOLLOW_attrs_idtf_list_in_sentence_level2_6321_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_SEP_LINT_in_sentence_internal_list333  */
static	ANTLR3_BITWORD FOLLOW_SEP_LINT_in_sentence_internal_list333_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000101000) };
static  ANTLR3_BITSET_LIST FOLLOW_SEP_LINT_in_sentence_internal_list333	= { FOLLOW_SEP_LINT_in_sentence_internal_list333_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_sentence_internal_in_sentence_internal_list337  */
static	ANTLR3_BITWORD FOLLOW_sentence_internal_in_sentence_internal_list337_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000010) };
static  ANTLR3_BITSET_LIST FOLLOW_sentence_internal_in_sentence_internal_list337	= { FOLLOW_sentence_internal_in_sentence_internal_list337_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_SEP_SENTENCE_in_sentence_internal_list339  */
static	ANTLR3_BITWORD FOLLOW_SEP_SENTENCE_in_sentence_internal_list339_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000101000) };
static  ANTLR3_BITSET_LIST FOLLOW_SEP_SENTENCE_in_sentence_internal_list339	= { FOLLOW_SEP_SENTENCE_in_sentence_internal_list339_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_SEP_RINT_in_sentence_internal_list343  */
static	ANTLR3_BITWORD FOLLOW_SEP_RINT_in_sentence_internal_list343_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_SEP_RINT_in_sentence_internal_list343	= { FOLLOW_SEP_RINT_in_sentence_internal_list343_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_idtf_in_sentence_assignment355  */
static	ANTLR3_BITWORD FOLLOW_idtf_in_sentence_assignment355_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000080000) };
static  ANTLR3_BITSET_LIST FOLLOW_idtf_in_sentence_assignment355	= { FOLLOW_idtf_in_sentence_assignment355_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_SEP_ASSIGN_in_sentence_assignment357  */
static	ANTLR3_BITWORD FOLLOW_SEP_ASSIGN_in_sentence_assignment357_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000E0A040) };
static  ANTLR3_BITSET_LIST FOLLOW_SEP_ASSIGN_in_sentence_assignment357	= { FOLLOW_SEP_ASSIGN_in_sentence_assignment357_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_idtf_in_sentence_assignment359  */
static	ANTLR3_BITWORD FOLLOW_idtf_in_sentence_assignment359_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_idtf_in_sentence_assignment359	= { FOLLOW_idtf_in_sentence_assignment359_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_CONNECTORS_in_sentence_internal371  */
static	ANTLR3_BITWORD FOLLOW_CONNECTORS_in_sentence_internal371_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000E0A840) };
static  ANTLR3_BITSET_LIST FOLLOW_CONNECTORS_in_sentence_internal371	= { FOLLOW_CONNECTORS_in_sentence_internal371_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_attrs_idtf_list_in_sentence_internal373  */
static	ANTLR3_BITWORD FOLLOW_attrs_idtf_list_in_sentence_internal373_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_attrs_idtf_list_in_sentence_internal373	= { FOLLOW_attrs_idtf_list_in_sentence_internal373_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_idtf_attrs_in_attrs_idtf_list385  */
static	ANTLR3_BITWORD FOLLOW_idtf_attrs_in_attrs_idtf_list385_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000402) };
static  ANTLR3_BITSET_LIST FOLLOW_idtf_attrs_in_attrs_idtf_list385	= { FOLLOW_idtf_attrs_in_attrs_idtf_list385_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_SEP_IDTF_in_attrs_idtf_list389  */
static	ANTLR3_BITWORD FOLLOW_SEP_IDTF_in_attrs_idtf_list389_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000E0A840) };
static  ANTLR3_BITSET_LIST FOLLOW_SEP_IDTF_in_attrs_idtf_list389	= { FOLLOW_SEP_IDTF_in_attrs_idtf_list389_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_idtf_attrs_in_attrs_idtf_list391  */
static	ANTLR3_BITWORD FOLLOW_idtf_attrs_in_attrs_idtf_list391_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000402) };
static  ANTLR3_BITSET_LIST FOLLOW_idtf_attrs_in_attrs_idtf_list391	= { FOLLOW_idtf_attrs_in_attrs_idtf_list391_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_attrs_list_in_idtf_attrs405  */
static	ANTLR3_BITWORD FOLLOW_attrs_list_in_idtf_attrs405_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000E0A840) };
static  ANTLR3_BITSET_LIST FOLLOW_attrs_list_in_idtf_attrs405	= { FOLLOW_attrs_list_in_idtf_attrs405_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_idtf_internal_in_idtf_attrs407  */
static	ANTLR3_BITWORD FOLLOW_idtf_internal_in_idtf_attrs407_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_idtf_internal_in_idtf_attrs407	= { FOLLOW_idtf_internal_in_idtf_attrs407_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_idtf_level1_in_attrs_list420  */
static	ANTLR3_BITWORD FOLLOW_idtf_level1_in_attrs_list420_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000300) };
static  ANTLR3_BITSET_LIST FOLLOW_idtf_level1_in_attrs_list420	= { FOLLOW_idtf_level1_in_attrs_list420_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_set_in_attrs_list422  */
static	ANTLR3_BITWORD FOLLOW_set_in_attrs_list422_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000C00002) };
static  ANTLR3_BITSET_LIST FOLLOW_set_in_attrs_list422	= { FOLLOW_set_in_attrs_list422_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_idtf_in_idtf_internal442  */
static	ANTLR3_BITWORD FOLLOW_idtf_in_idtf_internal442_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000802) };
static  ANTLR3_BITSET_LIST FOLLOW_idtf_in_idtf_internal442	= { FOLLOW_idtf_in_idtf_internal442_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_sentence_internal_list_in_idtf_internal444  */
static	ANTLR3_BITWORD FOLLOW_sentence_internal_list_in_idtf_internal444_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_sentence_internal_list_in_idtf_internal444	= { FOLLOW_sentence_internal_list_in_idtf_internal444_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_SEP_LTUPLE_in_idtf_tuple456  */
static	ANTLR3_BITWORD FOLLOW_SEP_LTUPLE_in_idtf_tuple456_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000E0A840) };
static  ANTLR3_BITSET_LIST FOLLOW_SEP_LTUPLE_in_idtf_tuple456	= { FOLLOW_SEP_LTUPLE_in_idtf_tuple456_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_attrs_idtf_list_in_idtf_tuple458  */
static	ANTLR3_BITWORD FOLLOW_attrs_idtf_list_in_idtf_tuple458_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000004000) };
static  ANTLR3_BITSET_LIST FOLLOW_attrs_idtf_list_in_idtf_tuple458	= { FOLLOW_attrs_idtf_list_in_idtf_tuple458_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_SEP_RTUPLE_in_idtf_tuple461  */
static	ANTLR3_BITWORD FOLLOW_SEP_RTUPLE_in_idtf_tuple461_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_SEP_RTUPLE_in_idtf_tuple461	= { FOLLOW_SEP_RTUPLE_in_idtf_tuple461_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_SEP_LSET_in_idtf_set473  */
static	ANTLR3_BITWORD FOLLOW_SEP_LSET_in_idtf_set473_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000E0A840) };
static  ANTLR3_BITSET_LIST FOLLOW_SEP_LSET_in_idtf_set473	= { FOLLOW_SEP_LSET_in_idtf_set473_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_attrs_idtf_list_in_idtf_set475  */
static	ANTLR3_BITWORD FOLLOW_attrs_idtf_list_in_idtf_set475_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000010000) };
static  ANTLR3_BITSET_LIST FOLLOW_attrs_idtf_list_in_idtf_set475	= { FOLLOW_attrs_idtf_list_in_idtf_set475_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_SEP_RSET_in_idtf_set477  */
static	ANTLR3_BITWORD FOLLOW_SEP_RSET_in_idtf_set477_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_SEP_RSET_in_idtf_set477	= { FOLLOW_SEP_RSET_in_idtf_set477_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_idtf_level1_in_idtf488  */
static	ANTLR3_BITWORD FOLLOW_idtf_level1_in_idtf488_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_idtf_level1_in_idtf488	= { FOLLOW_idtf_level1_in_idtf488_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_idtf_edge_in_idtf493  */
static	ANTLR3_BITWORD FOLLOW_idtf_edge_in_idtf493_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_idtf_edge_in_idtf493	= { FOLLOW_idtf_edge_in_idtf493_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_idtf_tuple_in_idtf498  */
static	ANTLR3_BITWORD FOLLOW_idtf_tuple_in_idtf498_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_idtf_tuple_in_idtf498	= { FOLLOW_idtf_tuple_in_idtf498_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_idtf_set_in_idtf503  */
static	ANTLR3_BITWORD FOLLOW_idtf_set_in_idtf503_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_idtf_set_in_idtf503	= { FOLLOW_idtf_set_in_idtf503_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_CONTENT_in_idtf508  */
static	ANTLR3_BITWORD FOLLOW_CONTENT_in_idtf508_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_CONTENT_in_idtf508	= { FOLLOW_CONTENT_in_idtf508_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_set_in_idtf_level10  */
static	ANTLR3_BITWORD FOLLOW_set_in_idtf_level10_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_set_in_idtf_level10	= { FOLLOW_set_in_idtf_level10_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_SEP_LPAR_in_idtf_edge537  */
static	ANTLR3_BITWORD FOLLOW_SEP_LPAR_in_idtf_edge537_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000F0A040) };
static  ANTLR3_BITSET_LIST FOLLOW_SEP_LPAR_in_idtf_edge537	= { FOLLOW_SEP_LPAR_in_idtf_edge537_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_idtf_in_idtf_edge539  */
static	ANTLR3_BITWORD FOLLOW_idtf_in_idtf_edge539_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000100000) };
static  ANTLR3_BITSET_LIST FOLLOW_idtf_in_idtf_edge539	= { FOLLOW_idtf_in_idtf_edge539_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_CONNECTORS_in_idtf_edge541  */
static	ANTLR3_BITWORD FOLLOW_CONNECTORS_in_idtf_edge541_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000E0A0C0) };
static  ANTLR3_BITSET_LIST FOLLOW_CONNECTORS_in_idtf_edge541	= { FOLLOW_CONNECTORS_in_idtf_edge541_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_idtf_in_idtf_edge543  */
static	ANTLR3_BITWORD FOLLOW_idtf_in_idtf_edge543_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000080) };
static  ANTLR3_BITSET_LIST FOLLOW_idtf_in_idtf_edge543	= { FOLLOW_idtf_in_idtf_edge543_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_SEP_RPAR_in_idtf_edge545  */
static	ANTLR3_BITWORD FOLLOW_SEP_RPAR_in_idtf_edge545_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_SEP_RPAR_in_idtf_edge545	= { FOLLOW_SEP_RPAR_in_idtf_edge545_bits, 1	};
     

 
 
/* ==============================================
 * Parsing rules
 */
/** 
 * $ANTLR start syntax
 * grammar/scs.g:52:1: syntax : ( sentence SEP_SENTENCE )* EOF ;
 */
static scsParser_syntax_return
syntax(pscsParser ctx)
{   
    scsParser_syntax_return retval;

    pANTLR3_BASE_TREE root_0;

    pANTLR3_COMMON_TOKEN    SEP_SENTENCE2;
    pANTLR3_COMMON_TOKEN    EOF3;
    scsParser_sentence_return sentence1;
    #undef	RETURN_TYPE_sentence1
    #define	RETURN_TYPE_sentence1 scsParser_sentence_return

    pANTLR3_BASE_TREE SEP_SENTENCE2_tree;
    pANTLR3_BASE_TREE EOF3_tree;

    /* Initialize rule variables
     */


    root_0 = NULL;

    SEP_SENTENCE2       = NULL;
    EOF3       = NULL;
    sentence1.tree = NULL;

    retval.start = LT(1); retval.stop = retval.start;

    SEP_SENTENCE2_tree   = NULL;
    EOF3_tree   = NULL;


    retval.tree  = NULL;
    {
        // grammar/scs.g:53:2: ( ( sentence SEP_SENTENCE )* EOF )
        // grammar/scs.g:53:4: ( sentence SEP_SENTENCE )* EOF
        {
            root_0 = (pANTLR3_BASE_TREE)(ADAPTOR->nilNode(ADAPTOR));


            // grammar/scs.g:53:4: ( sentence SEP_SENTENCE )*

            for (;;)
            {
                int alt1=2;
                switch ( LA(1) ) 
                {
                case SEP_SENTENCE:
                case SEP_LPAR:
                case SEP_LTUPLE:
                case SEP_LSET:
                case CONTENT:
                case ID_SYSTEM:
                case LINK:
                	{
                		alt1=1;
                	}
                    break;

                }

                switch (alt1) 
                {
            	case 1:
            	    // grammar/scs.g:53:5: sentence SEP_SENTENCE
            	    {
            	        FOLLOWPUSH(FOLLOW_sentence_in_syntax254);
            	        sentence1=sentence(ctx);

            	        FOLLOWPOP();
            	        if  (HASEXCEPTION())
            	        {
            	            goto rulesyntaxEx;
            	        }

            	        ADAPTOR->addChild(ADAPTOR, root_0, sentence1.tree);
            	        SEP_SENTENCE2 = (pANTLR3_COMMON_TOKEN) MATCHT(SEP_SENTENCE, &FOLLOW_SEP_SENTENCE_in_syntax256); 
            	        if  (HASEXCEPTION())
            	        {
            	            goto rulesyntaxEx;
            	        }

            	        SEP_SENTENCE2_tree = (pANTLR3_BASE_TREE)(ADAPTOR->create(ADAPTOR, SEP_SENTENCE2));
            	        ADAPTOR->addChild(ADAPTOR, root_0, SEP_SENTENCE2_tree);


            	    }
            	    break;

            	default:
            	    goto loop1;	/* break out of the loop */
            	    break;
                }
            }
            loop1: ; /* Jump out to here if this rule does not match */

            EOF3 = (pANTLR3_COMMON_TOKEN) MATCHT(EOF, &FOLLOW_EOF_in_syntax260); 
            if  (HASEXCEPTION())
            {
                goto rulesyntaxEx;
            }

            EOF3_tree = (pANTLR3_BASE_TREE)(ADAPTOR->create(ADAPTOR, EOF3));
            ADAPTOR->addChild(ADAPTOR, root_0, EOF3_tree);


        }

    }
    

    // This is where rules clean up and exit
    //
    goto rulesyntaxEx; /* Prevent compiler warnings */
    rulesyntaxEx: ;
    retval.stop = LT(-1);

    	retval.stop = LT(-1);
    	retval.tree = (pANTLR3_BASE_TREE)(ADAPTOR->rulePostProcessing(ADAPTOR, root_0));
    	ADAPTOR->setTokenBoundaries(ADAPTOR, retval.tree, retval.start, retval.stop);





    return retval;
}
/* $ANTLR end syntax */

/** 
 * $ANTLR start sentence
 * grammar/scs.g:56:1: sentence : ( sentence_level1 | sentence_level2_6 | sentence_assignment );
 */
static scsParser_sentence_return
sentence(pscsParser ctx)
{   
    scsParser_sentence_return retval;

    pANTLR3_BASE_TREE root_0;

    scsParser_sentence_level1_return sentence_level14;
    #undef	RETURN_TYPE_sentence_level14
    #define	RETURN_TYPE_sentence_level14 scsParser_sentence_level1_return

    scsParser_sentence_level2_6_return sentence_level2_65;
    #undef	RETURN_TYPE_sentence_level2_65
    #define	RETURN_TYPE_sentence_level2_65 scsParser_sentence_level2_6_return

    scsParser_sentence_assignment_return sentence_assignment6;
    #undef	RETURN_TYPE_sentence_assignment6
    #define	RETURN_TYPE_sentence_assignment6 scsParser_sentence_assignment_return


    /* Initialize rule variables
     */


    root_0 = NULL;

    sentence_level14.tree = NULL;

    sentence_level2_65.tree = NULL;

    sentence_assignment6.tree = NULL;

    retval.start = LT(1); retval.stop = retval.start;



    retval.tree  = NULL;
    {
        {
            //  grammar/scs.g:57:2: ( sentence_level1 | sentence_level2_6 | sentence_assignment )
            
            ANTLR3_UINT32 alt2;

            alt2=3;

            switch ( LA(1) ) 
            {
            case ID_SYSTEM:
            case LINK:
            	{
            		switch ( LA(2) ) 
            		{
            		case SEP_SIMPLE:
            			{
            				alt2=1;
            			}
            		    break;
            		case SEP_ASSIGN:
            			{
            				alt2=3;
            			}
            		    break;
            		case CONNECTORS:
            			{
            				alt2=2;
            			}
            		    break;

            		default:
            		    CONSTRUCTEX();
            		    EXCEPTION->type         = ANTLR3_NO_VIABLE_ALT_EXCEPTION;
            		    EXCEPTION->message      = (void *)"";
            		    EXCEPTION->decisionNum  = 2;
            		    EXCEPTION->state        = 1;


            		    goto rulesentenceEx;
            		}

            	}
                break;
            case SEP_SENTENCE:
            	{
            		alt2=2;
            	}
                break;
            case SEP_LPAR:
            	{
            		switch ( LA(2) ) 
            		{
            		case ID_SYSTEM:
            		case LINK:
            			{
            				alt2=2;
            			}
            		    break;
            		case SEP_LPAR:
            			{
            				alt2=2;
            			}
            		    break;
            		case SEP_LTUPLE:
            			{
            				alt2=2;
            			}
            		    break;
            		case SEP_LSET:
            			{
            				alt2=2;
            			}
            		    break;
            		case CONTENT:
            			{
            				alt2=2;
            			}
            		    break;

            		default:
            		    CONSTRUCTEX();
            		    EXCEPTION->type         = ANTLR3_NO_VIABLE_ALT_EXCEPTION;
            		    EXCEPTION->message      = (void *)"";
            		    EXCEPTION->decisionNum  = 2;
            		    EXCEPTION->state        = 3;


            		    goto rulesentenceEx;
            		}

            	}
                break;
            case SEP_LTUPLE:
            	{
            		switch ( LA(2) ) 
            		{
            		case ID_SYSTEM:
            		case LINK:
            			{
            				alt2=2;
            			}
            		    break;
            		case SEP_LPAR:
            			{
            				alt2=2;
            			}
            		    break;
            		case SEP_LTUPLE:
            			{
            				alt2=2;
            			}
            		    break;
            		case SEP_LSET:
            			{
            				alt2=2;
            			}
            		    break;
            		case CONTENT:
            			{
            				alt2=2;
            			}
            		    break;

            		default:
            		    CONSTRUCTEX();
            		    EXCEPTION->type         = ANTLR3_NO_VIABLE_ALT_EXCEPTION;
            		    EXCEPTION->message      = (void *)"";
            		    EXCEPTION->decisionNum  = 2;
            		    EXCEPTION->state        = 4;


            		    goto rulesentenceEx;
            		}

            	}
                break;
            case SEP_LSET:
            	{
            		switch ( LA(2) ) 
            		{
            		case ID_SYSTEM:
            		case LINK:
            			{
            				alt2=2;
            			}
            		    break;
            		case SEP_LPAR:
            			{
            				alt2=2;
            			}
            		    break;
            		case SEP_LTUPLE:
            			{
            				alt2=2;
            			}
            		    break;
            		case SEP_LSET:
            			{
            				alt2=2;
            			}
            		    break;
            		case CONTENT:
            			{
            				alt2=2;
            			}
            		    break;

            		default:
            		    CONSTRUCTEX();
            		    EXCEPTION->type         = ANTLR3_NO_VIABLE_ALT_EXCEPTION;
            		    EXCEPTION->message      = (void *)"";
            		    EXCEPTION->decisionNum  = 2;
            		    EXCEPTION->state        = 5;


            		    goto rulesentenceEx;
            		}

            	}
                break;
            case CONTENT:
            	{
            		switch ( LA(2) ) 
            		{
            		case SEP_ASSIGN:
            			{
            				alt2=3;
            			}
            		    break;
            		case CONNECTORS:
            			{
            				alt2=2;
            			}
            		    break;

            		default:
            		    CONSTRUCTEX();
            		    EXCEPTION->type         = ANTLR3_NO_VIABLE_ALT_EXCEPTION;
            		    EXCEPTION->message      = (void *)"";
            		    EXCEPTION->decisionNum  = 2;
            		    EXCEPTION->state        = 6;


            		    goto rulesentenceEx;
            		}

            	}
                break;

            default:
                CONSTRUCTEX();
                EXCEPTION->type         = ANTLR3_NO_VIABLE_ALT_EXCEPTION;
                EXCEPTION->message      = (void *)"";
                EXCEPTION->decisionNum  = 2;
                EXCEPTION->state        = 0;


                goto rulesentenceEx;
            }

            switch (alt2) 
            {
        	case 1:
        	    // grammar/scs.g:57:4: sentence_level1
        	    {
        	        root_0 = (pANTLR3_BASE_TREE)(ADAPTOR->nilNode(ADAPTOR));

        	        FOLLOWPUSH(FOLLOW_sentence_level1_in_sentence272);
        	        sentence_level14=sentence_level1(ctx);

        	        FOLLOWPOP();
        	        if  (HASEXCEPTION())
        	        {
        	            goto rulesentenceEx;
        	        }

        	        ADAPTOR->addChild(ADAPTOR, root_0, sentence_level14.tree);

        	    }
        	    break;
        	case 2:
        	    // grammar/scs.g:58:4: sentence_level2_6
        	    {
        	        root_0 = (pANTLR3_BASE_TREE)(ADAPTOR->nilNode(ADAPTOR));

        	        FOLLOWPUSH(FOLLOW_sentence_level2_6_in_sentence277);
        	        sentence_level2_65=sentence_level2_6(ctx);

        	        FOLLOWPOP();
        	        if  (HASEXCEPTION())
        	        {
        	            goto rulesentenceEx;
        	        }

        	        ADAPTOR->addChild(ADAPTOR, root_0, sentence_level2_65.tree);

        	    }
        	    break;
        	case 3:
        	    // grammar/scs.g:59:4: sentence_assignment
        	    {
        	        root_0 = (pANTLR3_BASE_TREE)(ADAPTOR->nilNode(ADAPTOR));

        	        FOLLOWPUSH(FOLLOW_sentence_assignment_in_sentence282);
        	        sentence_assignment6=sentence_assignment(ctx);

        	        FOLLOWPOP();
        	        if  (HASEXCEPTION())
        	        {
        	            goto rulesentenceEx;
        	        }

        	        ADAPTOR->addChild(ADAPTOR, root_0, sentence_assignment6.tree);

        	    }
        	    break;

            }
        }
    }
    

    // This is where rules clean up and exit
    //
    goto rulesentenceEx; /* Prevent compiler warnings */
    rulesentenceEx: ;
    retval.stop = LT(-1);

    	retval.stop = LT(-1);
    	retval.tree = (pANTLR3_BASE_TREE)(ADAPTOR->rulePostProcessing(ADAPTOR, root_0));
    	ADAPTOR->setTokenBoundaries(ADAPTOR, retval.tree, retval.start, retval.stop);





    return retval;
}
/* $ANTLR end sentence */

/** 
 * $ANTLR start sentence_level1
 * grammar/scs.g:62:1: sentence_level1 : idtf_level1 SEP_SIMPLE idtf_level1 SEP_SIMPLE idtf_level1 ;
 */
static scsParser_sentence_level1_return
sentence_level1(pscsParser ctx)
{   
    scsParser_sentence_level1_return retval;

    pANTLR3_BASE_TREE root_0;

    pANTLR3_COMMON_TOKEN    SEP_SIMPLE8;
    pANTLR3_COMMON_TOKEN    SEP_SIMPLE10;
    scsParser_idtf_level1_return idtf_level17;
    #undef	RETURN_TYPE_idtf_level17
    #define	RETURN_TYPE_idtf_level17 scsParser_idtf_level1_return

    scsParser_idtf_level1_return idtf_level19;
    #undef	RETURN_TYPE_idtf_level19
    #define	RETURN_TYPE_idtf_level19 scsParser_idtf_level1_return

    scsParser_idtf_level1_return idtf_level111;
    #undef	RETURN_TYPE_idtf_level111
    #define	RETURN_TYPE_idtf_level111 scsParser_idtf_level1_return

    pANTLR3_BASE_TREE SEP_SIMPLE8_tree;
    pANTLR3_BASE_TREE SEP_SIMPLE10_tree;

    /* Initialize rule variables
     */


    root_0 = NULL;

    SEP_SIMPLE8       = NULL;
    SEP_SIMPLE10       = NULL;
    idtf_level17.tree = NULL;

    idtf_level19.tree = NULL;

    idtf_level111.tree = NULL;

    retval.start = LT(1); retval.stop = retval.start;

    SEP_SIMPLE8_tree   = NULL;
    SEP_SIMPLE10_tree   = NULL;


    retval.tree  = NULL;
    {
        // grammar/scs.g:63:2: ( idtf_level1 SEP_SIMPLE idtf_level1 SEP_SIMPLE idtf_level1 )
        // grammar/scs.g:63:4: idtf_level1 SEP_SIMPLE idtf_level1 SEP_SIMPLE idtf_level1
        {
            root_0 = (pANTLR3_BASE_TREE)(ADAPTOR->nilNode(ADAPTOR));

            FOLLOWPUSH(FOLLOW_idtf_level1_in_sentence_level1294);
            idtf_level17=idtf_level1(ctx);

            FOLLOWPOP();
            if  (HASEXCEPTION())
            {
                goto rulesentence_level1Ex;
            }

            ADAPTOR->addChild(ADAPTOR, root_0, idtf_level17.tree);
            SEP_SIMPLE8 = (pANTLR3_COMMON_TOKEN) MATCHT(SEP_SIMPLE, &FOLLOW_SEP_SIMPLE_in_sentence_level1296); 
            if  (HASEXCEPTION())
            {
                goto rulesentence_level1Ex;
            }

            SEP_SIMPLE8_tree = (pANTLR3_BASE_TREE)(ADAPTOR->create(ADAPTOR, SEP_SIMPLE8));
            ADAPTOR->addChild(ADAPTOR, root_0, SEP_SIMPLE8_tree);

            FOLLOWPUSH(FOLLOW_idtf_level1_in_sentence_level1298);
            idtf_level19=idtf_level1(ctx);

            FOLLOWPOP();
            if  (HASEXCEPTION())
            {
                goto rulesentence_level1Ex;
            }

            ADAPTOR->addChild(ADAPTOR, root_0, idtf_level19.tree);
            SEP_SIMPLE10 = (pANTLR3_COMMON_TOKEN) MATCHT(SEP_SIMPLE, &FOLLOW_SEP_SIMPLE_in_sentence_level1300); 
            if  (HASEXCEPTION())
            {
                goto rulesentence_level1Ex;
            }

            SEP_SIMPLE10_tree = (pANTLR3_BASE_TREE)(ADAPTOR->create(ADAPTOR, SEP_SIMPLE10));
            ADAPTOR->addChild(ADAPTOR, root_0, SEP_SIMPLE10_tree);

            FOLLOWPUSH(FOLLOW_idtf_level1_in_sentence_level1302);
            idtf_level111=idtf_level1(ctx);

            FOLLOWPOP();
            if  (HASEXCEPTION())
            {
                goto rulesentence_level1Ex;
            }

            ADAPTOR->addChild(ADAPTOR, root_0, idtf_level111.tree);

        }

    }
    

    // This is where rules clean up and exit
    //
    goto rulesentence_level1Ex; /* Prevent compiler warnings */
    rulesentence_level1Ex: ;
    retval.stop = LT(-1);

    	retval.stop = LT(-1);
    	retval.tree = (pANTLR3_BASE_TREE)(ADAPTOR->rulePostProcessing(ADAPTOR, root_0));
    	ADAPTOR->setTokenBoundaries(ADAPTOR, retval.tree, retval.start, retval.stop);





    return retval;
}
/* $ANTLR end sentence_level1 */

/** 
 * $ANTLR start sentence_level2_6
 * grammar/scs.g:66:1: sentence_level2_6 : ( | idtf CONNECTORS attrs_idtf_list );
 */
static scsParser_sentence_level2_6_return
sentence_level2_6(pscsParser ctx)
{   
    scsParser_sentence_level2_6_return retval;

    pANTLR3_BASE_TREE root_0;

    pANTLR3_COMMON_TOKEN    CONNECTORS13;
    scsParser_idtf_return idtf12;
    #undef	RETURN_TYPE_idtf12
    #define	RETURN_TYPE_idtf12 scsParser_idtf_return

    scsParser_attrs_idtf_list_return attrs_idtf_list14;
    #undef	RETURN_TYPE_attrs_idtf_list14
    #define	RETURN_TYPE_attrs_idtf_list14 scsParser_attrs_idtf_list_return

    pANTLR3_BASE_TREE CONNECTORS13_tree;

    /* Initialize rule variables
     */


    root_0 = NULL;

    CONNECTORS13       = NULL;
    idtf12.tree = NULL;

    attrs_idtf_list14.tree = NULL;

    retval.start = LT(1); retval.stop = retval.start;

    CONNECTORS13_tree   = NULL;


    retval.tree  = NULL;
    {
        {
            //  grammar/scs.g:67:2: ( | idtf CONNECTORS attrs_idtf_list )
            
            ANTLR3_UINT32 alt3;

            alt3=2;

            switch ( LA(1) ) 
            {
            case SEP_SENTENCE:
            	{
            		alt3=1;
            	}
                break;
            case SEP_LPAR:
            case SEP_LTUPLE:
            case SEP_LSET:
            case CONTENT:
            case ID_SYSTEM:
            case LINK:
            	{
            		alt3=2;
            	}
                break;

            default:
                CONSTRUCTEX();
                EXCEPTION->type         = ANTLR3_NO_VIABLE_ALT_EXCEPTION;
                EXCEPTION->message      = (void *)"";
                EXCEPTION->decisionNum  = 3;
                EXCEPTION->state        = 0;


                goto rulesentence_level2_6Ex;
            }

            switch (alt3) 
            {
        	case 1:
        	    // grammar/scs.g:68:2: 
        	    {
        	        root_0 = (pANTLR3_BASE_TREE)(ADAPTOR->nilNode(ADAPTOR));

        	    }
        	    break;
        	case 2:
        	    // grammar/scs.g:68:4: idtf CONNECTORS attrs_idtf_list
        	    {
        	        root_0 = (pANTLR3_BASE_TREE)(ADAPTOR->nilNode(ADAPTOR));

        	        FOLLOWPUSH(FOLLOW_idtf_in_sentence_level2_6317);
        	        idtf12=idtf(ctx);

        	        FOLLOWPOP();
        	        if  (HASEXCEPTION())
        	        {
        	            goto rulesentence_level2_6Ex;
        	        }

        	        ADAPTOR->addChild(ADAPTOR, root_0, idtf12.tree);
        	        CONNECTORS13 = (pANTLR3_COMMON_TOKEN) MATCHT(CONNECTORS, &FOLLOW_CONNECTORS_in_sentence_level2_6319); 
        	        if  (HASEXCEPTION())
        	        {
        	            goto rulesentence_level2_6Ex;
        	        }

        	        CONNECTORS13_tree = (pANTLR3_BASE_TREE)(ADAPTOR->create(ADAPTOR, CONNECTORS13));
        	        ADAPTOR->addChild(ADAPTOR, root_0, CONNECTORS13_tree);

        	        FOLLOWPUSH(FOLLOW_attrs_idtf_list_in_sentence_level2_6321);
        	        attrs_idtf_list14=attrs_idtf_list(ctx);

        	        FOLLOWPOP();
        	        if  (HASEXCEPTION())
        	        {
        	            goto rulesentence_level2_6Ex;
        	        }

        	        ADAPTOR->addChild(ADAPTOR, root_0, attrs_idtf_list14.tree);

        	    }
        	    break;

            }
        }
    }
    

    // This is where rules clean up and exit
    //
    goto rulesentence_level2_6Ex; /* Prevent compiler warnings */
    rulesentence_level2_6Ex: ;
    retval.stop = LT(-1);

    	retval.stop = LT(-1);
    	retval.tree = (pANTLR3_BASE_TREE)(ADAPTOR->rulePostProcessing(ADAPTOR, root_0));
    	ADAPTOR->setTokenBoundaries(ADAPTOR, retval.tree, retval.start, retval.stop);





    return retval;
}
/* $ANTLR end sentence_level2_6 */

/** 
 * $ANTLR start sentence_internal_list
 * grammar/scs.g:71:1: sentence_internal_list : SEP_LINT ( sentence_internal SEP_SENTENCE )* SEP_RINT ;
 */
static scsParser_sentence_internal_list_return
sentence_internal_list(pscsParser ctx)
{   
    scsParser_sentence_internal_list_return retval;

    pANTLR3_BASE_TREE root_0;

    pANTLR3_COMMON_TOKEN    SEP_LINT15;
    pANTLR3_COMMON_TOKEN    SEP_SENTENCE17;
    pANTLR3_COMMON_TOKEN    SEP_RINT18;
    scsParser_sentence_internal_return sentence_internal16;
    #undef	RETURN_TYPE_sentence_internal16
    #define	RETURN_TYPE_sentence_internal16 scsParser_sentence_internal_return

    pANTLR3_BASE_TREE SEP_LINT15_tree;
    pANTLR3_BASE_TREE SEP_SENTENCE17_tree;
    pANTLR3_BASE_TREE SEP_RINT18_tree;

    /* Initialize rule variables
     */


    root_0 = NULL;

    SEP_LINT15       = NULL;
    SEP_SENTENCE17       = NULL;
    SEP_RINT18       = NULL;
    sentence_internal16.tree = NULL;

    retval.start = LT(1); retval.stop = retval.start;

    SEP_LINT15_tree   = NULL;
    SEP_SENTENCE17_tree   = NULL;
    SEP_RINT18_tree   = NULL;


    retval.tree  = NULL;
    {
        // grammar/scs.g:72:2: ( SEP_LINT ( sentence_internal SEP_SENTENCE )* SEP_RINT )
        // grammar/scs.g:72:4: SEP_LINT ( sentence_internal SEP_SENTENCE )* SEP_RINT
        {
            root_0 = (pANTLR3_BASE_TREE)(ADAPTOR->nilNode(ADAPTOR));

            SEP_LINT15 = (pANTLR3_COMMON_TOKEN) MATCHT(SEP_LINT, &FOLLOW_SEP_LINT_in_sentence_internal_list333); 
            if  (HASEXCEPTION())
            {
                goto rulesentence_internal_listEx;
            }

            SEP_LINT15_tree = (pANTLR3_BASE_TREE)(ADAPTOR->create(ADAPTOR, SEP_LINT15));
            ADAPTOR->addChild(ADAPTOR, root_0, SEP_LINT15_tree);


            // grammar/scs.g:72:14: ( sentence_internal SEP_SENTENCE )*

            for (;;)
            {
                int alt4=2;
                switch ( LA(1) ) 
                {
                case CONNECTORS:
                	{
                		alt4=1;
                	}
                    break;

                }

                switch (alt4) 
                {
            	case 1:
            	    // grammar/scs.g:72:15: sentence_internal SEP_SENTENCE
            	    {
            	        FOLLOWPUSH(FOLLOW_sentence_internal_in_sentence_internal_list337);
            	        sentence_internal16=sentence_internal(ctx);

            	        FOLLOWPOP();
            	        if  (HASEXCEPTION())
            	        {
            	            goto rulesentence_internal_listEx;
            	        }

            	        ADAPTOR->addChild(ADAPTOR, root_0, sentence_internal16.tree);
            	        SEP_SENTENCE17 = (pANTLR3_COMMON_TOKEN) MATCHT(SEP_SENTENCE, &FOLLOW_SEP_SENTENCE_in_sentence_internal_list339); 
            	        if  (HASEXCEPTION())
            	        {
            	            goto rulesentence_internal_listEx;
            	        }

            	        SEP_SENTENCE17_tree = (pANTLR3_BASE_TREE)(ADAPTOR->create(ADAPTOR, SEP_SENTENCE17));
            	        ADAPTOR->addChild(ADAPTOR, root_0, SEP_SENTENCE17_tree);


            	    }
            	    break;

            	default:
            	    goto loop4;	/* break out of the loop */
            	    break;
                }
            }
            loop4: ; /* Jump out to here if this rule does not match */

            SEP_RINT18 = (pANTLR3_COMMON_TOKEN) MATCHT(SEP_RINT, &FOLLOW_SEP_RINT_in_sentence_internal_list343); 
            if  (HASEXCEPTION())
            {
                goto rulesentence_internal_listEx;
            }

            SEP_RINT18_tree = (pANTLR3_BASE_TREE)(ADAPTOR->create(ADAPTOR, SEP_RINT18));
            ADAPTOR->addChild(ADAPTOR, root_0, SEP_RINT18_tree);


        }

    }
    

    // This is where rules clean up and exit
    //
    goto rulesentence_internal_listEx; /* Prevent compiler warnings */
    rulesentence_internal_listEx: ;
    retval.stop = LT(-1);

    	retval.stop = LT(-1);
    	retval.tree = (pANTLR3_BASE_TREE)(ADAPTOR->rulePostProcessing(ADAPTOR, root_0));
    	ADAPTOR->setTokenBoundaries(ADAPTOR, retval.tree, retval.start, retval.stop);





    return retval;
}
/* $ANTLR end sentence_internal_list */

/** 
 * $ANTLR start sentence_assignment
 * grammar/scs.g:75:1: sentence_assignment : idtf SEP_ASSIGN idtf ;
 */
static scsParser_sentence_assignment_return
sentence_assignment(pscsParser ctx)
{   
    scsParser_sentence_assignment_return retval;

    pANTLR3_BASE_TREE root_0;

    pANTLR3_COMMON_TOKEN    SEP_ASSIGN20;
    scsParser_idtf_return idtf19;
    #undef	RETURN_TYPE_idtf19
    #define	RETURN_TYPE_idtf19 scsParser_idtf_return

    scsParser_idtf_return idtf21;
    #undef	RETURN_TYPE_idtf21
    #define	RETURN_TYPE_idtf21 scsParser_idtf_return

    pANTLR3_BASE_TREE SEP_ASSIGN20_tree;

    /* Initialize rule variables
     */


    root_0 = NULL;

    SEP_ASSIGN20       = NULL;
    idtf19.tree = NULL;

    idtf21.tree = NULL;

    retval.start = LT(1); retval.stop = retval.start;

    SEP_ASSIGN20_tree   = NULL;


    retval.tree  = NULL;
    {
        // grammar/scs.g:76:2: ( idtf SEP_ASSIGN idtf )
        // grammar/scs.g:76:4: idtf SEP_ASSIGN idtf
        {
            root_0 = (pANTLR3_BASE_TREE)(ADAPTOR->nilNode(ADAPTOR));

            FOLLOWPUSH(FOLLOW_idtf_in_sentence_assignment355);
            idtf19=idtf(ctx);

            FOLLOWPOP();
            if  (HASEXCEPTION())
            {
                goto rulesentence_assignmentEx;
            }

            ADAPTOR->addChild(ADAPTOR, root_0, idtf19.tree);
            SEP_ASSIGN20 = (pANTLR3_COMMON_TOKEN) MATCHT(SEP_ASSIGN, &FOLLOW_SEP_ASSIGN_in_sentence_assignment357); 
            if  (HASEXCEPTION())
            {
                goto rulesentence_assignmentEx;
            }

            SEP_ASSIGN20_tree = (pANTLR3_BASE_TREE)(ADAPTOR->create(ADAPTOR, SEP_ASSIGN20));
            ADAPTOR->addChild(ADAPTOR, root_0, SEP_ASSIGN20_tree);

            FOLLOWPUSH(FOLLOW_idtf_in_sentence_assignment359);
            idtf21=idtf(ctx);

            FOLLOWPOP();
            if  (HASEXCEPTION())
            {
                goto rulesentence_assignmentEx;
            }

            ADAPTOR->addChild(ADAPTOR, root_0, idtf21.tree);

        }

    }
    

    // This is where rules clean up and exit
    //
    goto rulesentence_assignmentEx; /* Prevent compiler warnings */
    rulesentence_assignmentEx: ;
    retval.stop = LT(-1);

    	retval.stop = LT(-1);
    	retval.tree = (pANTLR3_BASE_TREE)(ADAPTOR->rulePostProcessing(ADAPTOR, root_0));
    	ADAPTOR->setTokenBoundaries(ADAPTOR, retval.tree, retval.start, retval.stop);





    return retval;
}
/* $ANTLR end sentence_assignment */

/** 
 * $ANTLR start sentence_internal
 * grammar/scs.g:79:1: sentence_internal : CONNECTORS attrs_idtf_list ;
 */
static scsParser_sentence_internal_return
sentence_internal(pscsParser ctx)
{   
    scsParser_sentence_internal_return retval;

    pANTLR3_BASE_TREE root_0;

    pANTLR3_COMMON_TOKEN    CONNECTORS22;
    scsParser_attrs_idtf_list_return attrs_idtf_list23;
    #undef	RETURN_TYPE_attrs_idtf_list23
    #define	RETURN_TYPE_attrs_idtf_list23 scsParser_attrs_idtf_list_return

    pANTLR3_BASE_TREE CONNECTORS22_tree;

    /* Initialize rule variables
     */


    root_0 = NULL;

    CONNECTORS22       = NULL;
    attrs_idtf_list23.tree = NULL;

    retval.start = LT(1); retval.stop = retval.start;

    CONNECTORS22_tree   = NULL;


    retval.tree  = NULL;
    {
        // grammar/scs.g:80:2: ( CONNECTORS attrs_idtf_list )
        // grammar/scs.g:80:4: CONNECTORS attrs_idtf_list
        {
            root_0 = (pANTLR3_BASE_TREE)(ADAPTOR->nilNode(ADAPTOR));

            CONNECTORS22 = (pANTLR3_COMMON_TOKEN) MATCHT(CONNECTORS, &FOLLOW_CONNECTORS_in_sentence_internal371); 
            if  (HASEXCEPTION())
            {
                goto rulesentence_internalEx;
            }

            CONNECTORS22_tree = (pANTLR3_BASE_TREE)(ADAPTOR->create(ADAPTOR, CONNECTORS22));
            ADAPTOR->addChild(ADAPTOR, root_0, CONNECTORS22_tree);

            FOLLOWPUSH(FOLLOW_attrs_idtf_list_in_sentence_internal373);
            attrs_idtf_list23=attrs_idtf_list(ctx);

            FOLLOWPOP();
            if  (HASEXCEPTION())
            {
                goto rulesentence_internalEx;
            }

            ADAPTOR->addChild(ADAPTOR, root_0, attrs_idtf_list23.tree);

        }

    }
    

    // This is where rules clean up and exit
    //
    goto rulesentence_internalEx; /* Prevent compiler warnings */
    rulesentence_internalEx: ;
    retval.stop = LT(-1);

    	retval.stop = LT(-1);
    	retval.tree = (pANTLR3_BASE_TREE)(ADAPTOR->rulePostProcessing(ADAPTOR, root_0));
    	ADAPTOR->setTokenBoundaries(ADAPTOR, retval.tree, retval.start, retval.stop);





    return retval;
}
/* $ANTLR end sentence_internal */

/** 
 * $ANTLR start attrs_idtf_list
 * grammar/scs.g:83:1: attrs_idtf_list : idtf_attrs ( SEP_IDTF idtf_attrs )* ;
 */
static scsParser_attrs_idtf_list_return
attrs_idtf_list(pscsParser ctx)
{   
    scsParser_attrs_idtf_list_return retval;

    pANTLR3_BASE_TREE root_0;

    pANTLR3_COMMON_TOKEN    SEP_IDTF25;
    scsParser_idtf_attrs_return idtf_attrs24;
    #undef	RETURN_TYPE_idtf_attrs24
    #define	RETURN_TYPE_idtf_attrs24 scsParser_idtf_attrs_return

    scsParser_idtf_attrs_return idtf_attrs26;
    #undef	RETURN_TYPE_idtf_attrs26
    #define	RETURN_TYPE_idtf_attrs26 scsParser_idtf_attrs_return

    pANTLR3_BASE_TREE SEP_IDTF25_tree;

    /* Initialize rule variables
     */


    root_0 = NULL;

    SEP_IDTF25       = NULL;
    idtf_attrs24.tree = NULL;

    idtf_attrs26.tree = NULL;

    retval.start = LT(1); retval.stop = retval.start;

    SEP_IDTF25_tree   = NULL;


    retval.tree  = NULL;
    {
        // grammar/scs.g:84:2: ( idtf_attrs ( SEP_IDTF idtf_attrs )* )
        // grammar/scs.g:84:4: idtf_attrs ( SEP_IDTF idtf_attrs )*
        {
            root_0 = (pANTLR3_BASE_TREE)(ADAPTOR->nilNode(ADAPTOR));

            FOLLOWPUSH(FOLLOW_idtf_attrs_in_attrs_idtf_list385);
            idtf_attrs24=idtf_attrs(ctx);

            FOLLOWPOP();
            if  (HASEXCEPTION())
            {
                goto ruleattrs_idtf_listEx;
            }

            ADAPTOR->addChild(ADAPTOR, root_0, idtf_attrs24.tree);

            // grammar/scs.g:84:16: ( SEP_IDTF idtf_attrs )*

            for (;;)
            {
                int alt5=2;
                switch ( LA(1) ) 
                {
                case SEP_IDTF:
                	{
                		alt5=1;
                	}
                    break;

                }

                switch (alt5) 
                {
            	case 1:
            	    // grammar/scs.g:84:17: SEP_IDTF idtf_attrs
            	    {
            	        SEP_IDTF25 = (pANTLR3_COMMON_TOKEN) MATCHT(SEP_IDTF, &FOLLOW_SEP_IDTF_in_attrs_idtf_list389); 
            	        if  (HASEXCEPTION())
            	        {
            	            goto ruleattrs_idtf_listEx;
            	        }

            	        SEP_IDTF25_tree = (pANTLR3_BASE_TREE)(ADAPTOR->create(ADAPTOR, SEP_IDTF25));
            	        ADAPTOR->addChild(ADAPTOR, root_0, SEP_IDTF25_tree);

            	        FOLLOWPUSH(FOLLOW_idtf_attrs_in_attrs_idtf_list391);
            	        idtf_attrs26=idtf_attrs(ctx);

            	        FOLLOWPOP();
            	        if  (HASEXCEPTION())
            	        {
            	            goto ruleattrs_idtf_listEx;
            	        }

            	        ADAPTOR->addChild(ADAPTOR, root_0, idtf_attrs26.tree);

            	    }
            	    break;

            	default:
            	    goto loop5;	/* break out of the loop */
            	    break;
                }
            }
            loop5: ; /* Jump out to here if this rule does not match */


        }

    }
    

    // This is where rules clean up and exit
    //
    goto ruleattrs_idtf_listEx; /* Prevent compiler warnings */
    ruleattrs_idtf_listEx: ;
    retval.stop = LT(-1);

    	retval.stop = LT(-1);
    	retval.tree = (pANTLR3_BASE_TREE)(ADAPTOR->rulePostProcessing(ADAPTOR, root_0));
    	ADAPTOR->setTokenBoundaries(ADAPTOR, retval.tree, retval.start, retval.stop);





    return retval;
}
/* $ANTLR end attrs_idtf_list */

/** 
 * $ANTLR start idtf_attrs
 * grammar/scs.g:87:1: idtf_attrs : attrs_list idtf_internal ;
 */
static scsParser_idtf_attrs_return
idtf_attrs(pscsParser ctx)
{   
    scsParser_idtf_attrs_return retval;

    pANTLR3_BASE_TREE root_0;

    scsParser_attrs_list_return attrs_list27;
    #undef	RETURN_TYPE_attrs_list27
    #define	RETURN_TYPE_attrs_list27 scsParser_attrs_list_return

    scsParser_idtf_internal_return idtf_internal28;
    #undef	RETURN_TYPE_idtf_internal28
    #define	RETURN_TYPE_idtf_internal28 scsParser_idtf_internal_return


    /* Initialize rule variables
     */


    root_0 = NULL;

    attrs_list27.tree = NULL;

    idtf_internal28.tree = NULL;

    retval.start = LT(1); retval.stop = retval.start;



    retval.tree  = NULL;
    {
        // grammar/scs.g:88:2: ( attrs_list idtf_internal )
        // grammar/scs.g:88:4: attrs_list idtf_internal
        {
            root_0 = (pANTLR3_BASE_TREE)(ADAPTOR->nilNode(ADAPTOR));

            FOLLOWPUSH(FOLLOW_attrs_list_in_idtf_attrs405);
            attrs_list27=attrs_list(ctx);

            FOLLOWPOP();
            if  (HASEXCEPTION())
            {
                goto ruleidtf_attrsEx;
            }

            ADAPTOR->addChild(ADAPTOR, root_0, attrs_list27.tree);
            FOLLOWPUSH(FOLLOW_idtf_internal_in_idtf_attrs407);
            idtf_internal28=idtf_internal(ctx);

            FOLLOWPOP();
            if  (HASEXCEPTION())
            {
                goto ruleidtf_attrsEx;
            }

            ADAPTOR->addChild(ADAPTOR, root_0, idtf_internal28.tree);

        }

    }
    

    // This is where rules clean up and exit
    //
    goto ruleidtf_attrsEx; /* Prevent compiler warnings */
    ruleidtf_attrsEx: ;
    retval.stop = LT(-1);

    	retval.stop = LT(-1);
    	retval.tree = (pANTLR3_BASE_TREE)(ADAPTOR->rulePostProcessing(ADAPTOR, root_0));
    	ADAPTOR->setTokenBoundaries(ADAPTOR, retval.tree, retval.start, retval.stop);





    return retval;
}
/* $ANTLR end idtf_attrs */

/** 
 * $ANTLR start attrs_list
 * grammar/scs.g:91:1: attrs_list : ( idtf_level1 ( SEP_ATTR_VAR | SEP_ATTR_CONST ) )* ;
 */
static scsParser_attrs_list_return
attrs_list(pscsParser ctx)
{   
    scsParser_attrs_list_return retval;

    pANTLR3_BASE_TREE root_0;

    pANTLR3_COMMON_TOKEN    set30;
    scsParser_idtf_level1_return idtf_level129;
    #undef	RETURN_TYPE_idtf_level129
    #define	RETURN_TYPE_idtf_level129 scsParser_idtf_level1_return

    pANTLR3_BASE_TREE set30_tree;

    /* Initialize rule variables
     */


    root_0 = NULL;

    set30       = NULL;
    idtf_level129.tree = NULL;

    retval.start = LT(1); retval.stop = retval.start;

    set30_tree   = NULL;


    retval.tree  = NULL;
    {
        // grammar/scs.g:92:2: ( ( idtf_level1 ( SEP_ATTR_VAR | SEP_ATTR_CONST ) )* )
        // grammar/scs.g:92:4: ( idtf_level1 ( SEP_ATTR_VAR | SEP_ATTR_CONST ) )*
        {
            root_0 = (pANTLR3_BASE_TREE)(ADAPTOR->nilNode(ADAPTOR));


            // grammar/scs.g:92:4: ( idtf_level1 ( SEP_ATTR_VAR | SEP_ATTR_CONST ) )*

            for (;;)
            {
                int alt6=2;
                switch ( LA(1) ) 
                {
                case ID_SYSTEM:
                case LINK:
                	{
                		switch ( LA(2) ) 
                		{
                		case SEP_ATTR_CONST:
                		case SEP_ATTR_VAR:
                			{
                				alt6=1;
                			}
                		    break;

                		}

                	}
                    break;

                }

                switch (alt6) 
                {
            	case 1:
            	    // grammar/scs.g:92:5: idtf_level1 ( SEP_ATTR_VAR | SEP_ATTR_CONST )
            	    {
            	        FOLLOWPUSH(FOLLOW_idtf_level1_in_attrs_list420);
            	        idtf_level129=idtf_level1(ctx);

            	        FOLLOWPOP();
            	        if  (HASEXCEPTION())
            	        {
            	            goto ruleattrs_listEx;
            	        }

            	        ADAPTOR->addChild(ADAPTOR, root_0, idtf_level129.tree);
            	        set30=(pANTLR3_COMMON_TOKEN)LT(1);
            	        if ( ((LA(1) >= SEP_ATTR_CONST) && (LA(1) <= SEP_ATTR_VAR)) )
            	        {
            	            CONSUME();
            	            ADAPTOR->addChild(ADAPTOR, root_0, (pANTLR3_BASE_TREE)(ADAPTOR->create(ADAPTOR, set30)));
            	            PERRORRECOVERY=ANTLR3_FALSE;
            	        }
            	        else 
            	        {
            	            CONSTRUCTEX();
            	            EXCEPTION->type         = ANTLR3_MISMATCHED_SET_EXCEPTION;
            	            EXCEPTION->name         = (void *)ANTLR3_MISMATCHED_SET_NAME;
            	            EXCEPTION->expectingSet = &FOLLOW_set_in_attrs_list422;
            	            RECOVERFROMMISMATCHEDSET(&FOLLOW_set_in_attrs_list422);    goto ruleattrs_listEx;
            	        }


            	    }
            	    break;

            	default:
            	    goto loop6;	/* break out of the loop */
            	    break;
                }
            }
            loop6: ; /* Jump out to here if this rule does not match */


        }

    }
    

    // This is where rules clean up and exit
    //
    goto ruleattrs_listEx; /* Prevent compiler warnings */
    ruleattrs_listEx: ;
    retval.stop = LT(-1);

    	retval.stop = LT(-1);
    	retval.tree = (pANTLR3_BASE_TREE)(ADAPTOR->rulePostProcessing(ADAPTOR, root_0));
    	ADAPTOR->setTokenBoundaries(ADAPTOR, retval.tree, retval.start, retval.stop);





    return retval;
}
/* $ANTLR end attrs_list */

/** 
 * $ANTLR start idtf_internal
 * grammar/scs.g:95:1: idtf_internal : idtf ( sentence_internal_list )? ;
 */
static scsParser_idtf_internal_return
idtf_internal(pscsParser ctx)
{   
    scsParser_idtf_internal_return retval;

    pANTLR3_BASE_TREE root_0;

    scsParser_idtf_return idtf31;
    #undef	RETURN_TYPE_idtf31
    #define	RETURN_TYPE_idtf31 scsParser_idtf_return

    scsParser_sentence_internal_list_return sentence_internal_list32;
    #undef	RETURN_TYPE_sentence_internal_list32
    #define	RETURN_TYPE_sentence_internal_list32 scsParser_sentence_internal_list_return


    /* Initialize rule variables
     */


    root_0 = NULL;

    idtf31.tree = NULL;

    sentence_internal_list32.tree = NULL;

    retval.start = LT(1); retval.stop = retval.start;



    retval.tree  = NULL;
    {
        // grammar/scs.g:96:3: ( idtf ( sentence_internal_list )? )
        // grammar/scs.g:96:4: idtf ( sentence_internal_list )?
        {
            root_0 = (pANTLR3_BASE_TREE)(ADAPTOR->nilNode(ADAPTOR));

            FOLLOWPUSH(FOLLOW_idtf_in_idtf_internal442);
            idtf31=idtf(ctx);

            FOLLOWPOP();
            if  (HASEXCEPTION())
            {
                goto ruleidtf_internalEx;
            }

            ADAPTOR->addChild(ADAPTOR, root_0, idtf31.tree);

            // grammar/scs.g:96:9: ( sentence_internal_list )?
            {
                int alt7=2;
                switch ( LA(1) ) 
                {
                    case SEP_LINT:
                    	{
                    		alt7=1;
                    	}
                        break;
                }

                switch (alt7) 
                {
            	case 1:
            	    // grammar/scs.g:96:9: sentence_internal_list
            	    {
            	        FOLLOWPUSH(FOLLOW_sentence_internal_list_in_idtf_internal444);
            	        sentence_internal_list32=sentence_internal_list(ctx);

            	        FOLLOWPOP();
            	        if  (HASEXCEPTION())
            	        {
            	            goto ruleidtf_internalEx;
            	        }

            	        ADAPTOR->addChild(ADAPTOR, root_0, sentence_internal_list32.tree);

            	    }
            	    break;

                }
            }

        }

    }
    

    // This is where rules clean up and exit
    //
    goto ruleidtf_internalEx; /* Prevent compiler warnings */
    ruleidtf_internalEx: ;
    retval.stop = LT(-1);

    	retval.stop = LT(-1);
    	retval.tree = (pANTLR3_BASE_TREE)(ADAPTOR->rulePostProcessing(ADAPTOR, root_0));
    	ADAPTOR->setTokenBoundaries(ADAPTOR, retval.tree, retval.start, retval.stop);





    return retval;
}
/* $ANTLR end idtf_internal */

/** 
 * $ANTLR start idtf_tuple
 * grammar/scs.g:99:1: idtf_tuple : SEP_LTUPLE attrs_idtf_list SEP_RTUPLE ;
 */
static scsParser_idtf_tuple_return
idtf_tuple(pscsParser ctx)
{   
    scsParser_idtf_tuple_return retval;

    pANTLR3_BASE_TREE root_0;

    pANTLR3_COMMON_TOKEN    SEP_LTUPLE33;
    pANTLR3_COMMON_TOKEN    SEP_RTUPLE35;
    scsParser_attrs_idtf_list_return attrs_idtf_list34;
    #undef	RETURN_TYPE_attrs_idtf_list34
    #define	RETURN_TYPE_attrs_idtf_list34 scsParser_attrs_idtf_list_return

    pANTLR3_BASE_TREE SEP_LTUPLE33_tree;
    pANTLR3_BASE_TREE SEP_RTUPLE35_tree;

    /* Initialize rule variables
     */


    root_0 = NULL;

    SEP_LTUPLE33       = NULL;
    SEP_RTUPLE35       = NULL;
    attrs_idtf_list34.tree = NULL;

    retval.start = LT(1); retval.stop = retval.start;

    SEP_LTUPLE33_tree   = NULL;
    SEP_RTUPLE35_tree   = NULL;


    retval.tree  = NULL;
    {
        // grammar/scs.g:100:2: ( SEP_LTUPLE attrs_idtf_list SEP_RTUPLE )
        // grammar/scs.g:100:4: SEP_LTUPLE attrs_idtf_list SEP_RTUPLE
        {
            root_0 = (pANTLR3_BASE_TREE)(ADAPTOR->nilNode(ADAPTOR));

            SEP_LTUPLE33 = (pANTLR3_COMMON_TOKEN) MATCHT(SEP_LTUPLE, &FOLLOW_SEP_LTUPLE_in_idtf_tuple456); 
            if  (HASEXCEPTION())
            {
                goto ruleidtf_tupleEx;
            }

            SEP_LTUPLE33_tree = (pANTLR3_BASE_TREE)(ADAPTOR->create(ADAPTOR, SEP_LTUPLE33));
            ADAPTOR->addChild(ADAPTOR, root_0, SEP_LTUPLE33_tree);

            FOLLOWPUSH(FOLLOW_attrs_idtf_list_in_idtf_tuple458);
            attrs_idtf_list34=attrs_idtf_list(ctx);

            FOLLOWPOP();
            if  (HASEXCEPTION())
            {
                goto ruleidtf_tupleEx;
            }

            ADAPTOR->addChild(ADAPTOR, root_0, attrs_idtf_list34.tree);
            SEP_RTUPLE35 = (pANTLR3_COMMON_TOKEN) MATCHT(SEP_RTUPLE, &FOLLOW_SEP_RTUPLE_in_idtf_tuple461); 
            if  (HASEXCEPTION())
            {
                goto ruleidtf_tupleEx;
            }

            SEP_RTUPLE35_tree = (pANTLR3_BASE_TREE)(ADAPTOR->create(ADAPTOR, SEP_RTUPLE35));
            ADAPTOR->addChild(ADAPTOR, root_0, SEP_RTUPLE35_tree);


        }

    }
    

    // This is where rules clean up and exit
    //
    goto ruleidtf_tupleEx; /* Prevent compiler warnings */
    ruleidtf_tupleEx: ;
    retval.stop = LT(-1);

    	retval.stop = LT(-1);
    	retval.tree = (pANTLR3_BASE_TREE)(ADAPTOR->rulePostProcessing(ADAPTOR, root_0));
    	ADAPTOR->setTokenBoundaries(ADAPTOR, retval.tree, retval.start, retval.stop);





    return retval;
}
/* $ANTLR end idtf_tuple */

/** 
 * $ANTLR start idtf_set
 * grammar/scs.g:103:1: idtf_set : SEP_LSET attrs_idtf_list SEP_RSET ;
 */
static scsParser_idtf_set_return
idtf_set(pscsParser ctx)
{   
    scsParser_idtf_set_return retval;

    pANTLR3_BASE_TREE root_0;

    pANTLR3_COMMON_TOKEN    SEP_LSET36;
    pANTLR3_COMMON_TOKEN    SEP_RSET38;
    scsParser_attrs_idtf_list_return attrs_idtf_list37;
    #undef	RETURN_TYPE_attrs_idtf_list37
    #define	RETURN_TYPE_attrs_idtf_list37 scsParser_attrs_idtf_list_return

    pANTLR3_BASE_TREE SEP_LSET36_tree;
    pANTLR3_BASE_TREE SEP_RSET38_tree;

    /* Initialize rule variables
     */


    root_0 = NULL;

    SEP_LSET36       = NULL;
    SEP_RSET38       = NULL;
    attrs_idtf_list37.tree = NULL;

    retval.start = LT(1); retval.stop = retval.start;

    SEP_LSET36_tree   = NULL;
    SEP_RSET38_tree   = NULL;


    retval.tree  = NULL;
    {
        // grammar/scs.g:104:2: ( SEP_LSET attrs_idtf_list SEP_RSET )
        // grammar/scs.g:104:4: SEP_LSET attrs_idtf_list SEP_RSET
        {
            root_0 = (pANTLR3_BASE_TREE)(ADAPTOR->nilNode(ADAPTOR));

            SEP_LSET36 = (pANTLR3_COMMON_TOKEN) MATCHT(SEP_LSET, &FOLLOW_SEP_LSET_in_idtf_set473); 
            if  (HASEXCEPTION())
            {
                goto ruleidtf_setEx;
            }

            SEP_LSET36_tree = (pANTLR3_BASE_TREE)(ADAPTOR->create(ADAPTOR, SEP_LSET36));
            ADAPTOR->addChild(ADAPTOR, root_0, SEP_LSET36_tree);

            FOLLOWPUSH(FOLLOW_attrs_idtf_list_in_idtf_set475);
            attrs_idtf_list37=attrs_idtf_list(ctx);

            FOLLOWPOP();
            if  (HASEXCEPTION())
            {
                goto ruleidtf_setEx;
            }

            ADAPTOR->addChild(ADAPTOR, root_0, attrs_idtf_list37.tree);
            SEP_RSET38 = (pANTLR3_COMMON_TOKEN) MATCHT(SEP_RSET, &FOLLOW_SEP_RSET_in_idtf_set477); 
            if  (HASEXCEPTION())
            {
                goto ruleidtf_setEx;
            }

            SEP_RSET38_tree = (pANTLR3_BASE_TREE)(ADAPTOR->create(ADAPTOR, SEP_RSET38));
            ADAPTOR->addChild(ADAPTOR, root_0, SEP_RSET38_tree);


        }

    }
    

    // This is where rules clean up and exit
    //
    goto ruleidtf_setEx; /* Prevent compiler warnings */
    ruleidtf_setEx: ;
    retval.stop = LT(-1);

    	retval.stop = LT(-1);
    	retval.tree = (pANTLR3_BASE_TREE)(ADAPTOR->rulePostProcessing(ADAPTOR, root_0));
    	ADAPTOR->setTokenBoundaries(ADAPTOR, retval.tree, retval.start, retval.stop);





    return retval;
}
/* $ANTLR end idtf_set */

/** 
 * $ANTLR start idtf
 * grammar/scs.g:107:1: idtf : ( idtf_level1 | idtf_edge | idtf_tuple | idtf_set | CONTENT );
 */
static scsParser_idtf_return
idtf(pscsParser ctx)
{   
    scsParser_idtf_return retval;

    pANTLR3_BASE_TREE root_0;

    pANTLR3_COMMON_TOKEN    CONTENT43;
    scsParser_idtf_level1_return idtf_level139;
    #undef	RETURN_TYPE_idtf_level139
    #define	RETURN_TYPE_idtf_level139 scsParser_idtf_level1_return

    scsParser_idtf_edge_return idtf_edge40;
    #undef	RETURN_TYPE_idtf_edge40
    #define	RETURN_TYPE_idtf_edge40 scsParser_idtf_edge_return

    scsParser_idtf_tuple_return idtf_tuple41;
    #undef	RETURN_TYPE_idtf_tuple41
    #define	RETURN_TYPE_idtf_tuple41 scsParser_idtf_tuple_return

    scsParser_idtf_set_return idtf_set42;
    #undef	RETURN_TYPE_idtf_set42
    #define	RETURN_TYPE_idtf_set42 scsParser_idtf_set_return

    pANTLR3_BASE_TREE CONTENT43_tree;

    /* Initialize rule variables
     */


    root_0 = NULL;

    CONTENT43       = NULL;
    idtf_level139.tree = NULL;

    idtf_edge40.tree = NULL;

    idtf_tuple41.tree = NULL;

    idtf_set42.tree = NULL;

    retval.start = LT(1); retval.stop = retval.start;

    CONTENT43_tree   = NULL;


    retval.tree  = NULL;
    {
        {
            //  grammar/scs.g:108:2: ( idtf_level1 | idtf_edge | idtf_tuple | idtf_set | CONTENT )
            
            ANTLR3_UINT32 alt8;

            alt8=5;

            switch ( LA(1) ) 
            {
            case ID_SYSTEM:
            case LINK:
            	{
            		alt8=1;
            	}
                break;
            case SEP_LPAR:
            	{
            		alt8=2;
            	}
                break;
            case SEP_LTUPLE:
            	{
            		alt8=3;
            	}
                break;
            case SEP_LSET:
            	{
            		alt8=4;
            	}
                break;
            case CONTENT:
            	{
            		alt8=5;
            	}
                break;

            default:
                CONSTRUCTEX();
                EXCEPTION->type         = ANTLR3_NO_VIABLE_ALT_EXCEPTION;
                EXCEPTION->message      = (void *)"";
                EXCEPTION->decisionNum  = 8;
                EXCEPTION->state        = 0;


                goto ruleidtfEx;
            }

            switch (alt8) 
            {
        	case 1:
        	    // grammar/scs.g:108:4: idtf_level1
        	    {
        	        root_0 = (pANTLR3_BASE_TREE)(ADAPTOR->nilNode(ADAPTOR));

        	        FOLLOWPUSH(FOLLOW_idtf_level1_in_idtf488);
        	        idtf_level139=idtf_level1(ctx);

        	        FOLLOWPOP();
        	        if  (HASEXCEPTION())
        	        {
        	            goto ruleidtfEx;
        	        }

        	        ADAPTOR->addChild(ADAPTOR, root_0, idtf_level139.tree);

        	    }
        	    break;
        	case 2:
        	    // grammar/scs.g:109:4: idtf_edge
        	    {
        	        root_0 = (pANTLR3_BASE_TREE)(ADAPTOR->nilNode(ADAPTOR));

        	        FOLLOWPUSH(FOLLOW_idtf_edge_in_idtf493);
        	        idtf_edge40=idtf_edge(ctx);

        	        FOLLOWPOP();
        	        if  (HASEXCEPTION())
        	        {
        	            goto ruleidtfEx;
        	        }

        	        ADAPTOR->addChild(ADAPTOR, root_0, idtf_edge40.tree);

        	    }
        	    break;
        	case 3:
        	    // grammar/scs.g:110:4: idtf_tuple
        	    {
        	        root_0 = (pANTLR3_BASE_TREE)(ADAPTOR->nilNode(ADAPTOR));

        	        FOLLOWPUSH(FOLLOW_idtf_tuple_in_idtf498);
        	        idtf_tuple41=idtf_tuple(ctx);

        	        FOLLOWPOP();
        	        if  (HASEXCEPTION())
        	        {
        	            goto ruleidtfEx;
        	        }

        	        ADAPTOR->addChild(ADAPTOR, root_0, idtf_tuple41.tree);

        	    }
        	    break;
        	case 4:
        	    // grammar/scs.g:111:4: idtf_set
        	    {
        	        root_0 = (pANTLR3_BASE_TREE)(ADAPTOR->nilNode(ADAPTOR));

        	        FOLLOWPUSH(FOLLOW_idtf_set_in_idtf503);
        	        idtf_set42=idtf_set(ctx);

        	        FOLLOWPOP();
        	        if  (HASEXCEPTION())
        	        {
        	            goto ruleidtfEx;
        	        }

        	        ADAPTOR->addChild(ADAPTOR, root_0, idtf_set42.tree);

        	    }
        	    break;
        	case 5:
        	    // grammar/scs.g:112:4: CONTENT
        	    {
        	        root_0 = (pANTLR3_BASE_TREE)(ADAPTOR->nilNode(ADAPTOR));

        	        CONTENT43 = (pANTLR3_COMMON_TOKEN) MATCHT(CONTENT, &FOLLOW_CONTENT_in_idtf508); 
        	        if  (HASEXCEPTION())
        	        {
        	            goto ruleidtfEx;
        	        }

        	        CONTENT43_tree = (pANTLR3_BASE_TREE)(ADAPTOR->create(ADAPTOR, CONTENT43));
        	        ADAPTOR->addChild(ADAPTOR, root_0, CONTENT43_tree);


        	    }
        	    break;

            }
        }
    }
    

    // This is where rules clean up and exit
    //
    goto ruleidtfEx; /* Prevent compiler warnings */
    ruleidtfEx: ;
    retval.stop = LT(-1);

    	retval.stop = LT(-1);
    	retval.tree = (pANTLR3_BASE_TREE)(ADAPTOR->rulePostProcessing(ADAPTOR, root_0));
    	ADAPTOR->setTokenBoundaries(ADAPTOR, retval.tree, retval.start, retval.stop);





    return retval;
}
/* $ANTLR end idtf */

/** 
 * $ANTLR start idtf_level1
 * grammar/scs.g:115:1: idtf_level1 : ( ID_SYSTEM | LINK );
 */
static scsParser_idtf_level1_return
idtf_level1(pscsParser ctx)
{   
    scsParser_idtf_level1_return retval;

    pANTLR3_BASE_TREE root_0;

    pANTLR3_COMMON_TOKEN    set44;

    pANTLR3_BASE_TREE set44_tree;

    /* Initialize rule variables
     */


    root_0 = NULL;

    set44       = NULL;
    retval.start = LT(1); retval.stop = retval.start;

    set44_tree   = NULL;


    retval.tree  = NULL;
    {
        // grammar/scs.g:116:2: ( ID_SYSTEM | LINK )
        // grammar/scs.g:
        {
            root_0 = (pANTLR3_BASE_TREE)(ADAPTOR->nilNode(ADAPTOR));

            set44=(pANTLR3_COMMON_TOKEN)LT(1);
            if ( ((LA(1) >= ID_SYSTEM) && (LA(1) <= LINK)) )
            {
                CONSUME();
                ADAPTOR->addChild(ADAPTOR, root_0, (pANTLR3_BASE_TREE)(ADAPTOR->create(ADAPTOR, set44)));
                PERRORRECOVERY=ANTLR3_FALSE;
            }
            else 
            {
                CONSTRUCTEX();
                EXCEPTION->type         = ANTLR3_MISMATCHED_SET_EXCEPTION;
                EXCEPTION->name         = (void *)ANTLR3_MISMATCHED_SET_NAME;
                EXCEPTION->expectingSet = &FOLLOW_set_in_idtf_level10;
                RECOVERFROMMISMATCHEDSET(&FOLLOW_set_in_idtf_level10);    goto ruleidtf_level1Ex;
            }


        }

    }
    

    // This is where rules clean up and exit
    //
    goto ruleidtf_level1Ex; /* Prevent compiler warnings */
    ruleidtf_level1Ex: ;
    retval.stop = LT(-1);

    	retval.stop = LT(-1);
    	retval.tree = (pANTLR3_BASE_TREE)(ADAPTOR->rulePostProcessing(ADAPTOR, root_0));
    	ADAPTOR->setTokenBoundaries(ADAPTOR, retval.tree, retval.start, retval.stop);





    return retval;
}
/* $ANTLR end idtf_level1 */

/** 
 * $ANTLR start idtf_edge
 * grammar/scs.g:122:1: idtf_edge : SEP_LPAR idtf CONNECTORS idtf SEP_RPAR ;
 */
static scsParser_idtf_edge_return
idtf_edge(pscsParser ctx)
{   
    scsParser_idtf_edge_return retval;

    pANTLR3_BASE_TREE root_0;

    pANTLR3_COMMON_TOKEN    SEP_LPAR45;
    pANTLR3_COMMON_TOKEN    CONNECTORS47;
    pANTLR3_COMMON_TOKEN    SEP_RPAR49;
    scsParser_idtf_return idtf46;
    #undef	RETURN_TYPE_idtf46
    #define	RETURN_TYPE_idtf46 scsParser_idtf_return

    scsParser_idtf_return idtf48;
    #undef	RETURN_TYPE_idtf48
    #define	RETURN_TYPE_idtf48 scsParser_idtf_return

    pANTLR3_BASE_TREE SEP_LPAR45_tree;
    pANTLR3_BASE_TREE CONNECTORS47_tree;
    pANTLR3_BASE_TREE SEP_RPAR49_tree;

    /* Initialize rule variables
     */


    root_0 = NULL;

    SEP_LPAR45       = NULL;
    CONNECTORS47       = NULL;
    SEP_RPAR49       = NULL;
    idtf46.tree = NULL;

    idtf48.tree = NULL;

    retval.start = LT(1); retval.stop = retval.start;

    SEP_LPAR45_tree   = NULL;
    CONNECTORS47_tree   = NULL;
    SEP_RPAR49_tree   = NULL;


    retval.tree  = NULL;
    {
        // grammar/scs.g:123:2: ( SEP_LPAR idtf CONNECTORS idtf SEP_RPAR )
        // grammar/scs.g:123:4: SEP_LPAR idtf CONNECTORS idtf SEP_RPAR
        {
            root_0 = (pANTLR3_BASE_TREE)(ADAPTOR->nilNode(ADAPTOR));

            SEP_LPAR45 = (pANTLR3_COMMON_TOKEN) MATCHT(SEP_LPAR, &FOLLOW_SEP_LPAR_in_idtf_edge537); 
            if  (HASEXCEPTION())
            {
                goto ruleidtf_edgeEx;
            }

            SEP_LPAR45_tree = (pANTLR3_BASE_TREE)(ADAPTOR->create(ADAPTOR, SEP_LPAR45));
            ADAPTOR->addChild(ADAPTOR, root_0, SEP_LPAR45_tree);

            FOLLOWPUSH(FOLLOW_idtf_in_idtf_edge539);
            idtf46=idtf(ctx);

            FOLLOWPOP();
            if  (HASEXCEPTION())
            {
                goto ruleidtf_edgeEx;
            }

            ADAPTOR->addChild(ADAPTOR, root_0, idtf46.tree);
            CONNECTORS47 = (pANTLR3_COMMON_TOKEN) MATCHT(CONNECTORS, &FOLLOW_CONNECTORS_in_idtf_edge541); 
            if  (HASEXCEPTION())
            {
                goto ruleidtf_edgeEx;
            }

            CONNECTORS47_tree = (pANTLR3_BASE_TREE)(ADAPTOR->create(ADAPTOR, CONNECTORS47));
            ADAPTOR->addChild(ADAPTOR, root_0, CONNECTORS47_tree);

            FOLLOWPUSH(FOLLOW_idtf_in_idtf_edge543);
            idtf48=idtf(ctx);

            FOLLOWPOP();
            if  (HASEXCEPTION())
            {
                goto ruleidtf_edgeEx;
            }

            ADAPTOR->addChild(ADAPTOR, root_0, idtf48.tree);
            SEP_RPAR49 = (pANTLR3_COMMON_TOKEN) MATCHT(SEP_RPAR, &FOLLOW_SEP_RPAR_in_idtf_edge545); 
            if  (HASEXCEPTION())
            {
                goto ruleidtf_edgeEx;
            }

            SEP_RPAR49_tree = (pANTLR3_BASE_TREE)(ADAPTOR->create(ADAPTOR, SEP_RPAR49));
            ADAPTOR->addChild(ADAPTOR, root_0, SEP_RPAR49_tree);


        }

    }
    

    // This is where rules clean up and exit
    //
    goto ruleidtf_edgeEx; /* Prevent compiler warnings */
    ruleidtf_edgeEx: ;
    retval.stop = LT(-1);

    	retval.stop = LT(-1);
    	retval.tree = (pANTLR3_BASE_TREE)(ADAPTOR->rulePostProcessing(ADAPTOR, root_0));
    	ADAPTOR->setTokenBoundaries(ADAPTOR, retval.tree, retval.start, retval.stop);





    return retval;
}
/* $ANTLR end idtf_edge */
/* End of parsing rules
 * ==============================================
 */

/* ==============================================
 * Syntactic predicates
 */
/* End of syntactic predicates
 * ==============================================
 */

 
 



/* End of code
 * =============================================================================
 */
